/* Generated by Yosys 0.65+71 (git sha1 e56c6a954, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:14.1-120.10" *)
module wb_bridge(clk_i, rst_ni, wb_adr_i, wb_dat_i, wb_dat_o, wb_sel_i, wb_we_i, wb_stb_i, wb_cyc_i, wb_ack_o, wb_err_o, apb_paddr, apb_pwdata, apb_prdata, apb_pwrite, apb_psel, apb_penable, apb_pready, apb_pslverr);
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:15.24-15.29" *)
  input clk_i;
  wire clk_i;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:16.24-16.30" *)
  input rst_ni;
  wire rst_ni;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:19.24-19.32" *)
  input [31:0] wb_adr_i;
  wire [31:0] wb_adr_i;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:20.24-20.32" *)
  input [31:0] wb_dat_i;
  wire [31:0] wb_dat_i;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:21.24-21.32" *)
  output [31:0] wb_dat_o;
  wire [31:0] wb_dat_o;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:22.24-22.32" *)
  input [3:0] wb_sel_i;
  wire [3:0] wb_sel_i;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:23.24-23.31" *)
  input wb_we_i;
  wire wb_we_i;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:24.24-24.32" *)
  input wb_stb_i;
  wire wb_stb_i;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:25.24-25.32" *)
  input wb_cyc_i;
  wire wb_cyc_i;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:26.24-26.32" *)
  output wb_ack_o;
  wire wb_ack_o;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:27.24-27.32" *)
  output wb_err_o;
  wire wb_err_o;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:30.24-30.33" *)
  output [31:0] apb_paddr;
  wire [31:0] apb_paddr;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:31.24-31.34" *)
  output [31:0] apb_pwdata;
  wire [31:0] apb_pwdata;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:32.24-32.34" *)
  input [31:0] apb_prdata;
  wire [31:0] apb_prdata;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:33.24-33.34" *)
  output apb_pwrite;
  wire apb_pwrite;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:34.24-34.32" *)
  output apb_psel;
  wire apb_psel;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:35.24-35.35" *)
  output apb_penable;
  wire apb_penable;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:36.24-36.34" *)
  input apb_pready;
  wire apb_pready;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:37.24-37.35" *)
  input apb_pslverr;
  wire apb_pslverr;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:49.15-49.20" *)
  wire [1:0] state;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:41.10-41.22" *)
  wire wb_in_window;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _037_ (
    .A(state[1]),
    .SLEEP(state[0]),
    .X(apb_penable)
  );
  sky130_fd_sc_hd__and3b_1 _038_ (
    .A_N(state[0]),
    .B(apb_pready),
    .C(state[1]),
    .X(_000_)
  );
  sky130_fd_sc_hd__nand2_1 _039_ (
    .A(wb_cyc_i),
    .B(wb_stb_i),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand4b_1 _040_ (
    .A_N(state[1]),
    .B(wb_adr_i[31]),
    .C(wb_cyc_i),
    .D(wb_stb_i),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o21bai_1 _041_ (
    .A1(state[0]),
    .A2(_036_),
    .B1_N(_000_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _042_ (
    .A0(wb_dat_o[30]),
    .A1(apb_prdata[30]),
    .S(_000_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _043_ (
    .A0(wb_dat_o[29]),
    .A1(apb_prdata[29]),
    .S(_000_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _044_ (
    .A0(wb_dat_o[28]),
    .A1(apb_prdata[28]),
    .S(_000_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _045_ (
    .A0(wb_dat_o[27]),
    .A1(apb_prdata[27]),
    .S(_000_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _046_ (
    .A0(wb_dat_o[26]),
    .A1(apb_prdata[26]),
    .S(_000_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _047_ (
    .A0(wb_dat_o[25]),
    .A1(apb_prdata[25]),
    .S(_000_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _048_ (
    .A0(wb_dat_o[24]),
    .A1(apb_prdata[24]),
    .S(_000_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _049_ (
    .A0(wb_dat_o[23]),
    .A1(apb_prdata[23]),
    .S(_000_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _050_ (
    .A0(wb_dat_o[22]),
    .A1(apb_prdata[22]),
    .S(_000_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _051_ (
    .A0(wb_dat_o[21]),
    .A1(apb_prdata[21]),
    .S(_000_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _052_ (
    .A0(wb_dat_o[20]),
    .A1(apb_prdata[20]),
    .S(_000_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _053_ (
    .A0(wb_dat_o[19]),
    .A1(apb_prdata[19]),
    .S(_000_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _054_ (
    .A0(wb_dat_o[18]),
    .A1(apb_prdata[18]),
    .S(_000_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _055_ (
    .A0(wb_dat_o[17]),
    .A1(apb_prdata[17]),
    .S(_000_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _056_ (
    .A0(wb_dat_o[16]),
    .A1(apb_prdata[16]),
    .S(_000_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _057_ (
    .A0(wb_dat_o[15]),
    .A1(apb_prdata[15]),
    .S(_000_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _058_ (
    .A0(wb_dat_o[14]),
    .A1(apb_prdata[14]),
    .S(_000_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _059_ (
    .A0(wb_dat_o[13]),
    .A1(apb_prdata[13]),
    .S(_000_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _060_ (
    .A0(wb_dat_o[12]),
    .A1(apb_prdata[12]),
    .S(_000_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _061_ (
    .A0(wb_dat_o[11]),
    .A1(apb_prdata[11]),
    .S(_000_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _062_ (
    .A0(wb_dat_o[10]),
    .A1(apb_prdata[10]),
    .S(_000_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _063_ (
    .A0(wb_dat_o[9]),
    .A1(apb_prdata[9]),
    .S(_000_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _064_ (
    .A0(wb_dat_o[8]),
    .A1(apb_prdata[8]),
    .S(_000_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _065_ (
    .A0(wb_dat_o[7]),
    .A1(apb_prdata[7]),
    .S(_000_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _066_ (
    .A0(wb_dat_o[6]),
    .A1(apb_prdata[6]),
    .S(_000_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _067_ (
    .A0(wb_dat_o[5]),
    .A1(apb_prdata[5]),
    .S(_000_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _068_ (
    .A0(wb_dat_o[4]),
    .A1(apb_prdata[4]),
    .S(_000_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _069_ (
    .A0(wb_dat_o[3]),
    .A1(apb_prdata[3]),
    .S(_000_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _070_ (
    .A0(wb_dat_o[2]),
    .A1(apb_prdata[2]),
    .S(_000_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _071_ (
    .A0(wb_dat_o[1]),
    .A1(apb_prdata[1]),
    .S(_000_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _072_ (
    .A0(wb_dat_o[0]),
    .A1(apb_prdata[0]),
    .S(_000_),
    .X(_032_)
  );
  sky130_fd_sc_hd__xor2_1 _073_ (
    .A(state[0]),
    .B(state[1]),
    .X(apb_psel)
  );
  sky130_fd_sc_hd__mux2_1 _074_ (
    .A0(wb_dat_o[31]),
    .A1(apb_prdata[31]),
    .S(_000_),
    .X(_033_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _075_ (
    .A1_N(apb_pslverr),
    .A2_N(_000_),
    .B1(_035_),
    .B2(wb_adr_i[31]),
    .Y(wb_err_o)
  );
  sky130_fd_sc_hd__xor2_1 _076_ (
    .A(state[0]),
    .B(state[1]),
    .X(_034_)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _077_ (
    .CLK(clk_i),
    .D(_032_),
    .Q(wb_dat_o[0]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _078_ (
    .CLK(clk_i),
    .D(_031_),
    .Q(wb_dat_o[1]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _079_ (
    .CLK(clk_i),
    .D(_030_),
    .Q(wb_dat_o[2]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _080_ (
    .CLK(clk_i),
    .D(_029_),
    .Q(wb_dat_o[3]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _081_ (
    .CLK(clk_i),
    .D(_028_),
    .Q(wb_dat_o[4]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _082_ (
    .CLK(clk_i),
    .D(_027_),
    .Q(wb_dat_o[5]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _083_ (
    .CLK(clk_i),
    .D(_026_),
    .Q(wb_dat_o[6]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _084_ (
    .CLK(clk_i),
    .D(_025_),
    .Q(wb_dat_o[7]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _085_ (
    .CLK(clk_i),
    .D(_024_),
    .Q(wb_dat_o[8]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _086_ (
    .CLK(clk_i),
    .D(_023_),
    .Q(wb_dat_o[9]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _087_ (
    .CLK(clk_i),
    .D(_022_),
    .Q(wb_dat_o[10]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _088_ (
    .CLK(clk_i),
    .D(_021_),
    .Q(wb_dat_o[11]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _089_ (
    .CLK(clk_i),
    .D(_020_),
    .Q(wb_dat_o[12]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _090_ (
    .CLK(clk_i),
    .D(_019_),
    .Q(wb_dat_o[13]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _091_ (
    .CLK(clk_i),
    .D(_018_),
    .Q(wb_dat_o[14]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _092_ (
    .CLK(clk_i),
    .D(_017_),
    .Q(wb_dat_o[15]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _093_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(wb_dat_o[16]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _094_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(wb_dat_o[17]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _095_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(wb_dat_o[18]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _096_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(wb_dat_o[19]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _097_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(wb_dat_o[20]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _098_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(wb_dat_o[21]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _099_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(wb_dat_o[22]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _100_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(wb_dat_o[23]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _101_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(wb_dat_o[24]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _102_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(wb_dat_o[25]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _103_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(wb_dat_o[26]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _104_ (
    .CLK(clk_i),
    .D(_005_),
    .Q(wb_dat_o[27]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _105_ (
    .CLK(clk_i),
    .D(_004_),
    .Q(wb_dat_o[28]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _106_ (
    .CLK(clk_i),
    .D(_003_),
    .Q(wb_dat_o[29]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _107_ (
    .CLK(clk_i),
    .D(_002_),
    .Q(wb_dat_o[30]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _108_ (
    .CLK(clk_i),
    .D(_033_),
    .Q(wb_dat_o[31]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:51.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _109_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(state[0]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:51.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _110_ (
    .CLK(clk_i),
    .D(_034_),
    .Q(state[1]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-wb_bridge/rtl/wb_bridge.v:103.5-115.8" *)
  sky130_fd_sc_hd__dfrtp_1 _111_ (
    .CLK(clk_i),
    .D(_000_),
    .Q(wb_ack_o),
    .RESET_B(rst_ni)
  );
  assign wb_in_window = wb_adr_i[31];
  assign apb_pwrite = wb_we_i;
  assign apb_pwdata = wb_dat_i;
  assign apb_paddr = { 1'h0, wb_adr_i[30:0] };
endmodule
