/* Generated by Yosys 0.65+71 (git sha1 e56c6a954, clang++ 18.1.8 -fPIC -O3) */

(* src = "rtl-gpio/rtl/EF_GPIO8.v:20.1-113.10" *)
module EF_GPIO8(clk, rst_n, io_in, bus_in, io_out, bus_out, io_oe, bus_oe, pin0_hi, pin1_hi, pin2_hi, pin3_hi, pin4_hi, pin5_hi, pin6_hi, pin7_hi, pin0_lo, pin1_lo, pin2_lo, pin3_lo, pin4_lo
, pin5_lo, pin6_lo, pin7_lo, pin0_pe, pin1_pe, pin2_pe, pin3_pe, pin4_pe, pin5_pe, pin6_pe, pin7_pe, pin0_ne, pin1_ne, pin2_ne, pin3_ne, pin4_ne, pin5_ne, pin6_ne, pin7_ne);
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:21.25-21.28" *)
  input clk;
  wire clk;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:22.25-22.30" *)
  input rst_n;
  wire rst_n;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:23.25-23.30" *)
  input [7:0] io_in;
  wire [7:0] io_in;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:24.25-24.31" *)
  output [7:0] bus_in;
  wire [7:0] bus_in;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:25.25-25.31" *)
  output [7:0] io_out;
  wire [7:0] io_out;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:26.25-26.32" *)
  input [7:0] bus_out;
  wire [7:0] bus_out;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:27.25-27.30" *)
  output [7:0] io_oe;
  wire [7:0] io_oe;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:28.25-28.31" *)
  input [7:0] bus_oe;
  wire [7:0] bus_oe;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:30.17-30.24" *)
  output pin0_hi;
  wire pin0_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:31.17-31.24" *)
  output pin1_hi;
  wire pin1_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:32.17-32.24" *)
  output pin2_hi;
  wire pin2_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:33.17-33.24" *)
  output pin3_hi;
  wire pin3_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:34.17-34.24" *)
  output pin4_hi;
  wire pin4_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:35.17-35.24" *)
  output pin5_hi;
  wire pin5_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:36.17-36.24" *)
  output pin6_hi;
  wire pin6_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:37.17-37.24" *)
  output pin7_hi;
  wire pin7_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:39.17-39.24" *)
  output pin0_lo;
  wire pin0_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:40.17-40.24" *)
  output pin1_lo;
  wire pin1_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:41.17-41.24" *)
  output pin2_lo;
  wire pin2_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:42.17-42.24" *)
  output pin3_lo;
  wire pin3_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:43.17-43.24" *)
  output pin4_lo;
  wire pin4_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:44.17-44.24" *)
  output pin5_lo;
  wire pin5_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:45.17-45.24" *)
  output pin6_lo;
  wire pin6_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:46.17-46.24" *)
  output pin7_lo;
  wire pin7_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:48.17-48.24" *)
  output pin0_pe;
  wire pin0_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:49.17-49.24" *)
  output pin1_pe;
  wire pin1_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:50.17-50.24" *)
  output pin2_pe;
  wire pin2_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:51.17-51.24" *)
  output pin3_pe;
  wire pin3_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:52.17-52.24" *)
  output pin4_pe;
  wire pin4_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:53.17-53.24" *)
  output pin5_pe;
  wire pin5_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:54.17-54.24" *)
  output pin6_pe;
  wire pin6_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:55.17-55.24" *)
  output pin7_pe;
  wire pin7_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:57.17-57.24" *)
  output pin0_ne;
  wire pin0_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:58.17-58.24" *)
  output pin1_ne;
  wire pin1_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:59.17-59.24" *)
  output pin2_ne;
  wire pin2_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:60.17-60.24" *)
  output pin3_ne;
  wire pin3_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:61.17-61.24" *)
  output pin4_ne;
  wire pin4_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:62.17-62.24" *)
  output pin5_ne;
  wire pin5_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:63.17-63.24" *)
  output pin6_ne;
  wire pin6_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:64.17-64.24" *)
  output pin7_ne;
  wire pin7_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:67.16-67.26" *)
  wire [7:0] sync_io_in;
  sky130_fd_sc_hd__clkinv_1 _0_ (
    .A(pin7_hi),
    .Y(pin7_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _1_ (
    .A(pin6_hi),
    .Y(pin6_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _2_ (
    .A(pin5_hi),
    .Y(pin5_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _3_ (
    .A(pin4_hi),
    .Y(pin4_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _4_ (
    .A(pin3_hi),
    .Y(pin3_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _5_ (
    .A(pin2_hi),
    .Y(pin2_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _6_ (
    .A(pin1_hi),
    .Y(pin1_lo)
  );
  sky130_fd_sc_hd__clkinv_1 _7_ (
    .A(pin0_hi),
    .Y(pin0_lo)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:102.17-102.69" *)
  ef_util_ned ned_0 (
    .clk(clk),
    .in(pin0_hi),
    .out(pin0_ne)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:103.17-103.69" *)
  ef_util_ned ned_1 (
    .clk(clk),
    .in(pin1_hi),
    .out(pin1_ne)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:104.17-104.69" *)
  ef_util_ned ned_2 (
    .clk(clk),
    .in(pin2_hi),
    .out(pin2_ne)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:105.17-105.69" *)
  ef_util_ned ned_3 (
    .clk(clk),
    .in(pin3_hi),
    .out(pin3_ne)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:106.17-106.69" *)
  ef_util_ned ned_4 (
    .clk(clk),
    .in(pin4_hi),
    .out(pin4_ne)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:107.17-107.69" *)
  ef_util_ned ned_5 (
    .clk(clk),
    .in(pin5_hi),
    .out(pin5_ne)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:108.17-108.69" *)
  ef_util_ned ned_6 (
    .clk(clk),
    .in(pin6_hi),
    .out(pin6_ne)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:109.17-109.69" *)
  ef_util_ned ned_7 (
    .clk(clk),
    .in(pin7_hi),
    .out(pin7_ne)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:93.17-93.69" *)
  ef_util_ped ped_0 (
    .clk(clk),
    .in(pin0_hi),
    .out(pin0_pe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:94.17-94.69" *)
  ef_util_ped ped_1 (
    .clk(clk),
    .in(pin1_hi),
    .out(pin1_pe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:95.17-95.69" *)
  ef_util_ped ped_2 (
    .clk(clk),
    .in(pin2_hi),
    .out(pin2_pe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:96.17-96.69" *)
  ef_util_ped ped_3 (
    .clk(clk),
    .in(pin3_hi),
    .out(pin3_pe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:97.17-97.69" *)
  ef_util_ped ped_4 (
    .clk(clk),
    .in(pin4_hi),
    .out(pin4_pe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:98.17-98.69" *)
  ef_util_ped ped_5 (
    .clk(clk),
    .in(pin5_hi),
    .out(pin5_pe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:99.17-99.69" *)
  ef_util_ped ped_6 (
    .clk(clk),
    .in(pin6_hi),
    .out(pin6_pe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:100.17-100.69" *)
  ef_util_ped ped_7 (
    .clk(clk),
    .in(pin7_hi),
    .out(pin7_pe)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:69.18-69.77" *)
  ef_util_sync \synchronizer[0]  (
    .clk(clk),
    .in(io_in[0]),
    .out(pin0_hi)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:69.18-69.77" *)
  ef_util_sync \synchronizer[1]  (
    .clk(clk),
    .in(io_in[1]),
    .out(pin1_hi)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:69.18-69.77" *)
  ef_util_sync \synchronizer[2]  (
    .clk(clk),
    .in(io_in[2]),
    .out(pin2_hi)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:69.18-69.77" *)
  ef_util_sync \synchronizer[3]  (
    .clk(clk),
    .in(io_in[3]),
    .out(pin3_hi)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:69.18-69.77" *)
  ef_util_sync \synchronizer[4]  (
    .clk(clk),
    .in(io_in[4]),
    .out(pin4_hi)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:69.18-69.77" *)
  ef_util_sync \synchronizer[5]  (
    .clk(clk),
    .in(io_in[5]),
    .out(pin5_hi)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:69.18-69.77" *)
  ef_util_sync \synchronizer[6]  (
    .clk(clk),
    .in(io_in[6]),
    .out(pin6_hi)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8.v:69.18-69.77" *)
  ef_util_sync \synchronizer[7]  (
    .clk(clk),
    .in(io_in[7]),
    .out(pin7_hi)
  );
  assign sync_io_in = { pin7_hi, pin6_hi, pin5_hi, pin4_hi, pin3_hi, pin2_hi, pin1_hi, pin0_hi };
  assign io_oe = bus_oe;
  assign io_out = bus_out;
  assign bus_in = { pin7_hi, pin6_hi, pin5_hi, pin4_hi, pin3_hi, pin2_hi, pin1_hi, pin0_hi };
endmodule

(* top =  1  *)
(* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:25.1-363.10" *)
module EF_GPIO8_APB(PCLK, PRESETn, PWRITE, PWDATA, PADDR, PENABLE, PSEL, PREADY, PRDATA, IRQ, io_in, io_out, io_oe);
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:27.25-27.29" *)
  input PCLK;
  wire PCLK;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:28.25-28.32" *)
  input PRESETn;
  wire PRESETn;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:29.25-29.31" *)
  input PWRITE;
  wire PWRITE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:30.25-30.31" *)
  input [31:0] PWDATA;
  wire [31:0] PWDATA;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:31.25-31.30" *)
  input [31:0] PADDR;
  wire [31:0] PADDR;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:32.25-32.32" *)
  input PENABLE;
  wire PENABLE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:33.25-33.29" *)
  input PSEL;
  wire PSEL;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:34.25-34.31" *)
  output PREADY;
  wire PREADY;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:35.25-35.31" *)
  output [31:0] PRDATA;
  wire [31:0] PRDATA;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:36.25-36.28" *)
  output IRQ;
  wire IRQ;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:37.25-37.30" *)
  input [7:0] io_in;
  wire [7:0] io_in;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:38.25-38.31" *)
  output [7:0] io_out;
  wire [7:0] io_out;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:39.25-39.30" *)
  output [7:0] io_oe;
  wire [7:0] io_oe;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  wire [31:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  wire _284_;
  wire _285_;
  wire _286_;
  wire _287_;
  wire _288_;
  wire _289_;
  wire _290_;
  wire _291_;
  wire _292_;
  wire _293_;
  wire _294_;
  wire _295_;
  wire _296_;
  wire _297_;
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire _304_;
  wire _305_;
  wire _306_;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:106.16-106.26" *)
  wire [7:0] DATAI_WIRE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:109.13-109.22" *)
  wire [7:0] DATAO_REG;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:115.13-115.20" *)
  wire [7:0] DIR_REG;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:50.13-50.21" *)
  wire [0:0] GCLK_REG;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:127.17-127.23" *)
  wire [31:0] IC_REG;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:126.17-126.23" *)
  wire [31:0] IM_REG;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:139.14-139.18" *)
  wire [0:0] P0HI;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:147.14-147.18" *)
  wire [0:0] P0LO;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:163.14-163.18" *)
  wire [0:0] P0NE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:155.14-155.18" *)
  wire [0:0] P0PE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:140.14-140.18" *)
  wire [0:0] P1HI;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:148.14-148.18" *)
  wire [0:0] P1LO;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:164.14-164.18" *)
  wire [0:0] P1NE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:156.14-156.18" *)
  wire [0:0] P1PE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:141.14-141.18" *)
  wire [0:0] P2HI;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:149.14-149.18" *)
  wire [0:0] P2LO;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:165.14-165.18" *)
  wire [0:0] P2NE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:157.14-157.18" *)
  wire [0:0] P2PE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:142.14-142.18" *)
  wire [0:0] P3HI;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:150.14-150.18" *)
  wire [0:0] P3LO;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:166.14-166.18" *)
  wire [0:0] P3NE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:158.14-158.18" *)
  wire [0:0] P3PE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:143.14-143.18" *)
  wire [0:0] P4HI;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:151.14-151.18" *)
  wire [0:0] P4LO;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:167.14-167.18" *)
  wire [0:0] P4NE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:159.14-159.18" *)
  wire [0:0] P4PE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:144.14-144.18" *)
  wire [0:0] P5HI;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:152.14-152.18" *)
  wire [0:0] P5LO;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:168.14-168.18" *)
  wire [0:0] P5NE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:160.14-160.18" *)
  wire [0:0] P5PE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:145.14-145.18" *)
  wire [0:0] P6HI;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:153.14-153.18" *)
  wire [0:0] P6LO;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:169.14-169.18" *)
  wire [0:0] P6NE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:161.14-161.18" *)
  wire [0:0] P6PE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:146.14-146.18" *)
  wire [0:0] P7HI;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:154.14-154.18" *)
  wire [0:0] P7LO;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:170.14-170.18" *)
  wire [0:0] P7NE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:162.14-162.18" *)
  wire [0:0] P7PE;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:128.17-128.24" *)
  wire [31:0] RIS_REG;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:69.16-69.22" *)
  wire [7:0] bus_in;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:71.16-71.22" *)
  wire [7:0] bus_oe;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:70.16-70.23" *)
  wire [7:0] bus_out;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:62.16-62.19" *)
  wire clk;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:51.8-51.13" *)
  wire clk_g;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:53.8-53.20" *)
  wire clk_gated_en;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:72.16-72.23" *)
  wire [0:0] pin0_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:80.16-80.23" *)
  wire [0:0] pin0_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:96.16-96.23" *)
  wire [0:0] pin0_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:88.16-88.23" *)
  wire [0:0] pin0_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:73.16-73.23" *)
  wire [0:0] pin1_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:81.16-81.23" *)
  wire [0:0] pin1_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:97.16-97.23" *)
  wire [0:0] pin1_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:89.16-89.23" *)
  wire [0:0] pin1_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:74.16-74.23" *)
  wire [0:0] pin2_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:82.16-82.23" *)
  wire [0:0] pin2_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:98.16-98.23" *)
  wire [0:0] pin2_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:90.16-90.23" *)
  wire [0:0] pin2_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:75.16-75.23" *)
  wire [0:0] pin3_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:83.16-83.23" *)
  wire [0:0] pin3_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:99.16-99.23" *)
  wire [0:0] pin3_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:91.16-91.23" *)
  wire [0:0] pin3_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:76.16-76.23" *)
  wire [0:0] pin4_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:84.16-84.23" *)
  wire [0:0] pin4_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:100.16-100.23" *)
  wire [0:0] pin4_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:92.16-92.23" *)
  wire [0:0] pin4_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:77.16-77.23" *)
  wire [0:0] pin5_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:85.16-85.23" *)
  wire [0:0] pin5_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:101.16-101.23" *)
  wire [0:0] pin5_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:93.16-93.23" *)
  wire [0:0] pin5_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:78.16-78.23" *)
  wire [0:0] pin6_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:86.16-86.23" *)
  wire [0:0] pin6_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:102.16-102.23" *)
  wire [0:0] pin6_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:94.16-94.23" *)
  wire [0:0] pin6_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:79.16-79.23" *)
  wire [0:0] pin7_hi;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:87.16-87.23" *)
  wire [0:0] pin7_lo;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:103.16-103.23" *)
  wire [0:0] pin7_ne;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:95.16-95.23" *)
  wire [0:0] pin7_pe;
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:63.16-63.21" *)
  wire rst_n;
  sky130_fd_sc_hd__nor4_1 _307_ (
    .A(PADDR[10]),
    .B(PADDR[9]),
    .C(PADDR[8]),
    .D(PADDR[15]),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor4_1 _308_ (
    .A(PADDR[14]),
    .B(PADDR[13]),
    .C(PADDR[12]),
    .D(PADDR[11]),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand2_1 _309_ (
    .A(_082_),
    .B(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__or3b_1 _310_ (
    .A(PADDR[0]),
    .B(PADDR[1]),
    .C_N(PADDR[3]),
    .X(_085_)
  );
  sky130_fd_sc_hd__nor2_1 _311_ (
    .A(PADDR[6]),
    .B(PADDR[7]),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor3_1 _312_ (
    .A(PADDR[6]),
    .B(PADDR[7]),
    .C(PADDR[4]),
    .Y(_087_)
  );
  sky130_fd_sc_hd__nor2_1 _313_ (
    .A(PADDR[5]),
    .B(PADDR[2]),
    .Y(_088_)
  );
  sky130_fd_sc_hd__nor4_1 _314_ (
    .A(PADDR[6]),
    .B(PADDR[7]),
    .C(PADDR[5]),
    .D(PADDR[4]),
    .Y(_089_)
  );
  sky130_fd_sc_hd__and3b_1 _315_ (
    .A_N(_085_),
    .B(_087_),
    .C(_088_),
    .X(_090_)
  );
  sky130_fd_sc_hd__nand3b_1 _316_ (
    .A_N(_085_),
    .B(_087_),
    .C(_088_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nor2_1 _317_ (
    .A(_084_),
    .B(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__nand3_1 _318_ (
    .A(_082_),
    .B(_083_),
    .C(_090_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__nor3_1 _319_ (
    .A(PADDR[3]),
    .B(PADDR[0]),
    .C(PADDR[1]),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nand2_1 _320_ (
    .A(PADDR[2]),
    .B(_089_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__nand3_1 _321_ (
    .A(PADDR[2]),
    .B(_089_),
    .C(_094_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nor2_1 _322_ (
    .A(_084_),
    .B(_096_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _323_ (
    .A(_084_),
    .SLEEP(_096_),
    .X(_098_)
  );
  sky130_fd_sc_hd__nand3_1 _324_ (
    .A(_087_),
    .B(_088_),
    .C(_094_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__nor2_1 _325_ (
    .A(_084_),
    .B(_099_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__nor3_1 _326_ (
    .A(_092_),
    .B(_097_),
    .C(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__nand4_1 _327_ (
    .A(PADDR[10]),
    .B(PADDR[9]),
    .C(PADDR[8]),
    .D(PADDR[15]),
    .Y(_102_)
  );
  sky130_fd_sc_hd__nand4_1 _328_ (
    .A(PADDR[14]),
    .B(PADDR[13]),
    .C(PADDR[12]),
    .D(PADDR[11]),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nor2_1 _329_ (
    .A(_102_),
    .B(_103_),
    .Y(_104_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _330_ (
    .A(_102_),
    .SLEEP(_103_),
    .X(_105_)
  );
  sky130_fd_sc_hd__nor2_1 _331_ (
    .A(_099_),
    .B(_105_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _332_ (
    .A(_099_),
    .SLEEP(_105_),
    .X(_107_)
  );
  sky130_fd_sc_hd__nor2_1 _333_ (
    .A(_096_),
    .B(_105_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__nor2_1 _334_ (
    .A(_091_),
    .B(_105_),
    .Y(_109_)
  );
  sky130_fd_sc_hd__nand4_1 _335_ (
    .A(PADDR[4]),
    .B(_086_),
    .C(_088_),
    .D(_094_),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a21oi_1 _336_ (
    .A1(_091_),
    .A2(_110_),
    .B1(_105_),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand3_1 _337_ (
    .A(RIS_REG[26]),
    .B(_090_),
    .C(_104_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a21oi_1 _338_ (
    .A1(_111_),
    .A2(_112_),
    .B1(_108_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__a311oi_1 _339_ (
    .A1(RIS_REG[26]),
    .A2(IM_REG[26]),
    .A3(_108_),
    .B1(_113_),
    .C1(_106_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__o21ai_0 _340_ (
    .A1(IM_REG[26]),
    .A2(_107_),
    .B1(_101_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nor2_1 _341_ (
    .A(_114_),
    .B(_115_),
    .Y(PRDATA[26])
  );
  sky130_fd_sc_hd__nand3_1 _342_ (
    .A(RIS_REG[25]),
    .B(_090_),
    .C(_104_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__a21oi_1 _343_ (
    .A1(_111_),
    .A2(_116_),
    .B1(_108_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__a31oi_1 _344_ (
    .A1(RIS_REG[25]),
    .A2(IM_REG[25]),
    .A3(_108_),
    .B1(_117_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__o21ai_0 _345_ (
    .A1(IM_REG[25]),
    .A2(_107_),
    .B1(_101_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nor2_1 _346_ (
    .A(_118_),
    .B(_119_),
    .Y(PRDATA[25])
  );
  sky130_fd_sc_hd__nand2_1 _347_ (
    .A(RIS_REG[24]),
    .B(_108_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(_107_),
    .B(_120_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__a22o_1 _349_ (
    .A1(RIS_REG[24]),
    .A2(_109_),
    .B1(_121_),
    .B2(IM_REG[24]),
    .X(PRDATA[24])
  );
  sky130_fd_sc_hd__nand3_1 _350_ (
    .A(RIS_REG[23]),
    .B(_090_),
    .C(_104_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__a21oi_1 _351_ (
    .A1(_111_),
    .A2(_122_),
    .B1(_108_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__a31oi_1 _352_ (
    .A1(RIS_REG[23]),
    .A2(IM_REG[23]),
    .A3(_108_),
    .B1(_123_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__o21ai_0 _353_ (
    .A1(IM_REG[23]),
    .A2(_107_),
    .B1(_101_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__nor2_1 _354_ (
    .A(_124_),
    .B(_125_),
    .Y(PRDATA[23])
  );
  sky130_fd_sc_hd__nand2_1 _355_ (
    .A(RIS_REG[22]),
    .B(_108_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__nand2_1 _356_ (
    .A(_107_),
    .B(_126_),
    .Y(_127_)
  );
  sky130_fd_sc_hd__a22o_1 _357_ (
    .A1(RIS_REG[22]),
    .A2(_109_),
    .B1(_127_),
    .B2(IM_REG[22]),
    .X(PRDATA[22])
  );
  sky130_fd_sc_hd__nand3_1 _358_ (
    .A(RIS_REG[21]),
    .B(_090_),
    .C(_104_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__a21oi_1 _359_ (
    .A1(_111_),
    .A2(_128_),
    .B1(_108_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a311oi_1 _360_ (
    .A1(RIS_REG[21]),
    .A2(IM_REG[21]),
    .A3(_108_),
    .B1(_129_),
    .C1(_106_),
    .Y(_130_)
  );
  sky130_fd_sc_hd__o21ai_0 _361_ (
    .A1(IM_REG[21]),
    .A2(_107_),
    .B1(_101_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__nor2_1 _362_ (
    .A(_130_),
    .B(_131_),
    .Y(PRDATA[21])
  );
  sky130_fd_sc_hd__nand2_1 _363_ (
    .A(RIS_REG[20]),
    .B(_108_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__nand2_1 _364_ (
    .A(_107_),
    .B(_132_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a22o_1 _365_ (
    .A1(RIS_REG[20]),
    .A2(_109_),
    .B1(_133_),
    .B2(IM_REG[20]),
    .X(PRDATA[20])
  );
  sky130_fd_sc_hd__nand3_1 _366_ (
    .A(RIS_REG[19]),
    .B(_090_),
    .C(_104_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__a21oi_1 _367_ (
    .A1(_111_),
    .A2(_134_),
    .B1(_108_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nand2_1 _368_ (
    .A(RIS_REG[19]),
    .B(IM_REG[19]),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a31oi_1 _369_ (
    .A1(RIS_REG[19]),
    .A2(IM_REG[19]),
    .A3(_108_),
    .B1(_135_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__o21ai_0 _370_ (
    .A1(IM_REG[19]),
    .A2(_107_),
    .B1(_101_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _371_ (
    .A(_137_),
    .B(_138_),
    .Y(PRDATA[19])
  );
  sky130_fd_sc_hd__nand3_1 _372_ (
    .A(RIS_REG[18]),
    .B(_090_),
    .C(_104_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__a21oi_1 _373_ (
    .A1(_111_),
    .A2(_139_),
    .B1(_108_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__a311oi_1 _374_ (
    .A1(RIS_REG[18]),
    .A2(IM_REG[18]),
    .A3(_108_),
    .B1(_140_),
    .C1(_106_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__o21ai_0 _375_ (
    .A1(IM_REG[18]),
    .A2(_107_),
    .B1(_101_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__nor2_1 _376_ (
    .A(_141_),
    .B(_142_),
    .Y(PRDATA[18])
  );
  sky130_fd_sc_hd__nand2_1 _377_ (
    .A(RIS_REG[17]),
    .B(_108_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__nand2_1 _378_ (
    .A(_107_),
    .B(_143_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__a22o_1 _379_ (
    .A1(RIS_REG[17]),
    .A2(_109_),
    .B1(_144_),
    .B2(IM_REG[17]),
    .X(PRDATA[17])
  );
  sky130_fd_sc_hd__nand3_1 _380_ (
    .A(RIS_REG[16]),
    .B(_090_),
    .C(_104_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a21oi_1 _381_ (
    .A1(_111_),
    .A2(_145_),
    .B1(_108_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__a31oi_1 _382_ (
    .A1(RIS_REG[16]),
    .A2(IM_REG[16]),
    .A3(_108_),
    .B1(_146_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__o21ai_0 _383_ (
    .A1(IM_REG[16]),
    .A2(_107_),
    .B1(_101_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__nor2_1 _384_ (
    .A(_147_),
    .B(_148_),
    .Y(PRDATA[16])
  );
  sky130_fd_sc_hd__nand3_1 _385_ (
    .A(RIS_REG[15]),
    .B(_090_),
    .C(_104_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__a21oi_1 _386_ (
    .A1(_111_),
    .A2(_149_),
    .B1(_108_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__a31oi_1 _387_ (
    .A1(RIS_REG[15]),
    .A2(IM_REG[15]),
    .A3(_108_),
    .B1(_150_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__o21ai_0 _388_ (
    .A1(IM_REG[15]),
    .A2(_107_),
    .B1(_101_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__nor2_1 _389_ (
    .A(_151_),
    .B(_152_),
    .Y(PRDATA[15])
  );
  sky130_fd_sc_hd__nand2_1 _390_ (
    .A(RIS_REG[14]),
    .B(_108_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nand2_1 _391_ (
    .A(_107_),
    .B(_153_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__a22o_1 _392_ (
    .A1(RIS_REG[14]),
    .A2(_109_),
    .B1(_154_),
    .B2(IM_REG[14]),
    .X(PRDATA[14])
  );
  sky130_fd_sc_hd__nand3_1 _393_ (
    .A(RIS_REG[13]),
    .B(_090_),
    .C(_104_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__a21oi_1 _394_ (
    .A1(_111_),
    .A2(_155_),
    .B1(_108_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__a31oi_1 _395_ (
    .A1(RIS_REG[13]),
    .A2(IM_REG[13]),
    .A3(_108_),
    .B1(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__o21ai_0 _396_ (
    .A1(IM_REG[13]),
    .A2(_107_),
    .B1(_101_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__nor2_1 _397_ (
    .A(_157_),
    .B(_158_),
    .Y(PRDATA[13])
  );
  sky130_fd_sc_hd__nand3_1 _398_ (
    .A(RIS_REG[12]),
    .B(_090_),
    .C(_104_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a21oi_1 _399_ (
    .A1(_111_),
    .A2(_159_),
    .B1(_108_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__a311oi_1 _400_ (
    .A1(RIS_REG[12]),
    .A2(IM_REG[12]),
    .A3(_108_),
    .B1(_160_),
    .C1(_106_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__o21ai_0 _401_ (
    .A1(IM_REG[12]),
    .A2(_107_),
    .B1(_101_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__nor2_1 _402_ (
    .A(_161_),
    .B(_162_),
    .Y(PRDATA[12])
  );
  sky130_fd_sc_hd__nand3_1 _403_ (
    .A(RIS_REG[11]),
    .B(_090_),
    .C(_104_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a21oi_1 _404_ (
    .A1(_111_),
    .A2(_163_),
    .B1(_108_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__a31oi_1 _405_ (
    .A1(RIS_REG[11]),
    .A2(IM_REG[11]),
    .A3(_108_),
    .B1(_164_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__o21ai_0 _406_ (
    .A1(IM_REG[11]),
    .A2(_107_),
    .B1(_101_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nor2_1 _407_ (
    .A(_165_),
    .B(_166_),
    .Y(PRDATA[11])
  );
  sky130_fd_sc_hd__nand3_1 _408_ (
    .A(RIS_REG[10]),
    .B(_090_),
    .C(_104_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__a21oi_1 _409_ (
    .A1(_111_),
    .A2(_167_),
    .B1(_108_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__a31oi_1 _410_ (
    .A1(RIS_REG[10]),
    .A2(IM_REG[10]),
    .A3(_108_),
    .B1(_168_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__o21ai_0 _411_ (
    .A1(IM_REG[10]),
    .A2(_107_),
    .B1(_101_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nor2_1 _412_ (
    .A(_169_),
    .B(_170_),
    .Y(PRDATA[10])
  );
  sky130_fd_sc_hd__nand3_1 _413_ (
    .A(RIS_REG[9]),
    .B(_090_),
    .C(_104_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__a21oi_1 _414_ (
    .A1(_111_),
    .A2(_171_),
    .B1(_108_),
    .Y(_172_)
  );
  sky130_fd_sc_hd__a311oi_1 _415_ (
    .A1(RIS_REG[9]),
    .A2(IM_REG[9]),
    .A3(_108_),
    .B1(_172_),
    .C1(_106_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__o21ai_0 _416_ (
    .A1(IM_REG[9]),
    .A2(_107_),
    .B1(_101_),
    .Y(_174_)
  );
  sky130_fd_sc_hd__nor2_1 _417_ (
    .A(_173_),
    .B(_174_),
    .Y(PRDATA[9])
  );
  sky130_fd_sc_hd__nand2_1 _418_ (
    .A(RIS_REG[8]),
    .B(_108_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nand2_1 _419_ (
    .A(_107_),
    .B(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__a22o_1 _420_ (
    .A1(RIS_REG[8]),
    .A2(_109_),
    .B1(_176_),
    .B2(IM_REG[8]),
    .X(PRDATA[8])
  );
  sky130_fd_sc_hd__nand2_1 _421_ (
    .A(bus_in[7]),
    .B(_100_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__nand3_1 _422_ (
    .A(RIS_REG[7]),
    .B(_090_),
    .C(_104_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _423_ (
    .A(RIS_REG[7]),
    .B(IM_REG[7]),
    .Y(_179_)
  );
  sky130_fd_sc_hd__a22oi_1 _424_ (
    .A1(_111_),
    .A2(_178_),
    .B1(_179_),
    .B2(_108_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__o21a_1 _425_ (
    .A1(IM_REG[7]),
    .A2(_107_),
    .B1(_093_),
    .X(_181_)
  );
  sky130_fd_sc_hd__a221oi_1 _426_ (
    .A1(DIR_REG[7]),
    .A2(_092_),
    .B1(_180_),
    .B2(_181_),
    .C1(_097_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__nor2_1 _427_ (
    .A(DATAO_REG[7]),
    .B(_098_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__o31ai_1 _428_ (
    .A1(_100_),
    .A2(_182_),
    .A3(_183_),
    .B1(_177_),
    .Y(PRDATA[7])
  );
  sky130_fd_sc_hd__nand2_1 _429_ (
    .A(bus_in[6]),
    .B(_100_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__nand3_1 _430_ (
    .A(RIS_REG[6]),
    .B(_090_),
    .C(_104_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__nand2_1 _431_ (
    .A(RIS_REG[6]),
    .B(IM_REG[6]),
    .Y(_186_)
  );
  sky130_fd_sc_hd__a22oi_1 _432_ (
    .A1(_111_),
    .A2(_185_),
    .B1(_186_),
    .B2(_108_),
    .Y(_187_)
  );
  sky130_fd_sc_hd__o21a_1 _433_ (
    .A1(IM_REG[6]),
    .A2(_107_),
    .B1(_093_),
    .X(_188_)
  );
  sky130_fd_sc_hd__a221oi_1 _434_ (
    .A1(DIR_REG[6]),
    .A2(_092_),
    .B1(_187_),
    .B2(_188_),
    .C1(_097_),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _435_ (
    .A(DATAO_REG[6]),
    .B(_098_),
    .Y(_190_)
  );
  sky130_fd_sc_hd__o31ai_1 _436_ (
    .A1(_100_),
    .A2(_189_),
    .A3(_190_),
    .B1(_184_),
    .Y(PRDATA[6])
  );
  sky130_fd_sc_hd__nand2_1 _437_ (
    .A(bus_in[5]),
    .B(_100_),
    .Y(_191_)
  );
  sky130_fd_sc_hd__nand3_1 _438_ (
    .A(RIS_REG[5]),
    .B(_090_),
    .C(_104_),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nand2_1 _439_ (
    .A(RIS_REG[5]),
    .B(IM_REG[5]),
    .Y(_193_)
  );
  sky130_fd_sc_hd__a22oi_1 _440_ (
    .A1(_111_),
    .A2(_192_),
    .B1(_193_),
    .B2(_108_),
    .Y(_194_)
  );
  sky130_fd_sc_hd__o21a_1 _441_ (
    .A1(IM_REG[5]),
    .A2(_107_),
    .B1(_093_),
    .X(_195_)
  );
  sky130_fd_sc_hd__a221oi_1 _442_ (
    .A1(DIR_REG[5]),
    .A2(_092_),
    .B1(_194_),
    .B2(_195_),
    .C1(_097_),
    .Y(_196_)
  );
  sky130_fd_sc_hd__nor2_1 _443_ (
    .A(DATAO_REG[5]),
    .B(_098_),
    .Y(_197_)
  );
  sky130_fd_sc_hd__o31ai_1 _444_ (
    .A1(_100_),
    .A2(_196_),
    .A3(_197_),
    .B1(_191_),
    .Y(PRDATA[5])
  );
  sky130_fd_sc_hd__a22oi_1 _445_ (
    .A1(DATAO_REG[4]),
    .A2(_097_),
    .B1(_109_),
    .B2(RIS_REG[4]),
    .Y(_198_)
  );
  sky130_fd_sc_hd__nand3_1 _446_ (
    .A(RIS_REG[4]),
    .B(IM_REG[4]),
    .C(_108_),
    .Y(_199_)
  );
  sky130_fd_sc_hd__nand2_1 _447_ (
    .A(IM_REG[4]),
    .B(_106_),
    .Y(_200_)
  );
  sky130_fd_sc_hd__a22oi_1 _448_ (
    .A1(DIR_REG[4]),
    .A2(_092_),
    .B1(_100_),
    .B2(bus_in[4]),
    .Y(_201_)
  );
  sky130_fd_sc_hd__nand4_1 _449_ (
    .A(_198_),
    .B(_199_),
    .C(_200_),
    .D(_201_),
    .Y(PRDATA[4])
  );
  sky130_fd_sc_hd__nand2_1 _450_ (
    .A(bus_in[3]),
    .B(_100_),
    .Y(_202_)
  );
  sky130_fd_sc_hd__nand3_1 _451_ (
    .A(RIS_REG[3]),
    .B(_090_),
    .C(_104_),
    .Y(_203_)
  );
  sky130_fd_sc_hd__nand2_1 _452_ (
    .A(RIS_REG[3]),
    .B(IM_REG[3]),
    .Y(_204_)
  );
  sky130_fd_sc_hd__a22oi_1 _453_ (
    .A1(_111_),
    .A2(_203_),
    .B1(_204_),
    .B2(_108_),
    .Y(_205_)
  );
  sky130_fd_sc_hd__o21a_1 _454_ (
    .A1(IM_REG[3]),
    .A2(_107_),
    .B1(_093_),
    .X(_206_)
  );
  sky130_fd_sc_hd__a221oi_1 _455_ (
    .A1(DIR_REG[3]),
    .A2(_092_),
    .B1(_205_),
    .B2(_206_),
    .C1(_097_),
    .Y(_207_)
  );
  sky130_fd_sc_hd__nor2_1 _456_ (
    .A(DATAO_REG[3]),
    .B(_098_),
    .Y(_208_)
  );
  sky130_fd_sc_hd__o31ai_1 _457_ (
    .A1(_100_),
    .A2(_207_),
    .A3(_208_),
    .B1(_202_),
    .Y(PRDATA[3])
  );
  sky130_fd_sc_hd__nand2_1 _458_ (
    .A(bus_in[2]),
    .B(_100_),
    .Y(_209_)
  );
  sky130_fd_sc_hd__nand3_1 _459_ (
    .A(RIS_REG[2]),
    .B(_090_),
    .C(_104_),
    .Y(_210_)
  );
  sky130_fd_sc_hd__nand2_1 _460_ (
    .A(RIS_REG[2]),
    .B(IM_REG[2]),
    .Y(_211_)
  );
  sky130_fd_sc_hd__a22oi_1 _461_ (
    .A1(_111_),
    .A2(_210_),
    .B1(_211_),
    .B2(_108_),
    .Y(_212_)
  );
  sky130_fd_sc_hd__o21a_1 _462_ (
    .A1(IM_REG[2]),
    .A2(_107_),
    .B1(_093_),
    .X(_213_)
  );
  sky130_fd_sc_hd__a221oi_1 _463_ (
    .A1(DIR_REG[2]),
    .A2(_092_),
    .B1(_212_),
    .B2(_213_),
    .C1(_097_),
    .Y(_214_)
  );
  sky130_fd_sc_hd__nor2_1 _464_ (
    .A(DATAO_REG[2]),
    .B(_098_),
    .Y(_215_)
  );
  sky130_fd_sc_hd__o31ai_1 _465_ (
    .A1(_100_),
    .A2(_214_),
    .A3(_215_),
    .B1(_209_),
    .Y(PRDATA[2])
  );
  sky130_fd_sc_hd__nand2_1 _466_ (
    .A(bus_in[1]),
    .B(_100_),
    .Y(_216_)
  );
  sky130_fd_sc_hd__nand3_1 _467_ (
    .A(RIS_REG[1]),
    .B(_090_),
    .C(_104_),
    .Y(_217_)
  );
  sky130_fd_sc_hd__nand2_1 _468_ (
    .A(RIS_REG[1]),
    .B(IM_REG[1]),
    .Y(_218_)
  );
  sky130_fd_sc_hd__a22oi_1 _469_ (
    .A1(_111_),
    .A2(_217_),
    .B1(_218_),
    .B2(_108_),
    .Y(_219_)
  );
  sky130_fd_sc_hd__o21a_1 _470_ (
    .A1(IM_REG[1]),
    .A2(_107_),
    .B1(_093_),
    .X(_220_)
  );
  sky130_fd_sc_hd__a221oi_1 _471_ (
    .A1(DIR_REG[1]),
    .A2(_092_),
    .B1(_219_),
    .B2(_220_),
    .C1(_097_),
    .Y(_221_)
  );
  sky130_fd_sc_hd__nor2_1 _472_ (
    .A(DATAO_REG[1]),
    .B(_098_),
    .Y(_222_)
  );
  sky130_fd_sc_hd__o31ai_1 _473_ (
    .A1(_100_),
    .A2(_221_),
    .A3(_222_),
    .B1(_216_),
    .Y(PRDATA[1])
  );
  sky130_fd_sc_hd__nand2_1 _474_ (
    .A(bus_in[0]),
    .B(_100_),
    .Y(_223_)
  );
  sky130_fd_sc_hd__o22ai_1 _475_ (
    .A1(DATAO_REG[0]),
    .A2(_098_),
    .B1(_099_),
    .B2(_084_),
    .Y(_224_)
  );
  sky130_fd_sc_hd__nor2_1 _476_ (
    .A(DIR_REG[0]),
    .B(_093_),
    .Y(_225_)
  );
  sky130_fd_sc_hd__nand2_1 _477_ (
    .A(RIS_REG[0]),
    .B(IM_REG[0]),
    .Y(_226_)
  );
  sky130_fd_sc_hd__a21oi_1 _478_ (
    .A1(_108_),
    .A2(_226_),
    .B1(_106_),
    .Y(_227_)
  );
  sky130_fd_sc_hd__a21oi_1 _479_ (
    .A1(_090_),
    .A2(_104_),
    .B1(GCLK_REG),
    .Y(_228_)
  );
  sky130_fd_sc_hd__nor3_1 _480_ (
    .A(RIS_REG[0]),
    .B(_091_),
    .C(_105_),
    .Y(_229_)
  );
  sky130_fd_sc_hd__o21ai_0 _481_ (
    .A1(_228_),
    .A2(_229_),
    .B1(_111_),
    .Y(_230_)
  );
  sky130_fd_sc_hd__a221oi_1 _482_ (
    .A1(IM_REG[0]),
    .A2(_106_),
    .B1(_227_),
    .B2(_230_),
    .C1(_092_),
    .Y(_231_)
  );
  sky130_fd_sc_hd__o31ai_1 _483_ (
    .A1(_224_),
    .A2(_225_),
    .A3(_231_),
    .B1(_223_),
    .Y(PRDATA[0])
  );
  sky130_fd_sc_hd__nand3_1 _484_ (
    .A(PWRITE),
    .B(PSEL),
    .C(PENABLE),
    .Y(_232_)
  );
  sky130_fd_sc_hd__or3_1 _485_ (
    .A(_102_),
    .B(_103_),
    .C(_232_),
    .X(_233_)
  );
  sky130_fd_sc_hd__nor3_1 _486_ (
    .A(_085_),
    .B(_095_),
    .C(_233_),
    .Y(_234_)
  );
  sky130_fd_sc_hd__and2_0 _487_ (
    .A(PWDATA[30]),
    .B(_234_),
    .X(_000_[30])
  );
  sky130_fd_sc_hd__and2_0 _488_ (
    .A(PWDATA[29]),
    .B(_234_),
    .X(_000_[29])
  );
  sky130_fd_sc_hd__and2_0 _489_ (
    .A(PWDATA[28]),
    .B(_234_),
    .X(_000_[28])
  );
  sky130_fd_sc_hd__and2_0 _490_ (
    .A(PWDATA[27]),
    .B(_234_),
    .X(_000_[27])
  );
  sky130_fd_sc_hd__and2_0 _491_ (
    .A(PWDATA[25]),
    .B(_234_),
    .X(_000_[25])
  );
  sky130_fd_sc_hd__and2_0 _492_ (
    .A(PWDATA[24]),
    .B(_234_),
    .X(_000_[24])
  );
  sky130_fd_sc_hd__and2_0 _493_ (
    .A(PWDATA[23]),
    .B(_234_),
    .X(_000_[23])
  );
  sky130_fd_sc_hd__and2_0 _494_ (
    .A(PWDATA[22]),
    .B(_234_),
    .X(_000_[22])
  );
  sky130_fd_sc_hd__and2_0 _495_ (
    .A(PWDATA[21]),
    .B(_234_),
    .X(_000_[21])
  );
  sky130_fd_sc_hd__and2_0 _496_ (
    .A(PWDATA[20]),
    .B(_234_),
    .X(_000_[20])
  );
  sky130_fd_sc_hd__and2_0 _497_ (
    .A(PWDATA[19]),
    .B(_234_),
    .X(_000_[19])
  );
  sky130_fd_sc_hd__and2_0 _498_ (
    .A(PWDATA[18]),
    .B(_234_),
    .X(_000_[18])
  );
  sky130_fd_sc_hd__and2_0 _499_ (
    .A(PWDATA[17]),
    .B(_234_),
    .X(_000_[17])
  );
  sky130_fd_sc_hd__and2_0 _500_ (
    .A(PWDATA[16]),
    .B(_234_),
    .X(_000_[16])
  );
  sky130_fd_sc_hd__and2_0 _501_ (
    .A(PWDATA[15]),
    .B(_234_),
    .X(_000_[15])
  );
  sky130_fd_sc_hd__and2_0 _502_ (
    .A(PWDATA[14]),
    .B(_234_),
    .X(_000_[14])
  );
  sky130_fd_sc_hd__and2_0 _503_ (
    .A(PWDATA[13]),
    .B(_234_),
    .X(_000_[13])
  );
  sky130_fd_sc_hd__and2_0 _504_ (
    .A(PWDATA[12]),
    .B(_234_),
    .X(_000_[12])
  );
  sky130_fd_sc_hd__and2_0 _505_ (
    .A(PWDATA[26]),
    .B(_234_),
    .X(_000_[26])
  );
  sky130_fd_sc_hd__and2_0 _506_ (
    .A(PWDATA[10]),
    .B(_234_),
    .X(_000_[10])
  );
  sky130_fd_sc_hd__and2_0 _507_ (
    .A(PWDATA[9]),
    .B(_234_),
    .X(_000_[9])
  );
  sky130_fd_sc_hd__and2_0 _508_ (
    .A(PWDATA[8]),
    .B(_234_),
    .X(_000_[8])
  );
  sky130_fd_sc_hd__and2_0 _509_ (
    .A(PWDATA[7]),
    .B(_234_),
    .X(_000_[7])
  );
  sky130_fd_sc_hd__and2_0 _510_ (
    .A(PWDATA[6]),
    .B(_234_),
    .X(_000_[6])
  );
  sky130_fd_sc_hd__and2_0 _511_ (
    .A(PWDATA[5]),
    .B(_234_),
    .X(_000_[5])
  );
  sky130_fd_sc_hd__and2_0 _512_ (
    .A(PWDATA[4]),
    .B(_234_),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__and2_0 _513_ (
    .A(PWDATA[3]),
    .B(_234_),
    .X(_000_[3])
  );
  sky130_fd_sc_hd__and2_0 _514_ (
    .A(PWDATA[2]),
    .B(_234_),
    .X(_000_[2])
  );
  sky130_fd_sc_hd__and2_0 _515_ (
    .A(PWDATA[1]),
    .B(_234_),
    .X(_000_[1])
  );
  sky130_fd_sc_hd__and2_0 _516_ (
    .A(PWDATA[0]),
    .B(_234_),
    .X(_000_[0])
  );
  sky130_fd_sc_hd__nand3_1 _517_ (
    .A(RIS_REG[30]),
    .B(_090_),
    .C(_104_),
    .Y(_235_)
  );
  sky130_fd_sc_hd__a21oi_1 _518_ (
    .A1(_111_),
    .A2(_235_),
    .B1(_108_),
    .Y(_236_)
  );
  sky130_fd_sc_hd__a31oi_1 _519_ (
    .A1(RIS_REG[30]),
    .A2(IM_REG[30]),
    .A3(_108_),
    .B1(_236_),
    .Y(_237_)
  );
  sky130_fd_sc_hd__o21ai_0 _520_ (
    .A1(IM_REG[30]),
    .A2(_107_),
    .B1(_101_),
    .Y(_238_)
  );
  sky130_fd_sc_hd__nor2_1 _521_ (
    .A(_237_),
    .B(_238_),
    .Y(PRDATA[30])
  );
  sky130_fd_sc_hd__nand2_1 _522_ (
    .A(RIS_REG[29]),
    .B(_108_),
    .Y(_239_)
  );
  sky130_fd_sc_hd__nand2_1 _523_ (
    .A(_107_),
    .B(_239_),
    .Y(_240_)
  );
  sky130_fd_sc_hd__a22o_1 _524_ (
    .A1(RIS_REG[29]),
    .A2(_109_),
    .B1(_240_),
    .B2(IM_REG[29]),
    .X(PRDATA[29])
  );
  sky130_fd_sc_hd__nand3_1 _525_ (
    .A(RIS_REG[28]),
    .B(_090_),
    .C(_104_),
    .Y(_241_)
  );
  sky130_fd_sc_hd__a21oi_1 _526_ (
    .A1(_111_),
    .A2(_241_),
    .B1(_108_),
    .Y(_242_)
  );
  sky130_fd_sc_hd__a31oi_1 _527_ (
    .A1(RIS_REG[28]),
    .A2(IM_REG[28]),
    .A3(_108_),
    .B1(_242_),
    .Y(_243_)
  );
  sky130_fd_sc_hd__o21ai_0 _528_ (
    .A1(IM_REG[28]),
    .A2(_107_),
    .B1(_101_),
    .Y(_244_)
  );
  sky130_fd_sc_hd__nor2_1 _529_ (
    .A(_243_),
    .B(_244_),
    .Y(PRDATA[28])
  );
  sky130_fd_sc_hd__and2_0 _530_ (
    .A(PWDATA[11]),
    .B(_234_),
    .X(_000_[11])
  );
  sky130_fd_sc_hd__or3_1 _531_ (
    .A(_099_),
    .B(_105_),
    .C(_232_),
    .X(_245_)
  );
  sky130_fd_sc_hd__mux2_1 _532_ (
    .A0(PWDATA[30]),
    .A1(IM_REG[30]),
    .S(_245_),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _533_ (
    .A0(PWDATA[29]),
    .A1(IM_REG[29]),
    .S(_245_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _534_ (
    .A0(PWDATA[28]),
    .A1(IM_REG[28]),
    .S(_245_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _535_ (
    .A0(PWDATA[27]),
    .A1(IM_REG[27]),
    .S(_245_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _536_ (
    .A0(PWDATA[26]),
    .A1(IM_REG[26]),
    .S(_245_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _537_ (
    .A0(PWDATA[25]),
    .A1(IM_REG[25]),
    .S(_245_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _538_ (
    .A0(PWDATA[24]),
    .A1(IM_REG[24]),
    .S(_245_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _539_ (
    .A0(PWDATA[23]),
    .A1(IM_REG[23]),
    .S(_245_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _540_ (
    .A0(PWDATA[22]),
    .A1(IM_REG[22]),
    .S(_245_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _541_ (
    .A0(PWDATA[21]),
    .A1(IM_REG[21]),
    .S(_245_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _542_ (
    .A0(PWDATA[20]),
    .A1(IM_REG[20]),
    .S(_245_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _543_ (
    .A0(PWDATA[19]),
    .A1(IM_REG[19]),
    .S(_245_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _544_ (
    .A0(PWDATA[18]),
    .A1(IM_REG[18]),
    .S(_245_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _545_ (
    .A0(PWDATA[17]),
    .A1(IM_REG[17]),
    .S(_245_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _546_ (
    .A0(PWDATA[16]),
    .A1(IM_REG[16]),
    .S(_245_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _547_ (
    .A0(PWDATA[15]),
    .A1(IM_REG[15]),
    .S(_245_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _548_ (
    .A0(PWDATA[14]),
    .A1(IM_REG[14]),
    .S(_245_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _549_ (
    .A0(PWDATA[13]),
    .A1(IM_REG[13]),
    .S(_245_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _550_ (
    .A0(PWDATA[12]),
    .A1(IM_REG[12]),
    .S(_245_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _551_ (
    .A0(PWDATA[11]),
    .A1(IM_REG[11]),
    .S(_245_),
    .X(_020_)
  );
  sky130_fd_sc_hd__mux2_1 _552_ (
    .A0(PWDATA[10]),
    .A1(IM_REG[10]),
    .S(_245_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _553_ (
    .A0(PWDATA[9]),
    .A1(IM_REG[9]),
    .S(_245_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _554_ (
    .A0(PWDATA[8]),
    .A1(IM_REG[8]),
    .S(_245_),
    .X(_023_)
  );
  sky130_fd_sc_hd__mux2_1 _555_ (
    .A0(PWDATA[7]),
    .A1(IM_REG[7]),
    .S(_245_),
    .X(_024_)
  );
  sky130_fd_sc_hd__mux2_1 _556_ (
    .A0(PWDATA[6]),
    .A1(IM_REG[6]),
    .S(_245_),
    .X(_025_)
  );
  sky130_fd_sc_hd__mux2_1 _557_ (
    .A0(PWDATA[5]),
    .A1(IM_REG[5]),
    .S(_245_),
    .X(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _558_ (
    .A0(PWDATA[4]),
    .A1(IM_REG[4]),
    .S(_245_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _559_ (
    .A0(PWDATA[3]),
    .A1(IM_REG[3]),
    .S(_245_),
    .X(_028_)
  );
  sky130_fd_sc_hd__mux2_1 _560_ (
    .A0(PWDATA[2]),
    .A1(IM_REG[2]),
    .S(_245_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _561_ (
    .A0(PWDATA[1]),
    .A1(IM_REG[1]),
    .S(_245_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _562_ (
    .A0(PWDATA[0]),
    .A1(IM_REG[0]),
    .S(_245_),
    .X(_031_)
  );
  sky130_fd_sc_hd__nor2_1 _563_ (
    .A(_093_),
    .B(_232_),
    .Y(_246_)
  );
  sky130_fd_sc_hd__mux2_1 _564_ (
    .A0(DIR_REG[6]),
    .A1(PWDATA[6]),
    .S(_246_),
    .X(_032_)
  );
  sky130_fd_sc_hd__mux2_1 _565_ (
    .A0(DIR_REG[5]),
    .A1(PWDATA[5]),
    .S(_246_),
    .X(_033_)
  );
  sky130_fd_sc_hd__mux2_1 _566_ (
    .A0(DIR_REG[4]),
    .A1(PWDATA[4]),
    .S(_246_),
    .X(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _567_ (
    .A0(DIR_REG[3]),
    .A1(PWDATA[3]),
    .S(_246_),
    .X(_035_)
  );
  sky130_fd_sc_hd__mux2_1 _568_ (
    .A0(DIR_REG[2]),
    .A1(PWDATA[2]),
    .S(_246_),
    .X(_036_)
  );
  sky130_fd_sc_hd__mux2_1 _569_ (
    .A0(DIR_REG[1]),
    .A1(PWDATA[1]),
    .S(_246_),
    .X(_037_)
  );
  sky130_fd_sc_hd__mux2_1 _570_ (
    .A0(DIR_REG[0]),
    .A1(PWDATA[0]),
    .S(_246_),
    .X(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _571_ (
    .A(_098_),
    .B(_232_),
    .Y(_247_)
  );
  sky130_fd_sc_hd__mux2_1 _572_ (
    .A0(DATAO_REG[6]),
    .A1(PWDATA[6]),
    .S(_247_),
    .X(_039_)
  );
  sky130_fd_sc_hd__mux2_1 _573_ (
    .A0(DATAO_REG[5]),
    .A1(PWDATA[5]),
    .S(_247_),
    .X(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _574_ (
    .A0(DATAO_REG[4]),
    .A1(PWDATA[4]),
    .S(_247_),
    .X(_041_)
  );
  sky130_fd_sc_hd__mux2_1 _575_ (
    .A0(DATAO_REG[3]),
    .A1(PWDATA[3]),
    .S(_247_),
    .X(_042_)
  );
  sky130_fd_sc_hd__mux2_1 _576_ (
    .A0(DATAO_REG[2]),
    .A1(PWDATA[2]),
    .S(_247_),
    .X(_043_)
  );
  sky130_fd_sc_hd__mux2_1 _577_ (
    .A0(DATAO_REG[1]),
    .A1(PWDATA[1]),
    .S(_247_),
    .X(_044_)
  );
  sky130_fd_sc_hd__mux2_1 _578_ (
    .A0(DATAO_REG[0]),
    .A1(PWDATA[0]),
    .S(_247_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor2_1 _579_ (
    .A(RIS_REG[24]),
    .B(pin0_ne),
    .Y(_248_)
  );
  sky130_fd_sc_hd__nor2_1 _580_ (
    .A(IC_REG[24]),
    .B(_248_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nor2_1 _581_ (
    .A(RIS_REG[23]),
    .B(pin7_pe),
    .Y(_249_)
  );
  sky130_fd_sc_hd__nor2_1 _582_ (
    .A(IC_REG[23]),
    .B(_249_),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _583_ (
    .A(RIS_REG[22]),
    .B(pin6_pe),
    .Y(_250_)
  );
  sky130_fd_sc_hd__nor2_1 _584_ (
    .A(IC_REG[22]),
    .B(_250_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nor2_1 _585_ (
    .A(RIS_REG[21]),
    .B(pin5_pe),
    .Y(_251_)
  );
  sky130_fd_sc_hd__nor2_1 _586_ (
    .A(IC_REG[21]),
    .B(_251_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _587_ (
    .A(RIS_REG[20]),
    .B(pin4_pe),
    .Y(_252_)
  );
  sky130_fd_sc_hd__nor2_1 _588_ (
    .A(IC_REG[20]),
    .B(_252_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor2_1 _589_ (
    .A(RIS_REG[19]),
    .B(pin3_pe),
    .Y(_253_)
  );
  sky130_fd_sc_hd__nor2_1 _590_ (
    .A(IC_REG[19]),
    .B(_253_),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor2_1 _591_ (
    .A(RIS_REG[18]),
    .B(pin2_pe),
    .Y(_254_)
  );
  sky130_fd_sc_hd__nor2_1 _592_ (
    .A(IC_REG[18]),
    .B(_254_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nor2_1 _593_ (
    .A(RIS_REG[17]),
    .B(pin1_pe),
    .Y(_255_)
  );
  sky130_fd_sc_hd__nor2_1 _594_ (
    .A(IC_REG[17]),
    .B(_255_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _595_ (
    .A(RIS_REG[16]),
    .B(pin0_pe),
    .Y(_256_)
  );
  sky130_fd_sc_hd__nor2_1 _596_ (
    .A(IC_REG[16]),
    .B(_256_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nor2_1 _597_ (
    .A(RIS_REG[15]),
    .B(pin7_lo),
    .Y(_257_)
  );
  sky130_fd_sc_hd__nor2_1 _598_ (
    .A(IC_REG[15]),
    .B(_257_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor2_1 _599_ (
    .A(RIS_REG[14]),
    .B(pin6_lo),
    .Y(_258_)
  );
  sky130_fd_sc_hd__nor2_1 _600_ (
    .A(IC_REG[14]),
    .B(_258_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__nor2_1 _601_ (
    .A(RIS_REG[13]),
    .B(pin5_lo),
    .Y(_259_)
  );
  sky130_fd_sc_hd__nor2_1 _602_ (
    .A(IC_REG[13]),
    .B(_259_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__nor2_1 _603_ (
    .A(RIS_REG[12]),
    .B(pin4_lo),
    .Y(_260_)
  );
  sky130_fd_sc_hd__nor2_1 _604_ (
    .A(IC_REG[12]),
    .B(_260_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor2_1 _605_ (
    .A(RIS_REG[11]),
    .B(pin3_lo),
    .Y(_261_)
  );
  sky130_fd_sc_hd__nor2_1 _606_ (
    .A(IC_REG[11]),
    .B(_261_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__nor2_1 _607_ (
    .A(RIS_REG[10]),
    .B(pin2_lo),
    .Y(_262_)
  );
  sky130_fd_sc_hd__nor2_1 _608_ (
    .A(IC_REG[10]),
    .B(_262_),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _609_ (
    .A(RIS_REG[9]),
    .B(pin1_lo),
    .Y(_263_)
  );
  sky130_fd_sc_hd__nor2_1 _610_ (
    .A(IC_REG[9]),
    .B(_263_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor2_1 _611_ (
    .A(RIS_REG[8]),
    .B(pin0_lo),
    .Y(_264_)
  );
  sky130_fd_sc_hd__nor2_1 _612_ (
    .A(IC_REG[8]),
    .B(_264_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nor2_1 _613_ (
    .A(RIS_REG[7]),
    .B(pin7_hi),
    .Y(_265_)
  );
  sky130_fd_sc_hd__nor2_1 _614_ (
    .A(IC_REG[7]),
    .B(_265_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__nor2_1 _615_ (
    .A(RIS_REG[6]),
    .B(pin6_hi),
    .Y(_266_)
  );
  sky130_fd_sc_hd__nor2_1 _616_ (
    .A(IC_REG[6]),
    .B(_266_),
    .Y(_064_)
  );
  sky130_fd_sc_hd__nor2_1 _617_ (
    .A(RIS_REG[5]),
    .B(pin5_hi),
    .Y(_267_)
  );
  sky130_fd_sc_hd__nor2_1 _618_ (
    .A(IC_REG[5]),
    .B(_267_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nor2_1 _619_ (
    .A(RIS_REG[4]),
    .B(pin4_hi),
    .Y(_268_)
  );
  sky130_fd_sc_hd__nor2_1 _620_ (
    .A(IC_REG[4]),
    .B(_268_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor2_1 _621_ (
    .A(RIS_REG[3]),
    .B(pin3_hi),
    .Y(_269_)
  );
  sky130_fd_sc_hd__nor2_1 _622_ (
    .A(IC_REG[3]),
    .B(_269_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor2_1 _623_ (
    .A(RIS_REG[2]),
    .B(pin2_hi),
    .Y(_270_)
  );
  sky130_fd_sc_hd__nor2_1 _624_ (
    .A(IC_REG[2]),
    .B(_270_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _625_ (
    .A(RIS_REG[1]),
    .B(pin1_hi),
    .Y(_271_)
  );
  sky130_fd_sc_hd__nor2_1 _626_ (
    .A(IC_REG[1]),
    .B(_271_),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nor2_1 _627_ (
    .A(RIS_REG[0]),
    .B(pin0_hi),
    .Y(_272_)
  );
  sky130_fd_sc_hd__nor2_1 _628_ (
    .A(IC_REG[0]),
    .B(_272_),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nand3_1 _629_ (
    .A(RIS_REG[31]),
    .B(_090_),
    .C(_104_),
    .Y(_273_)
  );
  sky130_fd_sc_hd__a21oi_1 _630_ (
    .A1(_111_),
    .A2(_273_),
    .B1(_108_),
    .Y(_274_)
  );
  sky130_fd_sc_hd__a31oi_1 _631_ (
    .A1(IM_REG[31]),
    .A2(RIS_REG[31]),
    .A3(_108_),
    .B1(_274_),
    .Y(_275_)
  );
  sky130_fd_sc_hd__o21ai_0 _632_ (
    .A1(IM_REG[31]),
    .A2(_107_),
    .B1(_101_),
    .Y(_276_)
  );
  sky130_fd_sc_hd__nor2_1 _633_ (
    .A(_275_),
    .B(_276_),
    .Y(PRDATA[31])
  );
  sky130_fd_sc_hd__nor2_1 _634_ (
    .A(RIS_REG[30]),
    .B(pin6_ne),
    .Y(_277_)
  );
  sky130_fd_sc_hd__nor2_1 _635_ (
    .A(IC_REG[30]),
    .B(_277_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nor2_1 _636_ (
    .A(RIS_REG[29]),
    .B(pin5_ne),
    .Y(_278_)
  );
  sky130_fd_sc_hd__nor2_1 _637_ (
    .A(IC_REG[29]),
    .B(_278_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nand3_1 _638_ (
    .A(RIS_REG[27]),
    .B(_090_),
    .C(_104_),
    .Y(_279_)
  );
  sky130_fd_sc_hd__a21oi_1 _639_ (
    .A1(_111_),
    .A2(_279_),
    .B1(_108_),
    .Y(_280_)
  );
  sky130_fd_sc_hd__a31oi_1 _640_ (
    .A1(RIS_REG[27]),
    .A2(IM_REG[27]),
    .A3(_108_),
    .B1(_280_),
    .Y(_281_)
  );
  sky130_fd_sc_hd__o21ai_0 _641_ (
    .A1(IM_REG[27]),
    .A2(_107_),
    .B1(_101_),
    .Y(_282_)
  );
  sky130_fd_sc_hd__nor2_1 _642_ (
    .A(_281_),
    .B(_282_),
    .Y(PRDATA[27])
  );
  sky130_fd_sc_hd__a22oi_1 _643_ (
    .A1(RIS_REG[28]),
    .A2(IM_REG[28]),
    .B1(IM_REG[31]),
    .B2(RIS_REG[31]),
    .Y(_283_)
  );
  sky130_fd_sc_hd__a22oi_1 _644_ (
    .A1(RIS_REG[17]),
    .A2(IM_REG[17]),
    .B1(IM_REG[14]),
    .B2(RIS_REG[14]),
    .Y(_284_)
  );
  sky130_fd_sc_hd__a22oi_1 _645_ (
    .A1(RIS_REG[13]),
    .A2(IM_REG[13]),
    .B1(IM_REG[12]),
    .B2(RIS_REG[12]),
    .Y(_285_)
  );
  sky130_fd_sc_hd__a22oi_1 _646_ (
    .A1(RIS_REG[8]),
    .A2(IM_REG[8]),
    .B1(IM_REG[6]),
    .B2(RIS_REG[6]),
    .Y(_286_)
  );
  sky130_fd_sc_hd__a22oi_1 _647_ (
    .A1(RIS_REG[23]),
    .A2(IM_REG[23]),
    .B1(IM_REG[16]),
    .B2(RIS_REG[16]),
    .Y(_287_)
  );
  sky130_fd_sc_hd__nand2_1 _648_ (
    .A(_284_),
    .B(_287_),
    .Y(_288_)
  );
  sky130_fd_sc_hd__a221oi_1 _649_ (
    .A1(RIS_REG[20]),
    .A2(IM_REG[20]),
    .B1(IM_REG[11]),
    .B2(RIS_REG[11]),
    .C1(_288_),
    .Y(_289_)
  );
  sky130_fd_sc_hd__a22oi_1 _650_ (
    .A1(RIS_REG[22]),
    .A2(IM_REG[22]),
    .B1(IM_REG[15]),
    .B2(RIS_REG[15]),
    .Y(_290_)
  );
  sky130_fd_sc_hd__nand4_1 _651_ (
    .A(_136_),
    .B(_226_),
    .C(_285_),
    .D(_290_),
    .Y(_291_)
  );
  sky130_fd_sc_hd__a22oi_1 _652_ (
    .A1(RIS_REG[18]),
    .A2(IM_REG[18]),
    .B1(IM_REG[24]),
    .B2(RIS_REG[24]),
    .Y(_292_)
  );
  sky130_fd_sc_hd__a22oi_1 _653_ (
    .A1(RIS_REG[21]),
    .A2(IM_REG[21]),
    .B1(IM_REG[26]),
    .B2(RIS_REG[26]),
    .Y(_293_)
  );
  sky130_fd_sc_hd__a22oi_1 _654_ (
    .A1(RIS_REG[29]),
    .A2(IM_REG[29]),
    .B1(IM_REG[25]),
    .B2(RIS_REG[25]),
    .Y(_294_)
  );
  sky130_fd_sc_hd__nand4_1 _655_ (
    .A(_283_),
    .B(_292_),
    .C(_293_),
    .D(_294_),
    .Y(_295_)
  );
  sky130_fd_sc_hd__a222oi_1 _656_ (
    .A1(RIS_REG[9]),
    .A2(IM_REG[9]),
    .B1(IM_REG[2]),
    .B2(RIS_REG[2]),
    .C1(IM_REG[30]),
    .C2(RIS_REG[30]),
    .Y(_296_)
  );
  sky130_fd_sc_hd__a22oi_1 _657_ (
    .A1(RIS_REG[1]),
    .A2(IM_REG[1]),
    .B1(IM_REG[27]),
    .B2(RIS_REG[27]),
    .Y(_297_)
  );
  sky130_fd_sc_hd__a222oi_1 _658_ (
    .A1(RIS_REG[10]),
    .A2(IM_REG[10]),
    .B1(IM_REG[5]),
    .B2(RIS_REG[5]),
    .C1(IM_REG[4]),
    .C2(RIS_REG[4]),
    .Y(_298_)
  );
  sky130_fd_sc_hd__nand4_1 _659_ (
    .A(_179_),
    .B(_296_),
    .C(_297_),
    .D(_298_),
    .Y(_299_)
  );
  sky130_fd_sc_hd__nor3_1 _660_ (
    .A(_291_),
    .B(_295_),
    .C(_299_),
    .Y(_300_)
  );
  sky130_fd_sc_hd__nand4_1 _661_ (
    .A(_204_),
    .B(_286_),
    .C(_289_),
    .D(_300_),
    .Y(IRQ)
  );
  sky130_fd_sc_hd__and2_0 _662_ (
    .A(PWDATA[31]),
    .B(_234_),
    .X(_000_[31])
  );
  sky130_fd_sc_hd__nor2_1 _663_ (
    .A(RIS_REG[26]),
    .B(pin2_ne),
    .Y(_301_)
  );
  sky130_fd_sc_hd__nor2_1 _664_ (
    .A(IC_REG[26]),
    .B(_301_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__nor2_1 _665_ (
    .A(RIS_REG[25]),
    .B(pin1_ne),
    .Y(_302_)
  );
  sky130_fd_sc_hd__nor2_1 _666_ (
    .A(IC_REG[25]),
    .B(_302_),
    .Y(_074_)
  );
  sky130_fd_sc_hd__nor2_1 _667_ (
    .A(_110_),
    .B(_233_),
    .Y(_303_)
  );
  sky130_fd_sc_hd__mux2_1 _668_ (
    .A0(GCLK_REG),
    .A1(PWDATA[0]),
    .S(_303_),
    .X(_075_)
  );
  sky130_fd_sc_hd__nor2_1 _669_ (
    .A(pin7_ne),
    .B(RIS_REG[31]),
    .Y(_304_)
  );
  sky130_fd_sc_hd__nor2_1 _670_ (
    .A(IC_REG[31]),
    .B(_304_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _671_ (
    .A(RIS_REG[28]),
    .B(pin4_ne),
    .Y(_305_)
  );
  sky130_fd_sc_hd__nor2_1 _672_ (
    .A(IC_REG[28]),
    .B(_305_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__mux2_1 _673_ (
    .A0(DATAO_REG[7]),
    .A1(PWDATA[7]),
    .S(_247_),
    .X(_078_)
  );
  sky130_fd_sc_hd__mux2_1 _674_ (
    .A0(DIR_REG[7]),
    .A1(PWDATA[7]),
    .S(_246_),
    .X(_079_)
  );
  sky130_fd_sc_hd__mux2_1 _675_ (
    .A0(PWDATA[31]),
    .A1(IM_REG[31]),
    .S(_245_),
    .X(_080_)
  );
  sky130_fd_sc_hd__nor2_1 _676_ (
    .A(RIS_REG[27]),
    .B(pin3_ne),
    .Y(_306_)
  );
  sky130_fd_sc_hd__nor2_1 _677_ (
    .A(IC_REG[27]),
    .B(_306_),
    .Y(_081_)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _678_ (
    .CLK(PCLK),
    .D(_000_[0]),
    .Q(IC_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _679_ (
    .CLK(PCLK),
    .D(_000_[1]),
    .Q(IC_REG[1]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _680_ (
    .CLK(PCLK),
    .D(_000_[2]),
    .Q(IC_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _681_ (
    .CLK(PCLK),
    .D(_000_[3]),
    .Q(IC_REG[3]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _682_ (
    .CLK(PCLK),
    .D(_000_[4]),
    .Q(IC_REG[4]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _683_ (
    .CLK(PCLK),
    .D(_000_[5]),
    .Q(IC_REG[5]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _684_ (
    .CLK(PCLK),
    .D(_000_[6]),
    .Q(IC_REG[6]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _685_ (
    .CLK(PCLK),
    .D(_000_[7]),
    .Q(IC_REG[7]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _686_ (
    .CLK(PCLK),
    .D(_000_[8]),
    .Q(IC_REG[8]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _687_ (
    .CLK(PCLK),
    .D(_000_[9]),
    .Q(IC_REG[9]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _688_ (
    .CLK(PCLK),
    .D(_000_[10]),
    .Q(IC_REG[10]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _689_ (
    .CLK(PCLK),
    .D(_000_[11]),
    .Q(IC_REG[11]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _690_ (
    .CLK(PCLK),
    .D(_000_[12]),
    .Q(IC_REG[12]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _691_ (
    .CLK(PCLK),
    .D(_000_[13]),
    .Q(IC_REG[13]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _692_ (
    .CLK(PCLK),
    .D(_000_[14]),
    .Q(IC_REG[14]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _693_ (
    .CLK(PCLK),
    .D(_000_[15]),
    .Q(IC_REG[15]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _694_ (
    .CLK(PCLK),
    .D(_000_[16]),
    .Q(IC_REG[16]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _695_ (
    .CLK(PCLK),
    .D(_000_[17]),
    .Q(IC_REG[17]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _696_ (
    .CLK(PCLK),
    .D(_000_[18]),
    .Q(IC_REG[18]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _697_ (
    .CLK(PCLK),
    .D(_000_[19]),
    .Q(IC_REG[19]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _698_ (
    .CLK(PCLK),
    .D(_000_[20]),
    .Q(IC_REG[20]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _699_ (
    .CLK(PCLK),
    .D(_000_[21]),
    .Q(IC_REG[21]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _700_ (
    .CLK(PCLK),
    .D(_000_[22]),
    .Q(IC_REG[22]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _701_ (
    .CLK(PCLK),
    .D(_000_[23]),
    .Q(IC_REG[23]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _702_ (
    .CLK(PCLK),
    .D(_000_[24]),
    .Q(IC_REG[24]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _703_ (
    .CLK(PCLK),
    .D(_000_[25]),
    .Q(IC_REG[25]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _704_ (
    .CLK(PCLK),
    .D(_000_[26]),
    .Q(IC_REG[26]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _705_ (
    .CLK(PCLK),
    .D(_000_[27]),
    .Q(IC_REG[27]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _706_ (
    .CLK(PCLK),
    .D(_000_[28]),
    .Q(IC_REG[28]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _707_ (
    .CLK(PCLK),
    .D(_000_[29]),
    .Q(IC_REG[29]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _708_ (
    .CLK(PCLK),
    .D(_000_[30]),
    .Q(IC_REG[30]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:134.3-137.26" *)
  sky130_fd_sc_hd__dfrtp_1 _709_ (
    .CLK(PCLK),
    .D(_000_[31]),
    .Q(IC_REG[31]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:122.3-124.85" *)
  sky130_fd_sc_hd__dfrtp_1 _710_ (
    .CLK(PCLK),
    .D(_075_),
    .Q(GCLK_REG),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _711_ (
    .CLK(PCLK),
    .D(_076_),
    .Q(RIS_REG[31]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _712_ (
    .CLK(PCLK),
    .D(_071_),
    .Q(RIS_REG[30]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _713_ (
    .CLK(PCLK),
    .D(_072_),
    .Q(RIS_REG[29]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _714_ (
    .CLK(PCLK),
    .D(_077_),
    .Q(RIS_REG[28]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _715_ (
    .CLK(PCLK),
    .D(_081_),
    .Q(RIS_REG[27]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _716_ (
    .CLK(PCLK),
    .D(_073_),
    .Q(RIS_REG[26]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _717_ (
    .CLK(PCLK),
    .D(_074_),
    .Q(RIS_REG[25]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _718_ (
    .CLK(PCLK),
    .D(_046_),
    .Q(RIS_REG[24]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _719_ (
    .CLK(PCLK),
    .D(_047_),
    .Q(RIS_REG[23]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _720_ (
    .CLK(PCLK),
    .D(_048_),
    .Q(RIS_REG[22]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _721_ (
    .CLK(PCLK),
    .D(_049_),
    .Q(RIS_REG[21]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _722_ (
    .CLK(PCLK),
    .D(_050_),
    .Q(RIS_REG[20]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _723_ (
    .CLK(PCLK),
    .D(_051_),
    .Q(RIS_REG[19]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _724_ (
    .CLK(PCLK),
    .D(_052_),
    .Q(RIS_REG[18]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _725_ (
    .CLK(PCLK),
    .D(_053_),
    .Q(RIS_REG[17]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _726_ (
    .CLK(PCLK),
    .D(_054_),
    .Q(RIS_REG[16]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _727_ (
    .CLK(PCLK),
    .D(_055_),
    .Q(RIS_REG[15]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _728_ (
    .CLK(PCLK),
    .D(_056_),
    .Q(RIS_REG[14]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _729_ (
    .CLK(PCLK),
    .D(_057_),
    .Q(RIS_REG[13]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _730_ (
    .CLK(PCLK),
    .D(_058_),
    .Q(RIS_REG[12]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _731_ (
    .CLK(PCLK),
    .D(_059_),
    .Q(RIS_REG[11]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _732_ (
    .CLK(PCLK),
    .D(_060_),
    .Q(RIS_REG[10]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _733_ (
    .CLK(PCLK),
    .D(_061_),
    .Q(RIS_REG[9]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _734_ (
    .CLK(PCLK),
    .D(_062_),
    .Q(RIS_REG[8]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _735_ (
    .CLK(PCLK),
    .D(_063_),
    .Q(RIS_REG[7]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _736_ (
    .CLK(PCLK),
    .D(_064_),
    .Q(RIS_REG[6]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _737_ (
    .CLK(PCLK),
    .D(_065_),
    .Q(RIS_REG[5]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _738_ (
    .CLK(PCLK),
    .D(_066_),
    .Q(RIS_REG[4]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _739_ (
    .CLK(PCLK),
    .D(_067_),
    .Q(RIS_REG[3]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _740_ (
    .CLK(PCLK),
    .D(_068_),
    .Q(RIS_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _741_ (
    .CLK(PCLK),
    .D(_069_),
    .Q(RIS_REG[1]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:173.3-304.8" *)
  sky130_fd_sc_hd__dfrtp_1 _742_ (
    .CLK(PCLK),
    .D(_070_),
    .Q(RIS_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:111.3-113.87" *)
  sky130_fd_sc_hd__dfrtp_1 _743_ (
    .CLK(PCLK),
    .D(_045_),
    .Q(DATAO_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:111.3-113.87" *)
  sky130_fd_sc_hd__dfrtp_1 _744_ (
    .CLK(PCLK),
    .D(_044_),
    .Q(DATAO_REG[1]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:111.3-113.87" *)
  sky130_fd_sc_hd__dfrtp_1 _745_ (
    .CLK(PCLK),
    .D(_043_),
    .Q(DATAO_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:111.3-113.87" *)
  sky130_fd_sc_hd__dfrtp_1 _746_ (
    .CLK(PCLK),
    .D(_042_),
    .Q(DATAO_REG[3]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:111.3-113.87" *)
  sky130_fd_sc_hd__dfrtp_1 _747_ (
    .CLK(PCLK),
    .D(_041_),
    .Q(DATAO_REG[4]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:111.3-113.87" *)
  sky130_fd_sc_hd__dfrtp_1 _748_ (
    .CLK(PCLK),
    .D(_040_),
    .Q(DATAO_REG[5]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:111.3-113.87" *)
  sky130_fd_sc_hd__dfrtp_1 _749_ (
    .CLK(PCLK),
    .D(_039_),
    .Q(DATAO_REG[6]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:111.3-113.87" *)
  sky130_fd_sc_hd__dfrtp_1 _750_ (
    .CLK(PCLK),
    .D(_078_),
    .Q(DATAO_REG[7]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:117.3-119.83" *)
  sky130_fd_sc_hd__dfrtp_1 _751_ (
    .CLK(PCLK),
    .D(_038_),
    .Q(DIR_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:117.3-119.83" *)
  sky130_fd_sc_hd__dfrtp_1 _752_ (
    .CLK(PCLK),
    .D(_037_),
    .Q(DIR_REG[1]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:117.3-119.83" *)
  sky130_fd_sc_hd__dfrtp_1 _753_ (
    .CLK(PCLK),
    .D(_036_),
    .Q(DIR_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:117.3-119.83" *)
  sky130_fd_sc_hd__dfrtp_1 _754_ (
    .CLK(PCLK),
    .D(_035_),
    .Q(DIR_REG[3]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:117.3-119.83" *)
  sky130_fd_sc_hd__dfrtp_1 _755_ (
    .CLK(PCLK),
    .D(_034_),
    .Q(DIR_REG[4]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:117.3-119.83" *)
  sky130_fd_sc_hd__dfrtp_1 _756_ (
    .CLK(PCLK),
    .D(_033_),
    .Q(DIR_REG[5]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:117.3-119.83" *)
  sky130_fd_sc_hd__dfrtp_1 _757_ (
    .CLK(PCLK),
    .D(_032_),
    .Q(DIR_REG[6]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:117.3-119.83" *)
  sky130_fd_sc_hd__dfrtp_1 _758_ (
    .CLK(PCLK),
    .D(_079_),
    .Q(DIR_REG[7]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _759_ (
    .CLK(PCLK),
    .D(_031_),
    .Q(IM_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _760_ (
    .CLK(PCLK),
    .D(_030_),
    .Q(IM_REG[1]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _761_ (
    .CLK(PCLK),
    .D(_029_),
    .Q(IM_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _762_ (
    .CLK(PCLK),
    .D(_028_),
    .Q(IM_REG[3]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _763_ (
    .CLK(PCLK),
    .D(_027_),
    .Q(IM_REG[4]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _764_ (
    .CLK(PCLK),
    .D(_026_),
    .Q(IM_REG[5]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _765_ (
    .CLK(PCLK),
    .D(_025_),
    .Q(IM_REG[6]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _766_ (
    .CLK(PCLK),
    .D(_024_),
    .Q(IM_REG[7]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _767_ (
    .CLK(PCLK),
    .D(_023_),
    .Q(IM_REG[8]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _768_ (
    .CLK(PCLK),
    .D(_022_),
    .Q(IM_REG[9]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _769_ (
    .CLK(PCLK),
    .D(_021_),
    .Q(IM_REG[10]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _770_ (
    .CLK(PCLK),
    .D(_020_),
    .Q(IM_REG[11]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _771_ (
    .CLK(PCLK),
    .D(_019_),
    .Q(IM_REG[12]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _772_ (
    .CLK(PCLK),
    .D(_018_),
    .Q(IM_REG[13]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _773_ (
    .CLK(PCLK),
    .D(_017_),
    .Q(IM_REG[14]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _774_ (
    .CLK(PCLK),
    .D(_016_),
    .Q(IM_REG[15]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _775_ (
    .CLK(PCLK),
    .D(_015_),
    .Q(IM_REG[16]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _776_ (
    .CLK(PCLK),
    .D(_014_),
    .Q(IM_REG[17]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _777_ (
    .CLK(PCLK),
    .D(_013_),
    .Q(IM_REG[18]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _778_ (
    .CLK(PCLK),
    .D(_012_),
    .Q(IM_REG[19]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _779_ (
    .CLK(PCLK),
    .D(_011_),
    .Q(IM_REG[20]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _780_ (
    .CLK(PCLK),
    .D(_010_),
    .Q(IM_REG[21]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _781_ (
    .CLK(PCLK),
    .D(_009_),
    .Q(IM_REG[22]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _782_ (
    .CLK(PCLK),
    .D(_008_),
    .Q(IM_REG[23]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _783_ (
    .CLK(PCLK),
    .D(_007_),
    .Q(IM_REG[24]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _784_ (
    .CLK(PCLK),
    .D(_006_),
    .Q(IM_REG[25]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _785_ (
    .CLK(PCLK),
    .D(_005_),
    .Q(IM_REG[26]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _786_ (
    .CLK(PCLK),
    .D(_004_),
    .Q(IM_REG[27]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _787_ (
    .CLK(PCLK),
    .D(_003_),
    .Q(IM_REG[28]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _788_ (
    .CLK(PCLK),
    .D(_002_),
    .Q(IM_REG[29]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _789_ (
    .CLK(PCLK),
    .D(_001_),
    .Q(IM_REG[30]),
    .RESET_B(PRESETn)
  );
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:131.3-133.82" *)
  sky130_fd_sc_hd__dfrtp_1 _790_ (
    .CLK(PCLK),
    .D(_080_),
    .Q(IM_REG[31]),
    .RESET_B(PRESETn)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:54.23-60.4" *)
  ef_util_gating_cell clk_gate_cell (
    .clk(PCLK),
    .clk_en(GCLK_REG),
    .clk_o(clk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "rtl-gpio/rtl/EF_GPIO8_APB.v:308.12-349.4" *)
  EF_GPIO8 instance_to_wrap (
    .bus_in(bus_in),
    .bus_oe(DIR_REG),
    .bus_out(DATAO_REG),
    .clk(clk),
    .io_in(io_in),
    .io_oe(io_oe),
    .io_out(io_out),
    .pin0_hi(pin0_hi),
    .pin0_lo(pin0_lo),
    .pin0_ne(pin0_ne),
    .pin0_pe(pin0_pe),
    .pin1_hi(pin1_hi),
    .pin1_lo(pin1_lo),
    .pin1_ne(pin1_ne),
    .pin1_pe(pin1_pe),
    .pin2_hi(pin2_hi),
    .pin2_lo(pin2_lo),
    .pin2_ne(pin2_ne),
    .pin2_pe(pin2_pe),
    .pin3_hi(pin3_hi),
    .pin3_lo(pin3_lo),
    .pin3_ne(pin3_ne),
    .pin3_pe(pin3_pe),
    .pin4_hi(pin4_hi),
    .pin4_lo(pin4_lo),
    .pin4_ne(pin4_ne),
    .pin4_pe(pin4_pe),
    .pin5_hi(pin5_hi),
    .pin5_lo(pin5_lo),
    .pin5_ne(pin5_ne),
    .pin5_pe(pin5_pe),
    .pin6_hi(pin6_hi),
    .pin6_lo(pin6_lo),
    .pin6_ne(pin6_ne),
    .pin6_pe(pin6_pe),
    .pin7_hi(pin7_hi),
    .pin7_lo(pin7_lo),
    .pin7_ne(pin7_ne),
    .pin7_pe(pin7_pe),
    .rst_n(PRESETn)
  );
  assign P7NE = pin7_ne;
  assign P6NE = pin6_ne;
  assign P5NE = pin5_ne;
  assign P4NE = pin4_ne;
  assign P3NE = pin3_ne;
  assign P2NE = pin2_ne;
  assign P1NE = pin1_ne;
  assign P0NE = pin0_ne;
  assign P7PE = pin7_pe;
  assign P6PE = pin6_pe;
  assign P5PE = pin5_pe;
  assign P4PE = pin4_pe;
  assign P3PE = pin3_pe;
  assign P2PE = pin2_pe;
  assign P1PE = pin1_pe;
  assign P0PE = pin0_pe;
  assign P7LO = pin7_lo;
  assign P6LO = pin6_lo;
  assign P5LO = pin5_lo;
  assign P4LO = pin4_lo;
  assign P3LO = pin3_lo;
  assign P2LO = pin2_lo;
  assign P1LO = pin1_lo;
  assign P0LO = pin0_lo;
  assign P7HI = pin7_hi;
  assign P6HI = pin6_hi;
  assign P5HI = pin5_hi;
  assign P4HI = pin4_hi;
  assign P3HI = pin3_hi;
  assign P2HI = pin2_hi;
  assign P1HI = pin1_hi;
  assign P0HI = pin0_hi;
  assign DATAI_WIRE = bus_in;
  assign bus_oe = DIR_REG;
  assign bus_out = DATAO_REG;
  assign rst_n = PRESETn;
  assign clk_gated_en = GCLK_REG;
  assign clk_g = clk;
  assign PREADY = 1'h1;
endmodule

(* src = "common/ef_util_lib.v:366.1-393.10" *)
module ef_util_gating_cell(clk, rst_n, clk_en, clk_o);
  (* src = "common/ef_util_lib.v:371.21-371.24" *)
  input clk;
  wire clk;
  (* src = "common/ef_util_lib.v:372.21-372.26" *)
  input rst_n;
  wire rst_n;
  (* src = "common/ef_util_lib.v:373.21-373.27" *)
  input clk_en;
  wire clk_en;
  (* src = "common/ef_util_lib.v:374.21-374.26" *)
  output clk_o;
  wire clk_o;
  assign clk_o = clk;
endmodule

(* src = "common/ef_util_lib.v:62.1-71.10" *)
module ef_util_ned(clk, in, out);
  (* src = "common/ef_util_lib.v:63.16-63.19" *)
  input clk;
  wire clk;
  (* src = "common/ef_util_lib.v:64.16-64.18" *)
  input in;
  wire in;
  (* src = "common/ef_util_lib.v:65.17-65.20" *)
  output out;
  wire out;
  (* src = "common/ef_util_lib.v:67.9-67.16" *)
  wire last_in;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0_ (
    .A(last_in),
    .SLEEP(in),
    .X(out)
  );
  (* src = "common/ef_util_lib.v:68.5-69.23" *)
  sky130_fd_sc_hd__dfxtp_1 _1_ (
    .CLK(clk),
    .D(in),
    .Q(last_in)
  );
endmodule

(* src = "common/ef_util_lib.v:48.1-57.10" *)
module ef_util_ped(clk, in, out);
  (* src = "common/ef_util_lib.v:49.16-49.19" *)
  input clk;
  wire clk;
  (* src = "common/ef_util_lib.v:50.16-50.18" *)
  input in;
  wire in;
  (* src = "common/ef_util_lib.v:51.17-51.20" *)
  output out;
  wire out;
  (* src = "common/ef_util_lib.v:53.9-53.16" *)
  wire last_in;
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _0_ (
    .A(in),
    .SLEEP(last_in),
    .X(out)
  );
  (* src = "common/ef_util_lib.v:54.5-55.16" *)
  sky130_fd_sc_hd__dfxtp_1 _1_ (
    .CLK(clk),
    .D(in),
    .Q(last_in)
  );
endmodule

(* dynports =  1  *)
(* src = "common/ef_util_lib.v:30.1-43.10" *)
module ef_util_sync(clk, in, out);
  (* src = "common/ef_util_lib.v:31.16-31.19" *)
  input clk;
  wire clk;
  (* src = "common/ef_util_lib.v:32.16-32.18" *)
  input in;
  wire in;
  (* src = "common/ef_util_lib.v:33.17-33.20" *)
  output out;
  wire out;
  (* src = "common/ef_util_lib.v:36.26-36.30" *)
  wire [1:0] sync;
  (* src = "common/ef_util_lib.v:38.5-39.44" *)
  sky130_fd_sc_hd__dfxtp_1 _0_ (
    .CLK(clk),
    .D(in),
    .Q(sync[0])
  );
  (* src = "common/ef_util_lib.v:38.5-39.44" *)
  sky130_fd_sc_hd__dfxtp_1 _1_ (
    .CLK(clk),
    .D(sync[0]),
    .Q(sync[1])
  );
  assign out = sync[1];
endmodule
