/* Generated by Yosys 0.65+71 (git sha1 e56c6a954, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:14.1-79.10" *)
module interrupt_ctrl(clk_i, rst_ni, paddr, pwdata, prdata, pwrite, psel, penable, pready, irq_in, cpu_irq_o);
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:15.24-15.29" *)
  input clk_i;
  wire clk_i;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:16.24-16.30" *)
  input rst_ni;
  wire rst_ni;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:19.24-19.29" *)
  input [7:0] paddr;
  wire [7:0] paddr;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:20.24-20.30" *)
  input [31:0] pwdata;
  wire [31:0] pwdata;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:21.24-21.30" *)
  output [31:0] prdata;
  wire [31:0] prdata;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:22.24-22.30" *)
  input pwrite;
  wire pwrite;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:23.24-23.28" *)
  input psel;
  wire psel;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:24.24-24.31" *)
  input penable;
  wire penable;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:25.24-25.30" *)
  output pready;
  wire pready;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:28.24-28.30" *)
  input [12:0] irq_in;
  wire [12:0] irq_in;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:31.24-31.33" *)
  output cpu_irq_o;
  wire cpu_irq_o;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:61.17-61.29" *)
  wire cpu_irq_comb;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:39.16-39.22" *)
  wire [15:0] irq_en;
  sky130_fd_sc_hd__clkinv_1 _050_ (
    .A(paddr[2]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _051_ (
    .A(paddr[3]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _052_ (
    .A(paddr[0]),
    .SLEEP(paddr[1]),
    .X(_043_)
  );
  sky130_fd_sc_hd__or4_1 _053_ (
    .A(paddr[6]),
    .B(paddr[7]),
    .C(paddr[4]),
    .D(paddr[5]),
    .X(_044_)
  );
  sky130_fd_sc_hd__or3_1 _054_ (
    .A(paddr[3]),
    .B(_043_),
    .C(_044_),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor4_1 _055_ (
    .A(paddr[2]),
    .B(paddr[3]),
    .C(_043_),
    .D(_044_),
    .Y(_046_)
  );
  sky130_fd_sc_hd__nand2_1 _056_ (
    .A(psel),
    .B(penable),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor2_1 _057_ (
    .A(pwrite),
    .B(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _058_ (
    .A(pwrite),
    .SLEEP(_047_),
    .X(_049_)
  );
  sky130_fd_sc_hd__and3_1 _059_ (
    .A(irq_en[15]),
    .B(_046_),
    .C(_048_),
    .X(prdata[15])
  );
  sky130_fd_sc_hd__and3_1 _060_ (
    .A(irq_en[14]),
    .B(_046_),
    .C(_048_),
    .X(prdata[14])
  );
  sky130_fd_sc_hd__and3_1 _061_ (
    .A(irq_en[13]),
    .B(_046_),
    .C(_048_),
    .X(prdata[13])
  );
  sky130_fd_sc_hd__o21ai_0 _062_ (
    .A1(_041_),
    .A2(irq_in[12]),
    .B1(irq_en[12]),
    .Y(_016_)
  );
  sky130_fd_sc_hd__nor3_1 _063_ (
    .A(_045_),
    .B(_049_),
    .C(_016_),
    .Y(prdata[12])
  );
  sky130_fd_sc_hd__o21ai_0 _064_ (
    .A1(_041_),
    .A2(irq_in[11]),
    .B1(irq_en[11]),
    .Y(_017_)
  );
  sky130_fd_sc_hd__nor3_1 _065_ (
    .A(_045_),
    .B(_049_),
    .C(_017_),
    .Y(prdata[11])
  );
  sky130_fd_sc_hd__o21ai_0 _066_ (
    .A1(_041_),
    .A2(irq_in[10]),
    .B1(irq_en[10]),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nor3_1 _067_ (
    .A(_045_),
    .B(_049_),
    .C(_018_),
    .Y(prdata[10])
  );
  sky130_fd_sc_hd__o21ai_0 _068_ (
    .A1(_041_),
    .A2(irq_in[9]),
    .B1(irq_en[9]),
    .Y(_019_)
  );
  sky130_fd_sc_hd__nor3_1 _069_ (
    .A(_045_),
    .B(_049_),
    .C(_019_),
    .Y(prdata[9])
  );
  sky130_fd_sc_hd__o21ai_0 _070_ (
    .A1(_041_),
    .A2(irq_in[8]),
    .B1(irq_en[8]),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nor3_1 _071_ (
    .A(_045_),
    .B(_049_),
    .C(_020_),
    .Y(prdata[8])
  );
  sky130_fd_sc_hd__o21ai_0 _072_ (
    .A1(_041_),
    .A2(irq_in[7]),
    .B1(irq_en[7]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor3_1 _073_ (
    .A(_045_),
    .B(_049_),
    .C(_021_),
    .Y(prdata[7])
  );
  sky130_fd_sc_hd__o21ai_0 _074_ (
    .A1(_041_),
    .A2(irq_in[6]),
    .B1(irq_en[6]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor3_1 _075_ (
    .A(_045_),
    .B(_049_),
    .C(_022_),
    .Y(prdata[6])
  );
  sky130_fd_sc_hd__o21ai_0 _076_ (
    .A1(_041_),
    .A2(irq_in[5]),
    .B1(irq_en[5]),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nor3_1 _077_ (
    .A(_045_),
    .B(_049_),
    .C(_023_),
    .Y(prdata[5])
  );
  sky130_fd_sc_hd__o21ai_0 _078_ (
    .A1(_041_),
    .A2(irq_in[4]),
    .B1(irq_en[4]),
    .Y(_024_)
  );
  sky130_fd_sc_hd__nor3_1 _079_ (
    .A(_045_),
    .B(_049_),
    .C(_024_),
    .Y(prdata[4])
  );
  sky130_fd_sc_hd__o21ai_0 _080_ (
    .A1(_041_),
    .A2(irq_in[3]),
    .B1(irq_en[3]),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor3_1 _081_ (
    .A(_045_),
    .B(_049_),
    .C(_025_),
    .Y(prdata[3])
  );
  sky130_fd_sc_hd__o21ai_0 _082_ (
    .A1(_041_),
    .A2(irq_in[2]),
    .B1(irq_en[2]),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor3_1 _083_ (
    .A(_045_),
    .B(_049_),
    .C(_026_),
    .Y(prdata[2])
  );
  sky130_fd_sc_hd__o21ai_0 _084_ (
    .A1(_041_),
    .A2(irq_in[1]),
    .B1(irq_en[1]),
    .Y(_027_)
  );
  sky130_fd_sc_hd__nor3_1 _085_ (
    .A(_045_),
    .B(_049_),
    .C(_027_),
    .Y(prdata[1])
  );
  sky130_fd_sc_hd__nand2_1 _086_ (
    .A(irq_en[9]),
    .B(irq_in[9]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nand2_1 _087_ (
    .A(irq_en[0]),
    .B(irq_in[0]),
    .Y(_029_)
  );
  sky130_fd_sc_hd__a22oi_1 _088_ (
    .A1(irq_en[3]),
    .A2(irq_in[3]),
    .B1(irq_in[2]),
    .B2(irq_en[2]),
    .Y(_030_)
  );
  sky130_fd_sc_hd__a222oi_1 _089_ (
    .A1(irq_en[5]),
    .A2(irq_in[5]),
    .B1(irq_in[4]),
    .B2(irq_en[4]),
    .C1(irq_in[1]),
    .C2(irq_en[1]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__a222oi_1 _090_ (
    .A1(irq_en[10]),
    .A2(irq_in[10]),
    .B1(irq_in[12]),
    .B2(irq_en[12]),
    .C1(irq_in[6]),
    .C2(irq_en[6]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand3_1 _091_ (
    .A(_028_),
    .B(_031_),
    .C(_032_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a222oi_1 _092_ (
    .A1(irq_en[11]),
    .A2(irq_in[11]),
    .B1(irq_in[8]),
    .B2(irq_en[8]),
    .C1(irq_in[7]),
    .C2(irq_en[7]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand3_1 _093_ (
    .A(_029_),
    .B(_030_),
    .C(_034_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _094_ (
    .A(_033_),
    .SLEEP(_035_),
    .X(cpu_irq_o)
  );
  sky130_fd_sc_hd__nor4_1 _095_ (
    .A(paddr[2]),
    .B(_042_),
    .C(_043_),
    .D(_044_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__o21ai_0 _096_ (
    .A1(_033_),
    .A2(_035_),
    .B1(_036_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__o21ai_0 _097_ (
    .A1(_041_),
    .A2(irq_in[0]),
    .B1(irq_en[0]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _098_ (
    .A(_045_),
    .SLEEP(_038_),
    .X(_039_)
  );
  sky130_fd_sc_hd__a21oi_1 _099_ (
    .A1(_037_),
    .A2(_039_),
    .B1(_049_),
    .Y(prdata[0])
  );
  sky130_fd_sc_hd__nand4_1 _100_ (
    .A(pwrite),
    .B(psel),
    .C(penable),
    .D(_046_),
    .Y(_040_)
  );
  sky130_fd_sc_hd__mux2_1 _101_ (
    .A0(pwdata[14]),
    .A1(irq_en[14]),
    .S(_040_),
    .X(_000_)
  );
  sky130_fd_sc_hd__mux2_1 _102_ (
    .A0(pwdata[13]),
    .A1(irq_en[13]),
    .S(_040_),
    .X(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _103_ (
    .A0(pwdata[12]),
    .A1(irq_en[12]),
    .S(_040_),
    .X(_002_)
  );
  sky130_fd_sc_hd__mux2_1 _104_ (
    .A0(pwdata[11]),
    .A1(irq_en[11]),
    .S(_040_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _105_ (
    .A0(pwdata[10]),
    .A1(irq_en[10]),
    .S(_040_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _106_ (
    .A0(pwdata[9]),
    .A1(irq_en[9]),
    .S(_040_),
    .X(_005_)
  );
  sky130_fd_sc_hd__mux2_1 _107_ (
    .A0(pwdata[8]),
    .A1(irq_en[8]),
    .S(_040_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _108_ (
    .A0(pwdata[7]),
    .A1(irq_en[7]),
    .S(_040_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _109_ (
    .A0(pwdata[6]),
    .A1(irq_en[6]),
    .S(_040_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _110_ (
    .A0(pwdata[5]),
    .A1(irq_en[5]),
    .S(_040_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _111_ (
    .A0(pwdata[4]),
    .A1(irq_en[4]),
    .S(_040_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _112_ (
    .A0(pwdata[3]),
    .A1(irq_en[3]),
    .S(_040_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _113_ (
    .A0(pwdata[2]),
    .A1(irq_en[2]),
    .S(_040_),
    .X(_012_)
  );
  sky130_fd_sc_hd__mux2_1 _114_ (
    .A0(pwdata[1]),
    .A1(irq_en[1]),
    .S(_040_),
    .X(_013_)
  );
  sky130_fd_sc_hd__mux2_1 _115_ (
    .A0(pwdata[0]),
    .A1(irq_en[0]),
    .S(_040_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _116_ (
    .A0(pwdata[15]),
    .A1(irq_en[15]),
    .S(_040_),
    .X(_015_)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _117_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(irq_en[0]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _118_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(irq_en[1]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _119_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(irq_en[2]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _120_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(irq_en[3]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _121_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(irq_en[4]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _122_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(irq_en[5]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _123_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(irq_en[6]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _124_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(irq_en[7]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _125_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(irq_en[8]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _126_ (
    .CLK(clk_i),
    .D(_005_),
    .Q(irq_en[9]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _127_ (
    .CLK(clk_i),
    .D(_004_),
    .Q(irq_en[10]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _128_ (
    .CLK(clk_i),
    .D(_003_),
    .Q(irq_en[11]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _129_ (
    .CLK(clk_i),
    .D(_002_),
    .Q(irq_en[12]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _130_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(irq_en[13]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _131_ (
    .CLK(clk_i),
    .D(_000_),
    .Q(irq_en[14]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-interrupt_ctrl/rtl/interrupt_ctrl.v:46.5-57.8" *)
  sky130_fd_sc_hd__dfrtp_1 _132_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(irq_en[15]),
    .RESET_B(rst_ni)
  );
  assign cpu_irq_comb = cpu_irq_o;
  assign pready = 1'h1;
  assign prdata[31:16] = 16'h0000;
endmodule
