/* Generated by Yosys 0.65+71 (git sha1 e56c6a954, clang++ 18.1.8 -fPIC -O3) */

(* top =  1  *)
(* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:11.1-125.10" *)
module sys_ctrl(clk_i, rst_ni, paddr, pwdata, prdata, pwrite, psel, penable, pready, wdt_rst_n, ext_rst_n, core_sleep_i, clk_gate_en, wake_event_i);
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:12.24-12.29" *)
  input clk_i;
  wire clk_i;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:13.24-13.30" *)
  input rst_ni;
  wire rst_ni;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:16.24-16.29" *)
  input [7:0] paddr;
  wire [7:0] paddr;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:17.24-17.30" *)
  input [31:0] pwdata;
  wire [31:0] pwdata;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:18.24-18.30" *)
  output [31:0] prdata;
  wire [31:0] prdata;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:19.24-19.30" *)
  input pwrite;
  wire pwrite;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:20.24-20.28" *)
  input psel;
  wire psel;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:21.24-21.31" *)
  input penable;
  wire penable;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:22.24-22.30" *)
  output pready;
  wire pready;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:25.24-25.33" *)
  input wdt_rst_n;
  wire wdt_rst_n;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:26.24-26.33" *)
  input ext_rst_n;
  wire ext_rst_n;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:29.24-29.36" *)
  input core_sleep_i;
  wire core_sleep_i;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:32.24-32.35" *)
  output [11:0] clk_gate_en;
  wire [11:0] clk_gate_en;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:35.24-35.36" *)
  input [1:0] wake_event_i;
  wire [1:0] wake_event_i;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  (* unused_bits = "1 2 3 4 5 6 7" *)
  wire [7:0] _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:54.16-54.30" *)
  wire cause_captured;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:40.16-40.23" *)
  wire [7:0] clk_div;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:119.17-119.32" *)
  wire [11:0] clk_gate_all_on;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:120.17-120.31" *)
  wire [11:0] clk_gate_sleep;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:55.16-55.27" *)
  wire ext_was_low;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:44.16-44.24" *)
  wire in_sleep;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:41.16-41.27" *)
  wire [2:0] reset_cause;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:53.16-53.24" *)
  wire rst_ni_d;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:42.16-42.26" *)
  (* unused_bits = "4 5 6 7" *)
  wire [7:0] sleep_ctrl;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:43.16-43.27" *)
  wire [3:0] wake_source;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:55.29-55.40" *)
  wire wdt_was_low;
  sky130_fd_sc_hd__clkinv_1 _057_ (
    .A(reset_cause[0]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__clkinv_1 _058_ (
    .A(paddr[3]),
    .Y(_041_)
  );
  sky130_fd_sc_hd__clkinv_1 _059_ (
    .A(in_sleep),
    .Y(clk_gate_en[0])
  );
  sky130_fd_sc_hd__clkinv_1 _060_ (
    .A(pwdata[0]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__clkinv_1 _061_ (
    .A(rst_ni_d),
    .Y(_043_)
  );
  sky130_fd_sc_hd__nor3_1 _062_ (
    .A(paddr[2]),
    .B(paddr[0]),
    .C(paddr[1]),
    .Y(_044_)
  );
  sky130_fd_sc_hd__or3_1 _063_ (
    .A(paddr[2]),
    .B(paddr[0]),
    .C(paddr[1]),
    .X(_045_)
  );
  sky130_fd_sc_hd__nor4_1 _064_ (
    .A(paddr[6]),
    .B(paddr[7]),
    .C(paddr[4]),
    .D(paddr[5]),
    .Y(_046_)
  );
  sky130_fd_sc_hd__or4_1 _065_ (
    .A(paddr[6]),
    .B(paddr[7]),
    .C(paddr[4]),
    .D(paddr[5]),
    .X(_047_)
  );
  sky130_fd_sc_hd__nand3_1 _066_ (
    .A(_041_),
    .B(_044_),
    .C(_046_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _067_ (
    .A(psel),
    .B(penable),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nor2_1 _068_ (
    .A(pwrite),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nand3b_1 _069_ (
    .A_N(pwrite),
    .B(psel),
    .C(penable),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor4_1 _070_ (
    .A(paddr[3]),
    .B(_045_),
    .C(_047_),
    .D(_051_),
    .Y(prdata[10])
  );
  sky130_fd_sc_hd__nor3b_1 _071_ (
    .A(paddr[0]),
    .B(paddr[1]),
    .C_N(paddr[2]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__and3_1 _072_ (
    .A(paddr[3]),
    .B(_046_),
    .C(_052_),
    .X(_053_)
  );
  sky130_fd_sc_hd__a31o_1 _073_ (
    .A1(wake_source[0]),
    .A2(_050_),
    .A3(_053_),
    .B1(prdata[10]),
    .X(prdata[8])
  );
  sky130_fd_sc_hd__and3_1 _074_ (
    .A(_041_),
    .B(_046_),
    .C(_052_),
    .X(_054_)
  );
  sky130_fd_sc_hd__and3_1 _075_ (
    .A(clk_div[7]),
    .B(_050_),
    .C(_054_),
    .X(prdata[7])
  );
  sky130_fd_sc_hd__a31o_1 _076_ (
    .A1(clk_div[6]),
    .A2(_050_),
    .A3(_054_),
    .B1(prdata[10]),
    .X(prdata[6])
  );
  sky130_fd_sc_hd__and3_1 _077_ (
    .A(clk_div[5]),
    .B(_050_),
    .C(_054_),
    .X(prdata[5])
  );
  sky130_fd_sc_hd__a31o_1 _078_ (
    .A1(clk_div[4]),
    .A2(_050_),
    .A3(_054_),
    .B1(prdata[10]),
    .X(prdata[4])
  );
  sky130_fd_sc_hd__nand4_1 _079_ (
    .A(sleep_ctrl[3]),
    .B(paddr[3]),
    .C(_046_),
    .D(_052_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nand4_1 _080_ (
    .A(clk_div[3]),
    .B(_041_),
    .C(_046_),
    .D(_052_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a21oi_1 _081_ (
    .A1(_055_),
    .A2(_056_),
    .B1(_051_),
    .Y(prdata[3])
  );
  sky130_fd_sc_hd__nand4_1 _082_ (
    .A(sleep_ctrl[2]),
    .B(paddr[3]),
    .C(_046_),
    .D(_052_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__nand4_1 _083_ (
    .A(clk_div[2]),
    .B(_041_),
    .C(_046_),
    .D(_052_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a31oi_1 _084_ (
    .A1(_048_),
    .A2(_018_),
    .A3(_019_),
    .B1(_051_),
    .Y(prdata[2])
  );
  sky130_fd_sc_hd__nand4_1 _085_ (
    .A(clk_div[1]),
    .B(_041_),
    .C(_046_),
    .D(_052_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__nand4_1 _086_ (
    .A(paddr[3]),
    .B(reset_cause[1]),
    .C(_044_),
    .D(_046_),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nand4_1 _087_ (
    .A(sleep_ctrl[1]),
    .B(paddr[3]),
    .C(_046_),
    .D(_052_),
    .Y(_022_)
  );
  sky130_fd_sc_hd__a31oi_1 _088_ (
    .A1(_020_),
    .A2(_021_),
    .A3(_022_),
    .B1(_051_),
    .Y(prdata[1])
  );
  sky130_fd_sc_hd__nor3b_1 _089_ (
    .A(cause_captured),
    .B(rst_ni_d),
    .C_N(rst_ni),
    .Y(_023_)
  );
  sky130_fd_sc_hd__nand2_1 _090_ (
    .A(wdt_rst_n),
    .B(_023_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__o21a_1 _091_ (
    .A1(reset_cause[1]),
    .A2(_023_),
    .B1(_024_),
    .X(_001_)
  );
  sky130_fd_sc_hd__o22ai_1 _092_ (
    .A1(_040_),
    .A2(_023_),
    .B1(_024_),
    .B2(ext_rst_n),
    .Y(_002_)
  );
  sky130_fd_sc_hd__and3_1 _093_ (
    .A(pwrite),
    .B(psel),
    .C(penable),
    .X(_025_)
  );
  sky130_fd_sc_hd__nand4_1 _094_ (
    .A(paddr[3]),
    .B(_046_),
    .C(_052_),
    .D(_025_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__mux2_1 _095_ (
    .A0(pwdata[3]),
    .A1(sleep_ctrl[3]),
    .S(_026_),
    .X(_003_)
  );
  sky130_fd_sc_hd__mux2_1 _096_ (
    .A0(pwdata[2]),
    .A1(sleep_ctrl[2]),
    .S(_026_),
    .X(_004_)
  );
  sky130_fd_sc_hd__mux2_1 _097_ (
    .A0(pwdata[1]),
    .A1(sleep_ctrl[1]),
    .S(_026_),
    .X(_005_)
  );
  sky130_fd_sc_hd__and4_1 _098_ (
    .A(_041_),
    .B(_046_),
    .C(_052_),
    .D(_025_),
    .X(_027_)
  );
  sky130_fd_sc_hd__mux2_1 _099_ (
    .A0(clk_div[6]),
    .A1(pwdata[6]),
    .S(_027_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _100_ (
    .A0(clk_div[5]),
    .A1(pwdata[5]),
    .S(_027_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _101_ (
    .A0(clk_div[4]),
    .A1(pwdata[4]),
    .S(_027_),
    .X(_008_)
  );
  sky130_fd_sc_hd__mux2_1 _102_ (
    .A0(clk_div[3]),
    .A1(pwdata[3]),
    .S(_027_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _103_ (
    .A0(clk_div[2]),
    .A1(pwdata[2]),
    .S(_027_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _104_ (
    .A0(clk_div[1]),
    .A1(pwdata[1]),
    .S(_027_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _105_ (
    .A0(clk_div[0]),
    .A1(pwdata[0]),
    .S(_027_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _106_ (
    .A(wake_event_i[0]),
    .B(wake_event_i[1]),
    .Y(_028_)
  );
  sky130_fd_sc_hd__nor2_1 _107_ (
    .A(clk_gate_en[0]),
    .B(_028_),
    .Y(_029_)
  );
  sky130_fd_sc_hd__o21ai_0 _108_ (
    .A1(wake_event_i[0]),
    .A2(wake_event_i[1]),
    .B1(in_sleep),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _109_ (
    .A(in_sleep),
    .B(wake_event_i[0]),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nand2_1 _110_ (
    .A(wake_source[0]),
    .B(_030_),
    .Y(_032_)
  );
  sky130_fd_sc_hd__nand2_1 _111_ (
    .A(_031_),
    .B(_032_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__a41oi_1 _112_ (
    .A1(paddr[3]),
    .A2(_046_),
    .A3(_052_),
    .A4(_025_),
    .B1(sleep_ctrl[0]),
    .Y(_033_)
  );
  sky130_fd_sc_hd__a311oi_1 _113_ (
    .A1(_042_),
    .A2(_053_),
    .A3(_025_),
    .B1(_029_),
    .C1(_033_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__nand2_1 _114_ (
    .A(in_sleep),
    .B(wake_event_i[1]),
    .Y(_034_)
  );
  sky130_fd_sc_hd__nand2_1 _115_ (
    .A(wake_source[1]),
    .B(_030_),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _116_ (
    .A(_034_),
    .B(_035_),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a21o_1 _117_ (
    .A1(rst_ni),
    .A2(_043_),
    .B1(cause_captured),
    .X(_015_)
  );
  sky130_fd_sc_hd__nand4_1 _118_ (
    .A(reset_cause[0]),
    .B(paddr[3]),
    .C(_044_),
    .D(_046_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nand4_1 _119_ (
    .A(clk_div[0]),
    .B(_041_),
    .C(_046_),
    .D(_052_),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nand4_1 _120_ (
    .A(sleep_ctrl[0]),
    .B(paddr[3]),
    .C(_046_),
    .D(_052_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__a41oi_1 _121_ (
    .A1(_048_),
    .A2(_036_),
    .A3(_037_),
    .A4(_038_),
    .B1(_051_),
    .Y(prdata[0])
  );
  sky130_fd_sc_hd__a31o_1 _122_ (
    .A1(wake_source[1]),
    .A2(_050_),
    .A3(_053_),
    .B1(prdata[10]),
    .X(prdata[9])
  );
  sky130_fd_sc_hd__a21oi_1 _123_ (
    .A1(sleep_ctrl[0]),
    .A2(core_sleep_i),
    .B1(in_sleep),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nor2_1 _124_ (
    .A(_029_),
    .B(_039_),
    .Y(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _125_ (
    .A0(clk_div[7]),
    .A1(pwdata[7]),
    .S(_027_),
    .X(_017_)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _126_ (
    .CLK(clk_i),
    .D(_013_),
    .Q(wake_source[0]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _127_ (
    .CLK(clk_i),
    .D(_014_),
    .Q(wake_source[1]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfstp_2 _128_ (
    .CLK(clk_i),
    .D(_012_),
    .Q(clk_div[0]),
    .SET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _129_ (
    .CLK(clk_i),
    .D(_011_),
    .Q(clk_div[1]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _130_ (
    .CLK(clk_i),
    .D(_010_),
    .Q(clk_div[2]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _131_ (
    .CLK(clk_i),
    .D(_009_),
    .Q(clk_div[3]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _132_ (
    .CLK(clk_i),
    .D(_008_),
    .Q(clk_div[4]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _133_ (
    .CLK(clk_i),
    .D(_007_),
    .Q(clk_div[5]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _134_ (
    .CLK(clk_i),
    .D(_006_),
    .Q(clk_div[6]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _135_ (
    .CLK(clk_i),
    .D(_017_),
    .Q(clk_div[7]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _136_ (
    .CLK(clk_i),
    .D(_000_[0]),
    .Q(sleep_ctrl[0]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _137_ (
    .CLK(clk_i),
    .D(_005_),
    .Q(sleep_ctrl[1]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _138_ (
    .CLK(clk_i),
    .D(_004_),
    .Q(sleep_ctrl[2]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _139_ (
    .CLK(clk_i),
    .D(_003_),
    .Q(sleep_ctrl[3]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _140_ (
    .CLK(clk_i),
    .D(_015_),
    .Q(cause_captured),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _141_ (
    .CLK(clk_i),
    .D(_016_),
    .Q(in_sleep),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _142_ (
    .CLK(clk_i),
    .D(_002_),
    .Q(reset_cause[0]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _143_ (
    .CLK(clk_i),
    .D(_001_),
    .Q(reset_cause[1]),
    .RESET_B(rst_ni)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-sys_ctrl/rtl/sys_ctrl.v:57.5-102.8" *)
  sky130_fd_sc_hd__dfrtp_1 _144_ (
    .CLK(clk_i),
    .D(rst_ni),
    .Q(rst_ni_d),
    .RESET_B(rst_ni)
  );
  assign clk_gate_sleep = 12'h048;
  assign clk_gate_all_on = 12'hfff;
  assign wdt_was_low = 1'h0;
  assign ext_was_low = 1'h0;
  assign wake_source[3:2] = 2'h0;
  assign reset_cause[2] = 1'h0;
  assign clk_gate_en[11:1] = { clk_gate_en[0], clk_gate_en[0], clk_gate_en[0], clk_gate_en[0], clk_gate_en[0], 1'h1, clk_gate_en[0], clk_gate_en[0], 1'h1, clk_gate_en[0], clk_gate_en[0] };
  assign pready = 1'h1;
  assign prdata[31:11] = { 1'h0, prdata[10], 5'h00, prdata[10], 1'h0, prdata[10], 1'h0, prdata[10], 2'h0, prdata[10], 2'h0, prdata[10], 3'h0 };
endmodule
