/* Generated by Yosys 0.65+71 (git sha1 e56c6a954, clang++ 18.1.8 -fPIC -O3) */

(* dynports =  1  *)
(* hdlname = "spi_master" *)
(* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:50.1-187.10" *)
module \$paramod$1b57ab934979e1dcff9d7d7aa75fd3de5f50b91e\spi_master (clk, resetb, CPOL, CPHA, clk_divider, enable, go, datai, datao, busy, done, dout, din, csb, sclk);
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:56.15-56.18" *)
  input clk;
  wire clk;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:57.15-57.21" *)
  input resetb;
  wire resetb;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:58.15-58.19" *)
  input CPOL;
  wire CPOL;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:59.15-59.19" *)
  input CPHA;
  wire CPHA;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:60.39-60.50" *)
  input [7:0] clk_divider;
  wire [7:0] clk_divider;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:61.15-61.21" *)
  input enable;
  wire enable;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:62.15-62.17" *)
  input go;
  wire go;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:63.44-63.49" *)
  input [7:0] datai;
  wire [7:0] datai;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:64.45-64.50" *)
  output [7:0] datao;
  wire [7:0] datao;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:65.15-65.19" *)
  output busy;
  wire busy;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:66.15-66.19" *)
  output done;
  wire done;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:68.31-68.35" *)
  input [0:0] dout;
  wire [0:0] dout;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:69.32-69.35" *)
  output [0:0] din;
  wire [0:0] din;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:70.15-70.18" *)
  output csb;
  wire csb;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:71.15-71.19" *)
  output sclk;
  wire sclk;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  wire [7:0] _000_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:109.14-109.74" *)
  wire _012_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:117.15-117.42" *)
  wire _013_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:118.14-118.61" *)
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:74.34-74.43" *)
  wire [7:0] clk_count;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:95.28-95.39" *)
  wire [4:0] shift_count;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:77.11-77.16" *)
  wire state;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:101.9-101.15" *)
  wire stop_s;
  sky130_fd_sc_hd__clkinv_1 _071_ (
    .A(shift_count[3]),
    .Y(_032_)
  );
  sky130_fd_sc_hd__clkinv_1 _072_ (
    .A(state),
    .Y(_033_)
  );
  sky130_fd_sc_hd__clkinv_1 _073_ (
    .A(csb),
    .Y(_034_)
  );
  sky130_fd_sc_hd__clkinv_1 _074_ (
    .A(busy),
    .Y(_035_)
  );
  sky130_fd_sc_hd__nand2_1 _075_ (
    .A(clk_count[1]),
    .B(clk_count[0]),
    .Y(_036_)
  );
  sky130_fd_sc_hd__and4_1 _076_ (
    .A(clk_count[1]),
    .B(clk_count[0]),
    .C(clk_count[3]),
    .D(clk_count[2]),
    .X(_037_)
  );
  sky130_fd_sc_hd__nand2_1 _077_ (
    .A(clk_count[4]),
    .B(_037_),
    .Y(_038_)
  );
  sky130_fd_sc_hd__and4_1 _078_ (
    .A(clk_count[6]),
    .B(clk_count[4]),
    .C(clk_count[5]),
    .D(_037_),
    .X(_039_)
  );
  sky130_fd_sc_hd__a31oi_1 _079_ (
    .A1(clk_count[4]),
    .A2(clk_count[5]),
    .A3(_037_),
    .B1(clk_count[6]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _080_ (
    .A(_039_),
    .SLEEP(_040_),
    .X(_041_)
  );
  sky130_fd_sc_hd__a31oi_1 _081_ (
    .A1(clk_count[1]),
    .A2(clk_count[0]),
    .A3(clk_count[2]),
    .B1(clk_count[3]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _082_ (
    .A(_037_),
    .SLEEP(_042_),
    .X(_043_)
  );
  sky130_fd_sc_hd__or3_1 _083_ (
    .A(clk_divider[4]),
    .B(_037_),
    .C(_042_),
    .X(_044_)
  );
  sky130_fd_sc_hd__xor2_1 _084_ (
    .A(clk_divider[4]),
    .B(_043_),
    .X(_045_)
  );
  sky130_fd_sc_hd__xor2_1 _085_ (
    .A(clk_count[2]),
    .B(_036_),
    .X(_046_)
  );
  sky130_fd_sc_hd__xor2_1 _086_ (
    .A(clk_divider[3]),
    .B(_046_),
    .X(_047_)
  );
  sky130_fd_sc_hd__xnor2_1 _087_ (
    .A(clk_count[1]),
    .B(clk_count[0]),
    .Y(_048_)
  );
  sky130_fd_sc_hd__nand2_1 _088_ (
    .A(clk_divider[2]),
    .B(_048_),
    .Y(_049_)
  );
  sky130_fd_sc_hd__xor2_1 _089_ (
    .A(clk_count[0]),
    .B(clk_divider[1]),
    .X(_050_)
  );
  sky130_fd_sc_hd__and3_1 _090_ (
    .A(enable),
    .B(_049_),
    .C(_050_),
    .X(_051_)
  );
  sky130_fd_sc_hd__o2111ai_1 _091_ (
    .A1(clk_divider[2]),
    .A2(_048_),
    .B1(_051_),
    .C1(_045_),
    .D1(_047_),
    .Y(_052_)
  );
  sky130_fd_sc_hd__xor2_1 _092_ (
    .A(clk_count[5]),
    .B(_038_),
    .X(_053_)
  );
  sky130_fd_sc_hd__xnor2_1 _093_ (
    .A(clk_count[4]),
    .B(_037_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__xor2_1 _094_ (
    .A(clk_divider[5]),
    .B(_054_),
    .X(_055_)
  );
  sky130_fd_sc_hd__o21ai_0 _095_ (
    .A1(clk_divider[6]),
    .A2(_053_),
    .B1(_055_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__a211oi_1 _096_ (
    .A1(clk_divider[6]),
    .A2(_053_),
    .B1(_056_),
    .C1(_052_),
    .Y(_057_)
  );
  sky130_fd_sc_hd__xnor2_1 _097_ (
    .A(clk_count[7]),
    .B(_039_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__clkinv_1 _098_ (
    .A(_058_),
    .Y(_000_[7])
  );
  sky130_fd_sc_hd__nor2_1 _099_ (
    .A(clk_divider[7]),
    .B(_041_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__o21ai_0 _100_ (
    .A1(_039_),
    .A2(_040_),
    .B1(clk_divider[7]),
    .Y(_060_)
  );
  sky130_fd_sc_hd__nand4b_1 _101_ (
    .A_N(_059_),
    .B(_060_),
    .C(_057_),
    .D(_058_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__xor3_1 _102_ (
    .A(clk_divider[6]),
    .B(clk_count[5]),
    .C(_038_),
    .X(_062_)
  );
  sky130_fd_sc_hd__o221ai_1 _103_ (
    .A1(clk_divider[3]),
    .A2(_046_),
    .B1(_048_),
    .B2(clk_divider[2]),
    .C1(enable),
    .Y(_063_)
  );
  sky130_fd_sc_hd__a22o_1 _104_ (
    .A1(clk_divider[4]),
    .A2(_043_),
    .B1(_054_),
    .B2(clk_divider[5]),
    .X(_064_)
  );
  sky130_fd_sc_hd__a211o_1 _105_ (
    .A1(clk_divider[3]),
    .A2(_046_),
    .B1(_063_),
    .C1(_064_),
    .X(_065_)
  );
  sky130_fd_sc_hd__o2111a_1 _106_ (
    .A1(clk_divider[5]),
    .A2(_054_),
    .B1(_050_),
    .C1(_049_),
    .D1(_044_),
    .X(_066_)
  );
  sky130_fd_sc_hd__nand4_1 _107_ (
    .A(_058_),
    .B(_060_),
    .C(_062_),
    .D(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nor3_1 _108_ (
    .A(_059_),
    .B(_065_),
    .C(_067_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor2_1 _109_ (
    .A(_041_),
    .B(_068_),
    .Y(_000_[6])
  );
  sky130_fd_sc_hd__nor2_1 _110_ (
    .A(_053_),
    .B(_068_),
    .Y(_000_[5])
  );
  sky130_fd_sc_hd__nor2_1 _111_ (
    .A(_054_),
    .B(_068_),
    .Y(_000_[4])
  );
  sky130_fd_sc_hd__nor2_1 _112_ (
    .A(_043_),
    .B(_068_),
    .Y(_000_[3])
  );
  sky130_fd_sc_hd__nor2_1 _113_ (
    .A(_046_),
    .B(_068_),
    .Y(_000_[2])
  );
  sky130_fd_sc_hd__nor2_1 _114_ (
    .A(_048_),
    .B(_068_),
    .Y(_000_[1])
  );
  sky130_fd_sc_hd__nor2_1 _115_ (
    .A(clk_count[0]),
    .B(_068_),
    .Y(_000_[0])
  );
  sky130_fd_sc_hd__nand2_1 _116_ (
    .A(shift_count[1]),
    .B(shift_count[0]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__and3_1 _117_ (
    .A(shift_count[2]),
    .B(shift_count[1]),
    .C(shift_count[0]),
    .X(_070_)
  );
  sky130_fd_sc_hd__a21oi_1 _118_ (
    .A1(shift_count[3]),
    .A2(_070_),
    .B1(shift_count[4]),
    .Y(_015_)
  );
  sky130_fd_sc_hd__a21o_1 _119_ (
    .A1(shift_count[3]),
    .A2(_070_),
    .B1(shift_count[4]),
    .X(_016_)
  );
  sky130_fd_sc_hd__or4_1 _120_ (
    .A(_059_),
    .B(_065_),
    .C(_067_),
    .D(_016_),
    .X(_017_)
  );
  sky130_fd_sc_hd__nand4_1 _121_ (
    .A(_034_),
    .B(_068_),
    .C(_070_),
    .D(_015_),
    .Y(_018_)
  );
  sky130_fd_sc_hd__a21oi_1 _122_ (
    .A1(_032_),
    .A2(_018_),
    .B1(_033_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor3_1 _123_ (
    .A(csb),
    .B(_069_),
    .C(_017_),
    .Y(_019_)
  );
  sky130_fd_sc_hd__a41oi_1 _124_ (
    .A1(_034_),
    .A2(_068_),
    .A3(_070_),
    .A4(_015_),
    .B1(_033_),
    .Y(_020_)
  );
  sky130_fd_sc_hd__o21a_1 _125_ (
    .A1(shift_count[2]),
    .A2(_019_),
    .B1(_020_),
    .X(_003_)
  );
  sky130_fd_sc_hd__nor3b_1 _126_ (
    .A(_017_),
    .B(csb),
    .C_N(shift_count[0]),
    .Y(_014_)
  );
  sky130_fd_sc_hd__a41oi_1 _127_ (
    .A1(_034_),
    .A2(shift_count[0]),
    .A3(_068_),
    .A4(_015_),
    .B1(shift_count[1]),
    .Y(_021_)
  );
  sky130_fd_sc_hd__nor3_1 _128_ (
    .A(_033_),
    .B(_019_),
    .C(_021_),
    .Y(_004_)
  );
  sky130_fd_sc_hd__a31oi_1 _129_ (
    .A1(_034_),
    .A2(_068_),
    .A3(_015_),
    .B1(shift_count[0]),
    .Y(_022_)
  );
  sky130_fd_sc_hd__nor3_1 _130_ (
    .A(_033_),
    .B(_014_),
    .C(_022_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _131_ (
    .A(go),
    .SLEEP(state),
    .X(_013_)
  );
  sky130_fd_sc_hd__nand2_1 _132_ (
    .A(_035_),
    .B(_013_),
    .Y(_023_)
  );
  sky130_fd_sc_hd__a31o_1 _133_ (
    .A1(done),
    .A2(_068_),
    .A3(_016_),
    .B1(_033_),
    .X(_024_)
  );
  sky130_fd_sc_hd__nand2_1 _134_ (
    .A(_023_),
    .B(_024_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__mux2_1 _135_ (
    .A0(stop_s),
    .A1(_016_),
    .S(_068_),
    .X(_006_)
  );
  sky130_fd_sc_hd__nor4_1 _136_ (
    .A(csb),
    .B(shift_count[0]),
    .C(stop_s),
    .D(_061_),
    .Y(_012_)
  );
  sky130_fd_sc_hd__nor2_1 _137_ (
    .A(sclk),
    .B(_068_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _138_ (
    .A(csb),
    .B(CPHA),
    .Y(_026_)
  );
  sky130_fd_sc_hd__a21oi_1 _139_ (
    .A1(state),
    .A2(CPHA),
    .B1(_026_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__o21ai_0 _140_ (
    .A1(_016_),
    .A2(_027_),
    .B1(CPOL),
    .Y(_028_)
  );
  sky130_fd_sc_hd__or3_1 _141_ (
    .A(sclk),
    .B(_016_),
    .C(_027_),
    .X(_029_)
  );
  sky130_fd_sc_hd__a31oi_1 _142_ (
    .A1(_068_),
    .A2(_028_),
    .A3(_029_),
    .B1(_025_),
    .Y(_007_)
  );
  sky130_fd_sc_hd__nand2_1 _143_ (
    .A(csb),
    .B(_017_),
    .Y(_030_)
  );
  sky130_fd_sc_hd__nand2_1 _144_ (
    .A(state),
    .B(_030_),
    .Y(_008_)
  );
  sky130_fd_sc_hd__and2_0 _145_ (
    .A(shift_count[4]),
    .B(state),
    .X(_009_)
  );
  sky130_fd_sc_hd__a21oi_1 _146_ (
    .A1(_068_),
    .A2(_016_),
    .B1(done),
    .Y(_031_)
  );
  sky130_fd_sc_hd__nor2_1 _147_ (
    .A(_024_),
    .B(_031_),
    .Y(_010_)
  );
  sky130_fd_sc_hd__o21ai_0 _148_ (
    .A1(_035_),
    .A2(_024_),
    .B1(_023_),
    .Y(_011_)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _149_ (
    .CLK(clk),
    .D(_006_),
    .Q(stop_s),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfstp_2 _150_ (
    .CLK(clk),
    .D(_007_),
    .Q(sclk),
    .SET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfstp_2 _151_ (
    .CLK(clk),
    .D(_008_),
    .Q(csb),
    .SET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _152_ (
    .CLK(clk),
    .D(_005_),
    .Q(shift_count[0]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _153_ (
    .CLK(clk),
    .D(_004_),
    .Q(shift_count[1]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _154_ (
    .CLK(clk),
    .D(_003_),
    .Q(shift_count[2]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _155_ (
    .CLK(clk),
    .D(_002_),
    .Q(shift_count[3]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _156_ (
    .CLK(clk),
    .D(_009_),
    .Q(shift_count[4]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _157_ (
    .CLK(clk),
    .D(_010_),
    .Q(done),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _158_ (
    .CLK(clk),
    .D(_011_),
    .Q(busy),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _159_ (
    .CLK(clk),
    .D(_000_[0]),
    .Q(clk_count[0]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _160_ (
    .CLK(clk),
    .D(_000_[1]),
    .Q(clk_count[1]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _161_ (
    .CLK(clk),
    .D(_000_[2]),
    .Q(clk_count[2]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _162_ (
    .CLK(clk),
    .D(_000_[3]),
    .Q(clk_count[3]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _163_ (
    .CLK(clk),
    .D(_000_[4]),
    .Q(clk_count[4]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _164_ (
    .CLK(clk),
    .D(_000_[5]),
    .Q(clk_count[5]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _165_ (
    .CLK(clk),
    .D(_000_[6]),
    .Q(clk_count[6]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _166_ (
    .CLK(clk),
    .D(_000_[7]),
    .Q(clk_count[7]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:124.4-186.7" *)
  sky130_fd_sc_hd__dfrtp_1 _167_ (
    .CLK(clk),
    .D(_001_),
    .Q(state),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:113.35-119.17" *)
  \$paramod\sri\DATA_WIDTH=s32'00000000000000000000000000001000  \sri[0]  (
    .clk(clk),
    .datai(datai),
    .din(din),
    .resetb(resetb),
    .sample(_013_),
    .shift(_014_)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:106.35-111.21" *)
  \$paramod\sro\DATA_WIDTH=s32'00000000000000000000000000001000  \sro[0]  (
    .clk(clk),
    .datao(datao),
    .dout(dout),
    .resetb(resetb),
    .shift(_012_)
  );
endmodule

(* dynports =  1  *)
(* hdlname = "EF_SPI" *)
(* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:23.1-149.10" *)
module \$paramod$c472ad5b357594777851f1f1c93c46d2cb71eced\EF_SPI (clk, rst_n, CPOL, CPHA, clk_divider, wr, rd, datai, datao, enable, rx_en, rx_flush, rx_threshold, rx_empty, rx_full, rx_level_above, rx_level, tx_flush, tx_threshold, tx_empty, tx_full
, tx_level_below, tx_level, busy, done, miso, mosi, csb, ss, sclk);
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:27.29-27.32" *)
  input clk;
  wire clk;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:28.29-28.34" *)
  input rst_n;
  wire rst_n;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:29.29-29.33" *)
  input CPOL;
  wire CPOL;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:30.29-30.33" *)
  input CPHA;
  wire CPHA;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:31.29-31.40" *)
  input [7:0] clk_divider;
  wire [7:0] clk_divider;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:32.29-32.31" *)
  input wr;
  wire wr;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:33.29-33.31" *)
  input rd;
  wire rd;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:34.29-34.34" *)
  input [7:0] datai;
  wire [7:0] datai;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:35.29-35.34" *)
  output [7:0] datao;
  wire [7:0] datao;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:36.29-36.35" *)
  input enable;
  wire enable;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:37.29-37.34" *)
  input rx_en;
  wire rx_en;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:38.29-38.37" *)
  input rx_flush;
  wire rx_flush;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:39.29-39.41" *)
  input [3:0] rx_threshold;
  wire [3:0] rx_threshold;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:40.29-40.37" *)
  output rx_empty;
  wire rx_empty;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:41.29-41.36" *)
  output rx_full;
  wire rx_full;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:42.29-42.43" *)
  output rx_level_above;
  wire rx_level_above;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:43.29-43.37" *)
  output [3:0] rx_level;
  wire [3:0] rx_level;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:45.29-45.37" *)
  input tx_flush;
  wire tx_flush;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:46.29-46.41" *)
  input [3:0] tx_threshold;
  wire [3:0] tx_threshold;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:47.29-47.37" *)
  output tx_empty;
  wire tx_empty;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:48.29-48.36" *)
  output tx_full;
  wire tx_full;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:49.29-49.43" *)
  output tx_level_below;
  wire tx_level_below;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:50.29-50.37" *)
  output [3:0] tx_level;
  wire [3:0] tx_level;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:52.29-52.33" *)
  output busy;
  wire busy;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:53.29-53.33" *)
  output done;
  wire done;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:55.29-55.33" *)
  input miso;
  wire miso;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:56.29-56.33" *)
  output mosi;
  wire mosi;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:57.29-57.32" *)
  output csb;
  wire csb;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:58.29-58.31" *)
  input ss;
  wire ss;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:59.29-59.33" *)
  output sclk;
  wire sclk;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:74.17-74.24" *)
  wire done_pe;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:78.17-78.24" *)
  wire [7:0] f_datao;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:76.17-76.22" *)
  wire rx_rd;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:80.17-80.25" *)
  wire [7:0] rx_rdata;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:79.17-79.25" *)
  wire [7:0] rx_wdata;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:75.17-75.22" *)
  wire rx_wr;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:67.17-67.23" *)
  wire spi_go;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:66.17-66.22" *)
  wire tx_rd;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:71.17-71.25" *)
  wire [7:0] tx_rdata;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:70.17-70.25" *)
  wire [7:0] tx_wdata;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:65.17-65.22" *)
  wire tx_wr;
  sky130_fd_sc_hd__clkinv_1 _15_ (
    .A(rx_threshold[2]),
    .Y(_00_)
  );
  sky130_fd_sc_hd__clkinv_1 _16_ (
    .A(tx_threshold[1]),
    .Y(_01_)
  );
  sky130_fd_sc_hd__clkinv_1 _17_ (
    .A(rx_threshold[3]),
    .Y(_02_)
  );
  sky130_fd_sc_hd__clkinv_1 _18_ (
    .A(tx_threshold[3]),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _19_ (
    .A(ss),
    .Y(csb)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _20_ (
    .A(rx_level[1]),
    .SLEEP(rx_threshold[1]),
    .X(_04_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _21_ (
    .A(rx_level[0]),
    .SLEEP(rx_threshold[0]),
    .X(_05_)
  );
  sky130_fd_sc_hd__nand2b_1 _22_ (
    .A_N(rx_level[1]),
    .B(rx_threshold[1]),
    .Y(_06_)
  );
  sky130_fd_sc_hd__o221ai_1 _23_ (
    .A1(_00_),
    .A2(rx_level[2]),
    .B1(_04_),
    .B2(_05_),
    .C1(_06_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a22oi_1 _24_ (
    .A1(_00_),
    .A2(rx_level[2]),
    .B1(rx_level[3]),
    .B2(_02_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a2bb2oi_1 _25_ (
    .A1_N(rx_level[3]),
    .A2_N(_02_),
    .B1(_07_),
    .B2(_08_),
    .Y(rx_level_above)
  );
  sky130_fd_sc_hd__nand2b_1 _26_ (
    .A_N(tx_level[0]),
    .B(tx_threshold[0]),
    .Y(_09_)
  );
  sky130_fd_sc_hd__maj3_1 _27_ (
    .A(tx_level[1]),
    .B(_01_),
    .C(_09_),
    .X(_10_)
  );
  sky130_fd_sc_hd__xnor2_1 _28_ (
    .A(tx_level[3]),
    .B(tx_threshold[3]),
    .Y(_11_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _29_ (
    .A(tx_level[2]),
    .SLEEP(tx_threshold[2]),
    .X(_12_)
  );
  sky130_fd_sc_hd__xnor2_1 _30_ (
    .A(tx_threshold[2]),
    .B(tx_level[2]),
    .Y(_13_)
  );
  sky130_fd_sc_hd__maj3_1 _31_ (
    .A(tx_level[3]),
    .B(_03_),
    .C(_12_),
    .X(_14_)
  );
  sky130_fd_sc_hd__a31oi_1 _32_ (
    .A1(_10_),
    .A2(_11_),
    .A3(_13_),
    .B1(_14_),
    .Y(tx_level_below)
  );
  sky130_fd_sc_hd__and2_0 _33_ (
    .A(rx_en),
    .B(done_pe),
    .X(rx_wr)
  );
  sky130_fd_sc_hd__nor2_1 _34_ (
    .A(busy),
    .B(tx_empty),
    .Y(spi_go)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:88.17-92.6" *)
  ef_util_ped done_ed (
    .clk(clk),
    .in(done),
    .out(done_pe)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:97.7-108.6" *)
  ef_util_fifo #(
    .AW(32'sd4),
    .DW(32'sd8)
  ) rx_fifo (
    .clk(clk),
    .empty(rx_empty),
    .flush(rx_flush),
    .full(rx_full),
    .level(rx_level),
    .rd(rd),
    .rdata(rx_rdata),
    .rst_n(rst_n),
    .wdata(f_datao),
    .wr(rx_wr)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:131.7-147.5" *)
  \$paramod$1b57ab934979e1dcff9d7d7aa75fd3de5f50b91e\spi_master  spi_master (
    .CPHA(CPHA),
    .CPOL(CPOL),
    .busy(busy),
    .clk(clk),
    .clk_divider(clk_divider),
    .datai(tx_rdata),
    .datao(f_datao),
    .din(mosi),
    .done(done),
    .dout(miso),
    .enable(enable),
    .go(spi_go),
    .resetb(rst_n),
    .sclk(sclk)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI.v:113.7-124.6" *)
  ef_util_fifo #(
    .AW(32'sd4),
    .DW(32'sd8)
  ) tx_fifo (
    .clk(clk),
    .empty(tx_empty),
    .flush(tx_flush),
    .full(tx_full),
    .level(tx_level),
    .rd(spi_go),
    .rdata(tx_rdata),
    .rst_n(rst_n),
    .wdata(datai),
    .wr(wr)
  );
  assign rx_wdata = f_datao;
  assign rx_rd = rd;
  assign tx_wdata = datai;
  assign tx_rd = spi_go;
  assign tx_wr = wr;
  assign datao = rx_rdata;
endmodule

(* dynports =  1  *)
(* hdlname = "sri" *)
(* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:189.1-219.10" *)
module \$paramod\sri\DATA_WIDTH=s32'00000000000000000000000000001000 (clk, resetb, datai, sample, shift, din);
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:193.15-193.18" *)
  input clk;
  wire clk;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:194.15-194.21" *)
  input resetb;
  wire resetb;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:195.32-195.37" *)
  input [7:0] datai;
  wire [7:0] datai;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:196.15-196.21" *)
  input sample;
  wire sample;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:197.15-197.20" *)
  input shift;
  wire shift;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:198.16-198.19" *)
  output din;
  wire din;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:201.25-201.31" *)
  wire [7:0] sr_reg;
  sky130_fd_sc_hd__nor2_1 _16_ (
    .A(sample),
    .B(shift),
    .Y(_08_)
  );
  sky130_fd_sc_hd__and3b_1 _17_ (
    .A_N(sample),
    .B(sr_reg[5]),
    .C(shift),
    .X(_09_)
  );
  sky130_fd_sc_hd__a221o_1 _18_ (
    .A1(datai[6]),
    .A2(sample),
    .B1(sr_reg[6]),
    .B2(_08_),
    .C1(_09_),
    .X(_00_)
  );
  sky130_fd_sc_hd__and3b_1 _19_ (
    .A_N(sample),
    .B(shift),
    .C(sr_reg[4]),
    .X(_10_)
  );
  sky130_fd_sc_hd__a221o_1 _20_ (
    .A1(sample),
    .A2(datai[5]),
    .B1(sr_reg[5]),
    .B2(_08_),
    .C1(_10_),
    .X(_01_)
  );
  sky130_fd_sc_hd__and3b_1 _21_ (
    .A_N(sample),
    .B(shift),
    .C(sr_reg[3]),
    .X(_11_)
  );
  sky130_fd_sc_hd__a221o_1 _22_ (
    .A1(sample),
    .A2(datai[4]),
    .B1(sr_reg[4]),
    .B2(_08_),
    .C1(_11_),
    .X(_02_)
  );
  sky130_fd_sc_hd__and3b_1 _23_ (
    .A_N(sample),
    .B(shift),
    .C(sr_reg[2]),
    .X(_12_)
  );
  sky130_fd_sc_hd__a221o_1 _24_ (
    .A1(sample),
    .A2(datai[3]),
    .B1(sr_reg[3]),
    .B2(_08_),
    .C1(_12_),
    .X(_03_)
  );
  sky130_fd_sc_hd__and3b_1 _25_ (
    .A_N(sample),
    .B(shift),
    .C(sr_reg[1]),
    .X(_13_)
  );
  sky130_fd_sc_hd__a221o_1 _26_ (
    .A1(sample),
    .A2(datai[2]),
    .B1(sr_reg[2]),
    .B2(_08_),
    .C1(_13_),
    .X(_04_)
  );
  sky130_fd_sc_hd__and3b_1 _27_ (
    .A_N(sample),
    .B(shift),
    .C(sr_reg[0]),
    .X(_14_)
  );
  sky130_fd_sc_hd__a221o_1 _28_ (
    .A1(sample),
    .A2(datai[1]),
    .B1(sr_reg[1]),
    .B2(_08_),
    .C1(_14_),
    .X(_05_)
  );
  sky130_fd_sc_hd__a22o_1 _29_ (
    .A1(sample),
    .A2(datai[0]),
    .B1(sr_reg[0]),
    .B2(_08_),
    .X(_06_)
  );
  sky130_fd_sc_hd__and3b_1 _30_ (
    .A_N(sample),
    .B(shift),
    .C(sr_reg[6]),
    .X(_15_)
  );
  sky130_fd_sc_hd__a221o_1 _31_ (
    .A1(sample),
    .A2(datai[7]),
    .B1(sr_reg[7]),
    .B2(_08_),
    .C1(_15_),
    .X(_07_)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:207.4-218.7" *)
  sky130_fd_sc_hd__dfrtp_1 _32_ (
    .CLK(clk),
    .D(_06_),
    .Q(sr_reg[0]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:207.4-218.7" *)
  sky130_fd_sc_hd__dfrtp_1 _33_ (
    .CLK(clk),
    .D(_05_),
    .Q(sr_reg[1]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:207.4-218.7" *)
  sky130_fd_sc_hd__dfrtp_1 _34_ (
    .CLK(clk),
    .D(_04_),
    .Q(sr_reg[2]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:207.4-218.7" *)
  sky130_fd_sc_hd__dfrtp_1 _35_ (
    .CLK(clk),
    .D(_03_),
    .Q(sr_reg[3]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:207.4-218.7" *)
  sky130_fd_sc_hd__dfrtp_1 _36_ (
    .CLK(clk),
    .D(_02_),
    .Q(sr_reg[4]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:207.4-218.7" *)
  sky130_fd_sc_hd__dfrtp_1 _37_ (
    .CLK(clk),
    .D(_01_),
    .Q(sr_reg[5]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:207.4-218.7" *)
  sky130_fd_sc_hd__dfrtp_1 _38_ (
    .CLK(clk),
    .D(_00_),
    .Q(sr_reg[6]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:207.4-218.7" *)
  sky130_fd_sc_hd__dfrtp_1 _39_ (
    .CLK(clk),
    .D(_07_),
    .Q(sr_reg[7]),
    .RESET_B(resetb)
  );
  assign din = sr_reg[7];
endmodule

(* dynports =  1  *)
(* hdlname = "sro" *)
(* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:221.1-248.10" *)
module \$paramod\sro\DATA_WIDTH=s32'00000000000000000000000000001000 (clk, resetb, shift, dout, datao);
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:225.15-225.18" *)
  input clk;
  wire clk;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:226.15-226.21" *)
  input resetb;
  wire resetb;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:227.15-227.20" *)
  input shift;
  wire shift;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:228.15-228.19" *)
  input dout;
  wire dout;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:229.32-229.37" *)
  output [7:0] datao;
  wire [7:0] datao;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:231.28-231.34" *)
  wire dout_s;
  sky130_fd_sc_hd__mux2_1 _08_ (
    .A0(datao[6]),
    .A1(datao[5]),
    .S(shift),
    .X(_00_)
  );
  sky130_fd_sc_hd__mux2_1 _09_ (
    .A0(datao[5]),
    .A1(datao[4]),
    .S(shift),
    .X(_01_)
  );
  sky130_fd_sc_hd__mux2_1 _10_ (
    .A0(datao[4]),
    .A1(datao[3]),
    .S(shift),
    .X(_02_)
  );
  sky130_fd_sc_hd__mux2_1 _11_ (
    .A0(datao[3]),
    .A1(datao[2]),
    .S(shift),
    .X(_03_)
  );
  sky130_fd_sc_hd__mux2_1 _12_ (
    .A0(datao[2]),
    .A1(datao[1]),
    .S(shift),
    .X(_04_)
  );
  sky130_fd_sc_hd__mux2_1 _13_ (
    .A0(datao[1]),
    .A1(datao[0]),
    .S(shift),
    .X(_05_)
  );
  sky130_fd_sc_hd__mux2_1 _14_ (
    .A0(datao[0]),
    .A1(dout_s),
    .S(shift),
    .X(_06_)
  );
  sky130_fd_sc_hd__mux2_1 _15_ (
    .A0(datao[7]),
    .A1(datao[6]),
    .S(shift),
    .X(_07_)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:236.4-247.7" *)
  sky130_fd_sc_hd__dfrtp_1 _16_ (
    .CLK(clk),
    .D(_06_),
    .Q(datao[0]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:236.4-247.7" *)
  sky130_fd_sc_hd__dfrtp_1 _17_ (
    .CLK(clk),
    .D(_05_),
    .Q(datao[1]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:236.4-247.7" *)
  sky130_fd_sc_hd__dfrtp_1 _18_ (
    .CLK(clk),
    .D(_04_),
    .Q(datao[2]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:236.4-247.7" *)
  sky130_fd_sc_hd__dfrtp_1 _19_ (
    .CLK(clk),
    .D(_03_),
    .Q(datao[3]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:236.4-247.7" *)
  sky130_fd_sc_hd__dfrtp_1 _20_ (
    .CLK(clk),
    .D(_02_),
    .Q(datao[4]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:236.4-247.7" *)
  sky130_fd_sc_hd__dfrtp_1 _21_ (
    .CLK(clk),
    .D(_01_),
    .Q(datao[5]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:236.4-247.7" *)
  sky130_fd_sc_hd__dfrtp_1 _22_ (
    .CLK(clk),
    .D(_00_),
    .Q(datao[6]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:236.4-247.7" *)
  sky130_fd_sc_hd__dfrtp_1 _23_ (
    .CLK(clk),
    .D(_07_),
    .Q(datao[7]),
    .RESET_B(resetb)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/spi_master.v:236.4-247.7" *)
  sky130_fd_sc_hd__dfrtp_1 _24_ (
    .CLK(clk),
    .D(dout),
    .Q(dout_s),
    .RESET_B(resetb)
  );
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:25.1-294.10" *)
module EF_SPI_APB(PCLK, PRESETn, PWRITE, PWDATA, PADDR, PENABLE, PSEL, PREADY, PRDATA, IRQ, miso, mosi, csb, sclk);
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:30.25-30.29" *)
  input PCLK;
  wire PCLK;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:31.25-31.32" *)
  input PRESETn;
  wire PRESETn;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:32.25-32.31" *)
  input PWRITE;
  wire PWRITE;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:33.25-33.31" *)
  input [31:0] PWDATA;
  wire [31:0] PWDATA;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:34.25-34.30" *)
  input [31:0] PADDR;
  wire [31:0] PADDR;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:35.25-35.32" *)
  input PENABLE;
  wire PENABLE;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:36.25-36.29" *)
  input PSEL;
  wire PSEL;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:37.25-37.31" *)
  output PREADY;
  wire PREADY;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:38.25-38.31" *)
  output [31:0] PRDATA;
  wire [31:0] PRDATA;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:39.25-39.28" *)
  output IRQ;
  wire IRQ;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:40.25-40.29" *)
  input [0:0] miso;
  wire [0:0] miso;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:41.25-41.29" *)
  output [0:0] mosi;
  wire [0:0] mosi;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:42.25-42.28" *)
  output [0:0] csb;
  wire [0:0] csb;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:43.25-43.29" *)
  output [0:0] sclk;
  wire [0:0] sclk;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:190.3-193.25" *)
  wire [5:0] _000_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:153.3-157.56" *)
  wire _001_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:171.3-175.56" *)
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:110.18-110.25" *)
  wire [1:0] CFG_REG;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:83.18-83.22" *)
  wire [0:0] CPHA;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:82.18-82.22" *)
  wire [0:0] CPOL;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:117.13-117.21" *)
  wire [2:0] CTRL_REG;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:63.13-63.21" *)
  wire [0:0] GCLK_REG;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:183.16-183.22" *)
  wire [5:0] IC_REG;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:182.16-182.22" *)
  wire [5:0] IM_REG;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:125.17-125.23" *)
  wire [7:0] PR_REG;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:184.16-184.23" *)
  wire [5:0] RIS_REG;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:200.14-200.17" *)
  wire [0:0] RXA;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:108.18-108.29" *)
  wire [7:0] RXDATA_WIRE;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:197.14-197.17" *)
  wire [0:0] RXE;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:198.14-198.17" *)
  wire [0:0] RXF;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:151.13-151.30" *)
  wire [0:0] RX_FIFO_FLUSH_REG;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:141.18-141.36" *)
  wire [3:0] RX_FIFO_LEVEL_WIRE;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:144.17-144.38" *)
  wire [3:0] RX_FIFO_THRESHOLD_REG;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:131.16-131.27" *)
  wire [7:0] STATUS_WIRE;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:199.14-199.17" *)
  wire [0:0] TXB;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:195.14-195.17" *)
  wire [0:0] TXE;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:196.14-196.17" *)
  wire [0:0] TXF;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:169.13-169.30" *)
  wire [0:0] TX_FIFO_FLUSH_REG;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:159.18-159.36" *)
  wire [3:0] TX_FIFO_LEVEL_WIRE;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:162.17-162.38" *)
  wire [3:0] TX_FIFO_THRESHOLD_REG;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:105.18-105.22" *)
  wire [0:0] busy;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:75.18-75.21" *)
  wire clk;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:84.18-84.29" *)
  wire [7:0] clk_divider;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:64.8-64.13" *)
  wire clk_g;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:66.8-66.20" *)
  wire clk_gated_en;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:87.18-87.23" *)
  wire [7:0] datai;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:88.18-88.23" *)
  wire [7:0] datao;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:104.18-104.22" *)
  wire [0:0] done;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:103.18-103.24" *)
  wire [0:0] enable;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:86.18-86.20" *)
  wire [0:0] rd;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:76.18-76.23" *)
  wire rst_n;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:92.18-92.26" *)
  wire [0:0] rx_empty;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:89.18-89.23" *)
  wire [0:0] rx_en;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:90.18-90.26" *)
  wire [0:0] rx_flush;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:93.18-93.25" *)
  wire [0:0] rx_full;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:95.18-95.26" *)
  wire [3:0] rx_level;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:94.18-94.32" *)
  wire [0:0] rx_level_above;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:91.18-91.30" *)
  wire [3:0] rx_threshold;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:102.18-102.20" *)
  wire [0:0] ss;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:98.18-98.26" *)
  wire [0:0] tx_empty;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:96.18-96.26" *)
  wire [0:0] tx_flush;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:99.18-99.25" *)
  wire [0:0] tx_full;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:101.18-101.26" *)
  wire [3:0] tx_level;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:100.18-100.32" *)
  wire [0:0] tx_level_below;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:97.18-97.30" *)
  wire [3:0] tx_threshold;
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:85.18-85.20" *)
  wire [0:0] wr;
  sky130_fd_sc_hd__clkinv_1 _196_ (
    .A(PADDR[8]),
    .Y(_037_)
  );
  sky130_fd_sc_hd__nor4_1 _197_ (
    .A(PADDR[6]),
    .B(PADDR[7]),
    .C(PADDR[5]),
    .D(PADDR[4]),
    .Y(_038_)
  );
  sky130_fd_sc_hd__nor2_1 _198_ (
    .A(PADDR[0]),
    .B(PADDR[1]),
    .Y(_039_)
  );
  sky130_fd_sc_hd__nand2_1 _199_ (
    .A(PADDR[2]),
    .B(PADDR[3]),
    .Y(_040_)
  );
  sky130_fd_sc_hd__nand4_1 _200_ (
    .A(PADDR[2]),
    .B(PADDR[3]),
    .C(_038_),
    .D(_039_),
    .Y(_041_)
  );
  sky130_fd_sc_hd__nand4_1 _201_ (
    .A(PADDR[10]),
    .B(PADDR[11]),
    .C(PADDR[13]),
    .D(PADDR[15]),
    .Y(_042_)
  );
  sky130_fd_sc_hd__nand3_1 _202_ (
    .A(PADDR[14]),
    .B(PADDR[9]),
    .C(PADDR[12]),
    .Y(_043_)
  );
  sky130_fd_sc_hd__or3_1 _203_ (
    .A(_037_),
    .B(_042_),
    .C(_043_),
    .X(_044_)
  );
  sky130_fd_sc_hd__nand2_1 _204_ (
    .A(PSEL),
    .B(PENABLE),
    .Y(_045_)
  );
  sky130_fd_sc_hd__and3_1 _205_ (
    .A(PWRITE),
    .B(PSEL),
    .C(PENABLE),
    .X(_046_)
  );
  sky130_fd_sc_hd__nand3_1 _206_ (
    .A(PWRITE),
    .B(PSEL),
    .C(PENABLE),
    .Y(_047_)
  );
  sky130_fd_sc_hd__nor3_1 _207_ (
    .A(_041_),
    .B(_044_),
    .C(_047_),
    .Y(_048_)
  );
  sky130_fd_sc_hd__and2_0 _208_ (
    .A(PWDATA[1]),
    .B(_048_),
    .X(_000_[1])
  );
  sky130_fd_sc_hd__and2_0 _209_ (
    .A(PWDATA[0]),
    .B(_048_),
    .X(_000_[0])
  );
  sky130_fd_sc_hd__nor4_1 _210_ (
    .A(PADDR[2]),
    .B(PADDR[3]),
    .C(PADDR[0]),
    .D(PADDR[1]),
    .Y(_049_)
  );
  sky130_fd_sc_hd__nand2_1 _211_ (
    .A(_038_),
    .B(_049_),
    .Y(_050_)
  );
  sky130_fd_sc_hd__nor4_1 _212_ (
    .A(PADDR[9]),
    .B(PADDR[13]),
    .C(PADDR[12]),
    .D(PADDR[15]),
    .Y(_051_)
  );
  sky130_fd_sc_hd__nor4_1 _213_ (
    .A(PADDR[8]),
    .B(PADDR[14]),
    .C(PADDR[10]),
    .D(PADDR[11]),
    .Y(_052_)
  );
  sky130_fd_sc_hd__nand2_1 _214_ (
    .A(_051_),
    .B(_052_),
    .Y(_053_)
  );
  sky130_fd_sc_hd__nor2_1 _215_ (
    .A(_050_),
    .B(_053_),
    .Y(_054_)
  );
  sky130_fd_sc_hd__nand2_1 _216_ (
    .A(datao[7]),
    .B(_054_),
    .Y(_055_)
  );
  sky130_fd_sc_hd__nor2_1 _217_ (
    .A(_041_),
    .B(_053_),
    .Y(_056_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _218_ (
    .A(_041_),
    .SLEEP(_053_),
    .X(_057_)
  );
  sky130_fd_sc_hd__nand4b_1 _219_ (
    .A_N(PADDR[2]),
    .B(PADDR[3]),
    .C(_038_),
    .D(_039_),
    .Y(_058_)
  );
  sky130_fd_sc_hd__nor2_1 _220_ (
    .A(_053_),
    .B(_058_),
    .Y(_059_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _221_ (
    .A(_053_),
    .SLEEP(_058_),
    .X(_060_)
  );
  sky130_fd_sc_hd__nor2_1 _222_ (
    .A(_054_),
    .B(_059_),
    .Y(_061_)
  );
  sky130_fd_sc_hd__nor3_1 _223_ (
    .A(_054_),
    .B(_056_),
    .C(_059_),
    .Y(_062_)
  );
  sky130_fd_sc_hd__nand2_1 _224_ (
    .A(_057_),
    .B(_061_),
    .Y(_063_)
  );
  sky130_fd_sc_hd__or4b_1 _225_ (
    .A(PADDR[6]),
    .B(PADDR[7]),
    .C(PADDR[5]),
    .D_N(PADDR[4]),
    .X(_064_)
  );
  sky130_fd_sc_hd__clkinv_1 _226_ (
    .A(_064_),
    .Y(_065_)
  );
  sky130_fd_sc_hd__nand2_1 _227_ (
    .A(_049_),
    .B(_065_),
    .Y(_066_)
  );
  sky130_fd_sc_hd__nor2_1 _228_ (
    .A(_053_),
    .B(_066_),
    .Y(_067_)
  );
  sky130_fd_sc_hd__nand4_1 _229_ (
    .A(_049_),
    .B(_051_),
    .C(_052_),
    .D(_065_),
    .Y(_068_)
  );
  sky130_fd_sc_hd__nor4b_1 _230_ (
    .A(PADDR[3]),
    .B(PADDR[0]),
    .C(PADDR[1]),
    .D_N(PADDR[2]),
    .Y(_069_)
  );
  sky130_fd_sc_hd__nand3b_1 _231_ (
    .A_N(PADDR[3]),
    .B(_039_),
    .C(PADDR[2]),
    .Y(_070_)
  );
  sky130_fd_sc_hd__nor3_1 _232_ (
    .A(_053_),
    .B(_064_),
    .C(_070_),
    .Y(_071_)
  );
  sky130_fd_sc_hd__nand2_1 _233_ (
    .A(done),
    .B(_071_),
    .Y(_072_)
  );
  sky130_fd_sc_hd__nor3_1 _234_ (
    .A(PADDR[8]),
    .B(_042_),
    .C(_043_),
    .Y(_073_)
  );
  sky130_fd_sc_hd__or3_1 _235_ (
    .A(PADDR[8]),
    .B(_042_),
    .C(_043_),
    .X(_074_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _236_ (
    .A(_058_),
    .SLEEP(_074_),
    .X(_075_)
  );
  sky130_fd_sc_hd__nand2_1 _237_ (
    .A(_038_),
    .B(_069_),
    .Y(_076_)
  );
  sky130_fd_sc_hd__nor2_1 _238_ (
    .A(_074_),
    .B(_076_),
    .Y(_077_)
  );
  sky130_fd_sc_hd__nand3_1 _239_ (
    .A(_038_),
    .B(_069_),
    .C(_073_),
    .Y(_078_)
  );
  sky130_fd_sc_hd__nand2_1 _240_ (
    .A(_075_),
    .B(_078_),
    .Y(_079_)
  );
  sky130_fd_sc_hd__nor2_1 _241_ (
    .A(_050_),
    .B(_074_),
    .Y(_080_)
  );
  sky130_fd_sc_hd__nand3_1 _242_ (
    .A(_038_),
    .B(_049_),
    .C(_073_),
    .Y(_081_)
  );
  sky130_fd_sc_hd__nor3_1 _243_ (
    .A(_071_),
    .B(_079_),
    .C(_080_),
    .Y(_082_)
  );
  sky130_fd_sc_hd__nor4_1 _244_ (
    .A(PADDR[8]),
    .B(_042_),
    .C(_043_),
    .D(_064_),
    .Y(_083_)
  );
  sky130_fd_sc_hd__nand3_1 _245_ (
    .A(_039_),
    .B(_040_),
    .C(_083_),
    .Y(_084_)
  );
  sky130_fd_sc_hd__nor2_1 _246_ (
    .A(_044_),
    .B(_058_),
    .Y(_085_)
  );
  sky130_fd_sc_hd__a21oi_1 _247_ (
    .A1(_058_),
    .A2(_066_),
    .B1(_044_),
    .Y(_086_)
  );
  sky130_fd_sc_hd__nor2_1 _248_ (
    .A(_044_),
    .B(_076_),
    .Y(_087_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _249_ (
    .A(_044_),
    .SLEEP(_076_),
    .X(_088_)
  );
  sky130_fd_sc_hd__nor2_1 _250_ (
    .A(_044_),
    .B(_050_),
    .Y(_089_)
  );
  sky130_fd_sc_hd__lpflow_inputiso1p_1 _251_ (
    .A(_044_),
    .SLEEP(_050_),
    .X(_090_)
  );
  sky130_fd_sc_hd__nor3_1 _252_ (
    .A(_086_),
    .B(_087_),
    .C(_089_),
    .Y(_091_)
  );
  sky130_fd_sc_hd__nand3_1 _253_ (
    .A(_082_),
    .B(_084_),
    .C(_091_),
    .Y(_092_)
  );
  sky130_fd_sc_hd__a21oi_1 _254_ (
    .A1(_072_),
    .A2(_092_),
    .B1(_067_),
    .Y(_093_)
  );
  sky130_fd_sc_hd__a21oi_1 _255_ (
    .A1(PR_REG[7]),
    .A2(_067_),
    .B1(_093_),
    .Y(_094_)
  );
  sky130_fd_sc_hd__nor2_1 _256_ (
    .A(_063_),
    .B(_067_),
    .Y(_095_)
  );
  sky130_fd_sc_hd__a21oi_1 _257_ (
    .A1(_058_),
    .A2(_066_),
    .B1(_044_),
    .Y(_096_)
  );
  sky130_fd_sc_hd__nand4b_1 _258_ (
    .A_N(PADDR[2]),
    .B(PADDR[3]),
    .C(_039_),
    .D(_083_),
    .Y(_097_)
  );
  sky130_fd_sc_hd__o21ai_0 _259_ (
    .A1(_063_),
    .A2(_094_),
    .B1(_055_),
    .Y(PRDATA[7])
  );
  sky130_fd_sc_hd__nand2_1 _260_ (
    .A(datao[6]),
    .B(_054_),
    .Y(_098_)
  );
  sky130_fd_sc_hd__nand2_1 _261_ (
    .A(busy),
    .B(_071_),
    .Y(_099_)
  );
  sky130_fd_sc_hd__a21oi_1 _262_ (
    .A1(_092_),
    .A2(_099_),
    .B1(_067_),
    .Y(_100_)
  );
  sky130_fd_sc_hd__a21oi_1 _263_ (
    .A1(PR_REG[6]),
    .A2(_067_),
    .B1(_100_),
    .Y(_101_)
  );
  sky130_fd_sc_hd__o21ai_0 _264_ (
    .A1(_063_),
    .A2(_101_),
    .B1(_098_),
    .Y(PRDATA[6])
  );
  sky130_fd_sc_hd__nand2_1 _265_ (
    .A(datao[5]),
    .B(_054_),
    .Y(_102_)
  );
  sky130_fd_sc_hd__o21ai_0 _266_ (
    .A1(PR_REG[5]),
    .A2(_068_),
    .B1(_062_),
    .Y(_103_)
  );
  sky130_fd_sc_hd__nand2_1 _267_ (
    .A(IM_REG[5]),
    .B(RIS_REG[5]),
    .Y(_104_)
  );
  sky130_fd_sc_hd__nand2_1 _268_ (
    .A(RIS_REG[5]),
    .B(_085_),
    .Y(_105_)
  );
  sky130_fd_sc_hd__o211ai_1 _269_ (
    .A1(IM_REG[5]),
    .A2(_090_),
    .B1(_084_),
    .C1(_082_),
    .Y(_106_)
  );
  sky130_fd_sc_hd__a221oi_1 _270_ (
    .A1(_087_),
    .A2(_104_),
    .B1(_105_),
    .B2(_086_),
    .C1(_106_),
    .Y(_107_)
  );
  sky130_fd_sc_hd__a211oi_1 _271_ (
    .A1(rx_level_above),
    .A2(_071_),
    .B1(_107_),
    .C1(_067_),
    .Y(_108_)
  );
  sky130_fd_sc_hd__o21ai_0 _272_ (
    .A1(_103_),
    .A2(_108_),
    .B1(_102_),
    .Y(PRDATA[5])
  );
  sky130_fd_sc_hd__a22oi_1 _273_ (
    .A1(RIS_REG[4]),
    .A2(_085_),
    .B1(_089_),
    .B2(IM_REG[4]),
    .Y(_109_)
  );
  sky130_fd_sc_hd__a32oi_1 _274_ (
    .A1(RIS_REG[4]),
    .A2(IM_REG[4]),
    .A3(_087_),
    .B1(_054_),
    .B2(datao[4]),
    .Y(_110_)
  );
  sky130_fd_sc_hd__a22oi_1 _275_ (
    .A1(PR_REG[4]),
    .A2(_067_),
    .B1(_071_),
    .B2(tx_level_below),
    .Y(_111_)
  );
  sky130_fd_sc_hd__nand3_1 _276_ (
    .A(_109_),
    .B(_110_),
    .C(_111_),
    .Y(PRDATA[4])
  );
  sky130_fd_sc_hd__nand2b_1 _277_ (
    .A_N(rx_full),
    .B(_071_),
    .Y(_112_)
  );
  sky130_fd_sc_hd__a21oi_1 _278_ (
    .A1(rx_level[3]),
    .A2(_080_),
    .B1(_071_),
    .Y(_113_)
  );
  sky130_fd_sc_hd__nand2_1 _279_ (
    .A(RX_FIFO_THRESHOLD_REG[3]),
    .B(_077_),
    .Y(_114_)
  );
  sky130_fd_sc_hd__nor2_1 _280_ (
    .A(_066_),
    .B(_074_),
    .Y(_115_)
  );
  sky130_fd_sc_hd__nand3_1 _281_ (
    .A(_049_),
    .B(_065_),
    .C(_073_),
    .Y(_116_)
  );
  sky130_fd_sc_hd__nor3_1 _282_ (
    .A(_064_),
    .B(_070_),
    .C(_074_),
    .Y(_117_)
  );
  sky130_fd_sc_hd__nand2_1 _283_ (
    .A(_069_),
    .B(_083_),
    .Y(_118_)
  );
  sky130_fd_sc_hd__nand2_1 _284_ (
    .A(_097_),
    .B(_118_),
    .Y(_119_)
  );
  sky130_fd_sc_hd__nand2_1 _285_ (
    .A(RIS_REG[3]),
    .B(_085_),
    .Y(_120_)
  );
  sky130_fd_sc_hd__a21oi_1 _286_ (
    .A1(IM_REG[3]),
    .A2(RIS_REG[3]),
    .B1(_088_),
    .Y(_121_)
  );
  sky130_fd_sc_hd__nor2_1 _287_ (
    .A(tx_level[3]),
    .B(_116_),
    .Y(_122_)
  );
  sky130_fd_sc_hd__nor2_1 _288_ (
    .A(IM_REG[3]),
    .B(_090_),
    .Y(_123_)
  );
  sky130_fd_sc_hd__nor3_1 _289_ (
    .A(_064_),
    .B(_070_),
    .C(_074_),
    .Y(_124_)
  );
  sky130_fd_sc_hd__a2111oi_0 _290_ (
    .A1(_086_),
    .A2(_120_),
    .B1(_121_),
    .C1(_123_),
    .D1(_119_),
    .Y(_125_)
  );
  sky130_fd_sc_hd__a211oi_1 _291_ (
    .A1(TX_FIFO_THRESHOLD_REG[3]),
    .A2(_117_),
    .B1(_125_),
    .C1(_115_),
    .Y(_126_)
  );
  sky130_fd_sc_hd__o31a_1 _292_ (
    .A1(_079_),
    .A2(_122_),
    .A3(_126_),
    .B1(_114_),
    .X(_127_)
  );
  sky130_fd_sc_hd__o21ai_0 _293_ (
    .A1(_080_),
    .A2(_127_),
    .B1(_113_),
    .Y(_128_)
  );
  sky130_fd_sc_hd__nand2_1 _294_ (
    .A(PR_REG[3]),
    .B(_067_),
    .Y(_129_)
  );
  sky130_fd_sc_hd__a32oi_1 _295_ (
    .A1(_095_),
    .A2(_112_),
    .A3(_128_),
    .B1(_054_),
    .B2(datao[3]),
    .Y(_130_)
  );
  sky130_fd_sc_hd__nand2_1 _296_ (
    .A(_129_),
    .B(_130_),
    .Y(PRDATA[3])
  );
  sky130_fd_sc_hd__a21oi_1 _297_ (
    .A1(CTRL_REG[2]),
    .A2(_061_),
    .B1(_062_),
    .Y(_131_)
  );
  sky130_fd_sc_hd__a21oi_1 _298_ (
    .A1(PR_REG[2]),
    .A2(_067_),
    .B1(_056_),
    .Y(_132_)
  );
  sky130_fd_sc_hd__a21oi_1 _299_ (
    .A1(RX_FIFO_THRESHOLD_REG[2]),
    .A2(_077_),
    .B1(_080_),
    .Y(_133_)
  );
  sky130_fd_sc_hd__a21oi_1 _300_ (
    .A1(IM_REG[2]),
    .A2(RIS_REG[2]),
    .B1(_088_),
    .Y(_134_)
  );
  sky130_fd_sc_hd__nand2_1 _301_ (
    .A(RIS_REG[2]),
    .B(_085_),
    .Y(_135_)
  );
  sky130_fd_sc_hd__nor2_1 _302_ (
    .A(IM_REG[2]),
    .B(_090_),
    .Y(_136_)
  );
  sky130_fd_sc_hd__a2111oi_0 _303_ (
    .A1(_086_),
    .A2(_135_),
    .B1(_136_),
    .C1(_119_),
    .D1(_134_),
    .Y(_137_)
  );
  sky130_fd_sc_hd__a211oi_1 _304_ (
    .A1(TX_FIFO_THRESHOLD_REG[2]),
    .A2(_117_),
    .B1(_137_),
    .C1(_115_),
    .Y(_138_)
  );
  sky130_fd_sc_hd__nor2_1 _305_ (
    .A(tx_level[2]),
    .B(_116_),
    .Y(_139_)
  );
  sky130_fd_sc_hd__o31ai_1 _306_ (
    .A1(_079_),
    .A2(_138_),
    .A3(_139_),
    .B1(_133_),
    .Y(_140_)
  );
  sky130_fd_sc_hd__nand2b_1 _307_ (
    .A_N(rx_empty),
    .B(_071_),
    .Y(_141_)
  );
  sky130_fd_sc_hd__o2111ai_1 _308_ (
    .A1(rx_level[2]),
    .A2(_081_),
    .B1(_140_),
    .C1(_141_),
    .D1(_068_),
    .Y(_142_)
  );
  sky130_fd_sc_hd__a21oi_1 _309_ (
    .A1(_132_),
    .A2(_142_),
    .B1(_131_),
    .Y(_143_)
  );
  sky130_fd_sc_hd__a21o_1 _310_ (
    .A1(datao[2]),
    .A2(_054_),
    .B1(_143_),
    .X(PRDATA[2])
  );
  sky130_fd_sc_hd__nor2_1 _311_ (
    .A(CFG_REG[1]),
    .B(_060_),
    .Y(_144_)
  );
  sky130_fd_sc_hd__nor2_1 _312_ (
    .A(_054_),
    .B(_144_),
    .Y(_145_)
  );
  sky130_fd_sc_hd__a21oi_1 _313_ (
    .A1(CTRL_REG[1]),
    .A2(_056_),
    .B1(_059_),
    .Y(_146_)
  );
  sky130_fd_sc_hd__o21ai_0 _314_ (
    .A1(PR_REG[1]),
    .A2(_068_),
    .B1(_057_),
    .Y(_147_)
  );
  sky130_fd_sc_hd__a21oi_1 _315_ (
    .A1(RX_FIFO_THRESHOLD_REG[1]),
    .A2(_077_),
    .B1(_080_),
    .Y(_148_)
  );
  sky130_fd_sc_hd__a21oi_1 _316_ (
    .A1(IM_REG[1]),
    .A2(RIS_REG[1]),
    .B1(_088_),
    .Y(_149_)
  );
  sky130_fd_sc_hd__nand2_1 _317_ (
    .A(RIS_REG[1]),
    .B(_085_),
    .Y(_150_)
  );
  sky130_fd_sc_hd__nor2_1 _318_ (
    .A(IM_REG[1]),
    .B(_090_),
    .Y(_151_)
  );
  sky130_fd_sc_hd__a2111oi_0 _319_ (
    .A1(_086_),
    .A2(_150_),
    .B1(_151_),
    .C1(_119_),
    .D1(_149_),
    .Y(_152_)
  );
  sky130_fd_sc_hd__a211oi_1 _320_ (
    .A1(TX_FIFO_THRESHOLD_REG[1]),
    .A2(_117_),
    .B1(_152_),
    .C1(_115_),
    .Y(_153_)
  );
  sky130_fd_sc_hd__nor2_1 _321_ (
    .A(tx_level[1]),
    .B(_116_),
    .Y(_154_)
  );
  sky130_fd_sc_hd__o31ai_1 _322_ (
    .A1(_079_),
    .A2(_153_),
    .A3(_154_),
    .B1(_148_),
    .Y(_155_)
  );
  sky130_fd_sc_hd__nor2_1 _323_ (
    .A(rx_level[1]),
    .B(_081_),
    .Y(_156_)
  );
  sky130_fd_sc_hd__nor2_1 _324_ (
    .A(_071_),
    .B(_156_),
    .Y(_157_)
  );
  sky130_fd_sc_hd__a221oi_1 _325_ (
    .A1(tx_full),
    .A2(_071_),
    .B1(_155_),
    .B2(_157_),
    .C1(_067_),
    .Y(_158_)
  );
  sky130_fd_sc_hd__o21ai_0 _326_ (
    .A1(_147_),
    .A2(_158_),
    .B1(_146_),
    .Y(_159_)
  );
  sky130_fd_sc_hd__a22o_1 _327_ (
    .A1(datao[1]),
    .A2(_054_),
    .B1(_145_),
    .B2(_159_),
    .X(PRDATA[1])
  );
  sky130_fd_sc_hd__nor3_1 _328_ (
    .A(datao[0]),
    .B(_050_),
    .C(_053_),
    .Y(_160_)
  );
  sky130_fd_sc_hd__nand2_1 _329_ (
    .A(PR_REG[0]),
    .B(_067_),
    .Y(_161_)
  );
  sky130_fd_sc_hd__nand2_1 _330_ (
    .A(_057_),
    .B(_161_),
    .Y(_162_)
  );
  sky130_fd_sc_hd__mux2i_1 _331_ (
    .A0(GCLK_REG),
    .A1(RIS_REG[0]),
    .S(_085_),
    .Y(_163_)
  );
  sky130_fd_sc_hd__a21oi_1 _332_ (
    .A1(RIS_REG[0]),
    .A2(IM_REG[0]),
    .B1(_088_),
    .Y(_164_)
  );
  sky130_fd_sc_hd__nand2_1 _333_ (
    .A(IM_REG[0]),
    .B(_089_),
    .Y(_165_)
  );
  sky130_fd_sc_hd__nor2_1 _334_ (
    .A(TX_FIFO_FLUSH_REG),
    .B(_097_),
    .Y(_166_)
  );
  sky130_fd_sc_hd__nand2_1 _335_ (
    .A(CFG_REG[0]),
    .B(_059_),
    .Y(_167_)
  );
  sky130_fd_sc_hd__o41ai_1 _336_ (
    .A1(tx_empty),
    .A2(_053_),
    .A3(_064_),
    .A4(_070_),
    .B1(_068_),
    .Y(_168_)
  );
  sky130_fd_sc_hd__nor2_1 _337_ (
    .A(rx_level[0]),
    .B(_081_),
    .Y(_169_)
  );
  sky130_fd_sc_hd__nor2_1 _338_ (
    .A(RX_FIFO_THRESHOLD_REG[0]),
    .B(_078_),
    .Y(_170_)
  );
  sky130_fd_sc_hd__nand3b_1 _339_ (
    .A_N(tx_level[0]),
    .B(_049_),
    .C(_083_),
    .Y(_171_)
  );
  sky130_fd_sc_hd__a211o_1 _340_ (
    .A1(_096_),
    .A2(_163_),
    .B1(_164_),
    .C1(_089_),
    .X(_172_)
  );
  sky130_fd_sc_hd__a311oi_1 _341_ (
    .A1(_097_),
    .A2(_165_),
    .A3(_172_),
    .B1(_166_),
    .C1(_124_),
    .Y(_173_)
  );
  sky130_fd_sc_hd__a22o_1 _342_ (
    .A1(_049_),
    .A2(_083_),
    .B1(_124_),
    .B2(TX_FIFO_THRESHOLD_REG[0]),
    .X(_174_)
  );
  sky130_fd_sc_hd__o221ai_1 _343_ (
    .A1(RX_FIFO_FLUSH_REG),
    .A2(_075_),
    .B1(_173_),
    .B2(_174_),
    .C1(_171_),
    .Y(_175_)
  );
  sky130_fd_sc_hd__nor4_1 _344_ (
    .A(_168_),
    .B(_169_),
    .C(_170_),
    .D(_175_),
    .Y(_176_)
  );
  sky130_fd_sc_hd__o221ai_1 _345_ (
    .A1(CTRL_REG[0]),
    .A2(_057_),
    .B1(_162_),
    .B2(_176_),
    .C1(_060_),
    .Y(_177_)
  );
  sky130_fd_sc_hd__a21oi_1 _346_ (
    .A1(_167_),
    .A2(_177_),
    .B1(_160_),
    .Y(PRDATA[0])
  );
  sky130_fd_sc_hd__nor3_1 _347_ (
    .A(_063_),
    .B(_067_),
    .C(_092_),
    .Y(PRDATA[9])
  );
  sky130_fd_sc_hd__nand2_1 _348_ (
    .A(_046_),
    .B(_059_),
    .Y(_178_)
  );
  sky130_fd_sc_hd__nand2_1 _349_ (
    .A(PWDATA[0]),
    .B(_046_),
    .Y(_179_)
  );
  sky130_fd_sc_hd__o2bb2ai_1 _350_ (
    .A1_N(CFG_REG[0]),
    .A2_N(_178_),
    .B1(_179_),
    .B2(_060_),
    .Y(_003_)
  );
  sky130_fd_sc_hd__nand2_1 _351_ (
    .A(_046_),
    .B(_056_),
    .Y(_180_)
  );
  sky130_fd_sc_hd__mux2_1 _352_ (
    .A0(PWDATA[1]),
    .A1(CTRL_REG[1]),
    .S(_180_),
    .X(_004_)
  );
  sky130_fd_sc_hd__nand2_1 _353_ (
    .A(CTRL_REG[0]),
    .B(_180_),
    .Y(_181_)
  );
  sky130_fd_sc_hd__o21ai_0 _354_ (
    .A1(_057_),
    .A2(_179_),
    .B1(_181_),
    .Y(_005_)
  );
  sky130_fd_sc_hd__nand2_1 _355_ (
    .A(_046_),
    .B(_117_),
    .Y(_182_)
  );
  sky130_fd_sc_hd__mux2_1 _356_ (
    .A0(PWDATA[2]),
    .A1(TX_FIFO_THRESHOLD_REG[2]),
    .S(_182_),
    .X(_006_)
  );
  sky130_fd_sc_hd__mux2_1 _357_ (
    .A0(PWDATA[1]),
    .A1(TX_FIFO_THRESHOLD_REG[1]),
    .S(_182_),
    .X(_007_)
  );
  sky130_fd_sc_hd__mux2_1 _358_ (
    .A0(PWDATA[0]),
    .A1(TX_FIFO_THRESHOLD_REG[0]),
    .S(_182_),
    .X(_008_)
  );
  sky130_fd_sc_hd__nand2_1 _359_ (
    .A(_046_),
    .B(_089_),
    .Y(_183_)
  );
  sky130_fd_sc_hd__mux2_1 _360_ (
    .A0(PWDATA[4]),
    .A1(IM_REG[4]),
    .S(_183_),
    .X(_009_)
  );
  sky130_fd_sc_hd__mux2_1 _361_ (
    .A0(PWDATA[3]),
    .A1(IM_REG[3]),
    .S(_183_),
    .X(_010_)
  );
  sky130_fd_sc_hd__mux2_1 _362_ (
    .A0(PWDATA[2]),
    .A1(IM_REG[2]),
    .S(_183_),
    .X(_011_)
  );
  sky130_fd_sc_hd__mux2_1 _363_ (
    .A0(PWDATA[1]),
    .A1(IM_REG[1]),
    .S(_183_),
    .X(_012_)
  );
  sky130_fd_sc_hd__nand2_1 _364_ (
    .A(IM_REG[0]),
    .B(_183_),
    .Y(_184_)
  );
  sky130_fd_sc_hd__o21ai_0 _365_ (
    .A1(_090_),
    .A2(_179_),
    .B1(_184_),
    .Y(_013_)
  );
  sky130_fd_sc_hd__nor3_1 _366_ (
    .A(_047_),
    .B(_053_),
    .C(_066_),
    .Y(_185_)
  );
  sky130_fd_sc_hd__mux2_1 _367_ (
    .A0(PR_REG[6]),
    .A1(PWDATA[6]),
    .S(_185_),
    .X(_014_)
  );
  sky130_fd_sc_hd__mux2_1 _368_ (
    .A0(PR_REG[5]),
    .A1(PWDATA[5]),
    .S(_185_),
    .X(_015_)
  );
  sky130_fd_sc_hd__mux2_1 _369_ (
    .A0(PR_REG[4]),
    .A1(PWDATA[4]),
    .S(_185_),
    .X(_016_)
  );
  sky130_fd_sc_hd__mux2_1 _370_ (
    .A0(PR_REG[3]),
    .A1(PWDATA[3]),
    .S(_185_),
    .X(_017_)
  );
  sky130_fd_sc_hd__mux2_1 _371_ (
    .A0(PR_REG[2]),
    .A1(PWDATA[2]),
    .S(_185_),
    .X(_018_)
  );
  sky130_fd_sc_hd__mux2_1 _372_ (
    .A0(PR_REG[1]),
    .A1(PWDATA[1]),
    .S(_185_),
    .X(_019_)
  );
  sky130_fd_sc_hd__mux2_1 _373_ (
    .A0(PR_REG[0]),
    .A1(PWDATA[0]),
    .S(_185_),
    .X(_020_)
  );
  sky130_fd_sc_hd__nand2_1 _374_ (
    .A(_046_),
    .B(_077_),
    .Y(_186_)
  );
  sky130_fd_sc_hd__mux2_1 _375_ (
    .A0(PWDATA[2]),
    .A1(RX_FIFO_THRESHOLD_REG[2]),
    .S(_186_),
    .X(_021_)
  );
  sky130_fd_sc_hd__mux2_1 _376_ (
    .A0(PWDATA[1]),
    .A1(RX_FIFO_THRESHOLD_REG[1]),
    .S(_186_),
    .X(_022_)
  );
  sky130_fd_sc_hd__mux2_1 _377_ (
    .A0(PWDATA[0]),
    .A1(RX_FIFO_THRESHOLD_REG[0]),
    .S(_186_),
    .X(_023_)
  );
  sky130_fd_sc_hd__nor2_1 _378_ (
    .A(RIS_REG[0]),
    .B(tx_empty),
    .Y(_187_)
  );
  sky130_fd_sc_hd__nor2_1 _379_ (
    .A(IC_REG[0]),
    .B(_187_),
    .Y(_024_)
  );
  sky130_fd_sc_hd__and2_0 _380_ (
    .A(PWDATA[4]),
    .B(_048_),
    .X(_000_[4])
  );
  sky130_fd_sc_hd__nor2_1 _381_ (
    .A(rx_level_above),
    .B(RIS_REG[5]),
    .Y(_188_)
  );
  sky130_fd_sc_hd__nor2_1 _382_ (
    .A(IC_REG[5]),
    .B(_188_),
    .Y(_025_)
  );
  sky130_fd_sc_hd__nor2_1 _383_ (
    .A(rx_full),
    .B(RIS_REG[3]),
    .Y(_189_)
  );
  sky130_fd_sc_hd__nor2_1 _384_ (
    .A(IC_REG[3]),
    .B(_189_),
    .Y(_026_)
  );
  sky130_fd_sc_hd__nor2_1 _385_ (
    .A(rx_empty),
    .B(RIS_REG[2]),
    .Y(_190_)
  );
  sky130_fd_sc_hd__nor2_1 _386_ (
    .A(IC_REG[2]),
    .B(_190_),
    .Y(_027_)
  );
  sky130_fd_sc_hd__and2_0 _387_ (
    .A(PWDATA[3]),
    .B(_048_),
    .X(_000_[3])
  );
  sky130_fd_sc_hd__and2_0 _388_ (
    .A(PWDATA[2]),
    .B(_048_),
    .X(_000_[2])
  );
  sky130_fd_sc_hd__mux2_1 _389_ (
    .A0(PWDATA[3]),
    .A1(RX_FIFO_THRESHOLD_REG[3]),
    .S(_186_),
    .X(_028_)
  );
  sky130_fd_sc_hd__a22oi_1 _390_ (
    .A1(IM_REG[2]),
    .A2(RIS_REG[2]),
    .B1(RIS_REG[1]),
    .B2(IM_REG[1]),
    .Y(_191_)
  );
  sky130_fd_sc_hd__a222oi_1 _391_ (
    .A1(RIS_REG[4]),
    .A2(IM_REG[4]),
    .B1(IM_REG[3]),
    .B2(RIS_REG[3]),
    .C1(IM_REG[0]),
    .C2(RIS_REG[0]),
    .Y(_192_)
  );
  sky130_fd_sc_hd__nand3_1 _392_ (
    .A(_104_),
    .B(_191_),
    .C(_192_),
    .Y(IRQ)
  );
  sky130_fd_sc_hd__mux2_1 _393_ (
    .A0(PR_REG[7]),
    .A1(PWDATA[7]),
    .S(_185_),
    .X(_029_)
  );
  sky130_fd_sc_hd__mux2_1 _394_ (
    .A0(PWDATA[5]),
    .A1(IM_REG[5]),
    .S(_183_),
    .X(_030_)
  );
  sky130_fd_sc_hd__mux2_1 _395_ (
    .A0(PWDATA[3]),
    .A1(TX_FIFO_THRESHOLD_REG[3]),
    .S(_182_),
    .X(_031_)
  );
  sky130_fd_sc_hd__mux2_1 _396_ (
    .A0(PWDATA[2]),
    .A1(CTRL_REG[2]),
    .S(_180_),
    .X(_032_)
  );
  sky130_fd_sc_hd__nor2_1 _397_ (
    .A(RIS_REG[4]),
    .B(tx_level_below),
    .Y(_193_)
  );
  sky130_fd_sc_hd__nor2_1 _398_ (
    .A(IC_REG[4]),
    .B(_193_),
    .Y(_033_)
  );
  sky130_fd_sc_hd__o31ai_1 _399_ (
    .A1(_044_),
    .A2(_047_),
    .A3(_066_),
    .B1(GCLK_REG),
    .Y(_194_)
  );
  sky130_fd_sc_hd__o31ai_1 _400_ (
    .A1(_044_),
    .A2(_066_),
    .A3(_179_),
    .B1(_194_),
    .Y(_034_)
  );
  sky130_fd_sc_hd__mux2_1 _401_ (
    .A0(PWDATA[1]),
    .A1(CFG_REG[1]),
    .S(_178_),
    .X(_035_)
  );
  sky130_fd_sc_hd__nor2_1 _402_ (
    .A(tx_full),
    .B(RIS_REG[1]),
    .Y(_195_)
  );
  sky130_fd_sc_hd__nor2_1 _403_ (
    .A(IC_REG[1]),
    .B(_195_),
    .Y(_036_)
  );
  sky130_fd_sc_hd__nor2_1 _404_ (
    .A(_075_),
    .B(_179_),
    .Y(_001_)
  );
  sky130_fd_sc_hd__nor4_1 _405_ (
    .A(PWRITE),
    .B(_045_),
    .C(_050_),
    .D(_053_),
    .Y(rd)
  );
  sky130_fd_sc_hd__nor2_1 _406_ (
    .A(_097_),
    .B(_179_),
    .Y(_002_)
  );
  sky130_fd_sc_hd__nor3_1 _407_ (
    .A(_047_),
    .B(_053_),
    .C(_076_),
    .Y(wr)
  );
  sky130_fd_sc_hd__and2_0 _408_ (
    .A(PWDATA[5]),
    .B(_048_),
    .X(_000_[5])
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:190.3-193.25" *)
  sky130_fd_sc_hd__dfrtp_1 _409_ (
    .CLK(PCLK),
    .D(_000_[0]),
    .Q(IC_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:190.3-193.25" *)
  sky130_fd_sc_hd__dfrtp_1 _410_ (
    .CLK(PCLK),
    .D(_000_[1]),
    .Q(IC_REG[1]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:190.3-193.25" *)
  sky130_fd_sc_hd__dfrtp_1 _411_ (
    .CLK(PCLK),
    .D(_000_[2]),
    .Q(IC_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:190.3-193.25" *)
  sky130_fd_sc_hd__dfrtp_1 _412_ (
    .CLK(PCLK),
    .D(_000_[3]),
    .Q(IC_REG[3]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:190.3-193.25" *)
  sky130_fd_sc_hd__dfrtp_1 _413_ (
    .CLK(PCLK),
    .D(_000_[4]),
    .Q(IC_REG[4]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:190.3-193.25" *)
  sky130_fd_sc_hd__dfrtp_1 _414_ (
    .CLK(PCLK),
    .D(_000_[5]),
    .Q(IC_REG[5]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:171.3-175.56" *)
  sky130_fd_sc_hd__dfrtp_1 _415_ (
    .CLK(PCLK),
    .D(_002_),
    .Q(TX_FIFO_FLUSH_REG),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:153.3-157.56" *)
  sky130_fd_sc_hd__dfrtp_1 _416_ (
    .CLK(PCLK),
    .D(_001_),
    .Q(RX_FIFO_FLUSH_REG),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:146.3-149.48" *)
  sky130_fd_sc_hd__dfrtp_1 _417_ (
    .CLK(PCLK),
    .D(_023_),
    .Q(RX_FIFO_THRESHOLD_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:146.3-149.48" *)
  sky130_fd_sc_hd__dfrtp_1 _418_ (
    .CLK(PCLK),
    .D(_022_),
    .Q(RX_FIFO_THRESHOLD_REG[1]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:146.3-149.48" *)
  sky130_fd_sc_hd__dfrtp_1 _419_ (
    .CLK(PCLK),
    .D(_021_),
    .Q(RX_FIFO_THRESHOLD_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:146.3-149.48" *)
  sky130_fd_sc_hd__dfrtp_1 _420_ (
    .CLK(PCLK),
    .D(_028_),
    .Q(RX_FIFO_THRESHOLD_REG[3]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:127.3-129.83" *)
  sky130_fd_sc_hd__dfrtp_1 _421_ (
    .CLK(PCLK),
    .D(_020_),
    .Q(PR_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:127.3-129.83" *)
  sky130_fd_sc_hd__dfstp_2 _422_ (
    .CLK(PCLK),
    .D(_019_),
    .Q(PR_REG[1]),
    .SET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:127.3-129.83" *)
  sky130_fd_sc_hd__dfrtp_1 _423_ (
    .CLK(PCLK),
    .D(_018_),
    .Q(PR_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:127.3-129.83" *)
  sky130_fd_sc_hd__dfrtp_1 _424_ (
    .CLK(PCLK),
    .D(_017_),
    .Q(PR_REG[3]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:127.3-129.83" *)
  sky130_fd_sc_hd__dfrtp_1 _425_ (
    .CLK(PCLK),
    .D(_016_),
    .Q(PR_REG[4]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:127.3-129.83" *)
  sky130_fd_sc_hd__dfrtp_1 _426_ (
    .CLK(PCLK),
    .D(_015_),
    .Q(PR_REG[5]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:127.3-129.83" *)
  sky130_fd_sc_hd__dfrtp_1 _427_ (
    .CLK(PCLK),
    .D(_014_),
    .Q(PR_REG[6]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:127.3-129.83" *)
  sky130_fd_sc_hd__dfrtp_1 _428_ (
    .CLK(PCLK),
    .D(_029_),
    .Q(PR_REG[7]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:187.3-189.81" *)
  sky130_fd_sc_hd__dfrtp_1 _429_ (
    .CLK(PCLK),
    .D(_013_),
    .Q(IM_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:187.3-189.81" *)
  sky130_fd_sc_hd__dfrtp_1 _430_ (
    .CLK(PCLK),
    .D(_012_),
    .Q(IM_REG[1]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:187.3-189.81" *)
  sky130_fd_sc_hd__dfrtp_1 _431_ (
    .CLK(PCLK),
    .D(_011_),
    .Q(IM_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:187.3-189.81" *)
  sky130_fd_sc_hd__dfrtp_1 _432_ (
    .CLK(PCLK),
    .D(_010_),
    .Q(IM_REG[3]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:187.3-189.81" *)
  sky130_fd_sc_hd__dfrtp_1 _433_ (
    .CLK(PCLK),
    .D(_009_),
    .Q(IM_REG[4]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:187.3-189.81" *)
  sky130_fd_sc_hd__dfrtp_1 _434_ (
    .CLK(PCLK),
    .D(_030_),
    .Q(IM_REG[5]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:164.3-167.48" *)
  sky130_fd_sc_hd__dfrtp_1 _435_ (
    .CLK(PCLK),
    .D(_008_),
    .Q(TX_FIFO_THRESHOLD_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:164.3-167.48" *)
  sky130_fd_sc_hd__dfrtp_1 _436_ (
    .CLK(PCLK),
    .D(_007_),
    .Q(TX_FIFO_THRESHOLD_REG[1]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:164.3-167.48" *)
  sky130_fd_sc_hd__dfrtp_1 _437_ (
    .CLK(PCLK),
    .D(_006_),
    .Q(TX_FIFO_THRESHOLD_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:164.3-167.48" *)
  sky130_fd_sc_hd__dfrtp_1 _438_ (
    .CLK(PCLK),
    .D(_031_),
    .Q(TX_FIFO_THRESHOLD_REG[3]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:121.3-123.85" *)
  sky130_fd_sc_hd__dfrtp_1 _439_ (
    .CLK(PCLK),
    .D(_005_),
    .Q(CTRL_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:121.3-123.85" *)
  sky130_fd_sc_hd__dfrtp_1 _440_ (
    .CLK(PCLK),
    .D(_004_),
    .Q(CTRL_REG[1]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:121.3-123.85" *)
  sky130_fd_sc_hd__dfrtp_1 _441_ (
    .CLK(PCLK),
    .D(_032_),
    .Q(CTRL_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:203.3-230.8" *)
  sky130_fd_sc_hd__dfrtp_1 _442_ (
    .CLK(PCLK),
    .D(_033_),
    .Q(RIS_REG[4]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:203.3-230.8" *)
  sky130_fd_sc_hd__dfrtp_1 _443_ (
    .CLK(PCLK),
    .D(_036_),
    .Q(RIS_REG[1]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:203.3-230.8" *)
  sky130_fd_sc_hd__dfrtp_1 _444_ (
    .CLK(PCLK),
    .D(_024_),
    .Q(RIS_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:203.3-230.8" *)
  sky130_fd_sc_hd__dfrtp_1 _445_ (
    .CLK(PCLK),
    .D(_025_),
    .Q(RIS_REG[5]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:203.3-230.8" *)
  sky130_fd_sc_hd__dfrtp_1 _446_ (
    .CLK(PCLK),
    .D(_026_),
    .Q(RIS_REG[3]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:203.3-230.8" *)
  sky130_fd_sc_hd__dfrtp_1 _447_ (
    .CLK(PCLK),
    .D(_027_),
    .Q(RIS_REG[2]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:178.3-180.85" *)
  sky130_fd_sc_hd__dfrtp_1 _448_ (
    .CLK(PCLK),
    .D(_034_),
    .Q(GCLK_REG),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:113.3-115.83" *)
  sky130_fd_sc_hd__dfrtp_1 _449_ (
    .CLK(PCLK),
    .D(_003_),
    .Q(CFG_REG[0]),
    .RESET_B(PRESETn)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:113.3-115.83" *)
  sky130_fd_sc_hd__dfrtp_1 _450_ (
    .CLK(PCLK),
    .D(_035_),
    .Q(CFG_REG[1]),
    .RESET_B(PRESETn)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:67.23-73.4" *)
  ef_util_gating_cell clk_gate_cell (
    .clk(PCLK),
    .clk_en(GCLK_REG),
    .clk_o(clk)
  );
  (* src = "/home/smdadmin/hermes_workspace/projects/PRJ-001/v0/04_frontend_stage/rtl-spi_master/rtl/EF_SPI_APB.v:237.5-268.4" *)
  \$paramod$c472ad5b357594777851f1f1c93c46d2cb71eced\EF_SPI  instance_to_wrap (
    .CPHA(CFG_REG[1]),
    .CPOL(CFG_REG[0]),
    .busy(busy),
    .clk(clk),
    .clk_divider(PR_REG),
    .csb(csb),
    .datai(PWDATA[7:0]),
    .datao(datao),
    .done(done),
    .enable(CTRL_REG[1]),
    .miso(miso),
    .mosi(mosi),
    .rd(rd),
    .rst_n(PRESETn),
    .rx_empty(rx_empty),
    .rx_en(CTRL_REG[2]),
    .rx_flush(RX_FIFO_FLUSH_REG),
    .rx_full(rx_full),
    .rx_level(rx_level),
    .rx_level_above(rx_level_above),
    .rx_threshold(RX_FIFO_THRESHOLD_REG),
    .sclk(sclk),
    .ss(CTRL_REG[0]),
    .tx_empty(tx_empty),
    .tx_flush(TX_FIFO_FLUSH_REG),
    .tx_full(tx_full),
    .tx_level(tx_level),
    .tx_level_below(tx_level_below),
    .tx_threshold(TX_FIFO_THRESHOLD_REG),
    .wr(wr)
  );
  assign RXA = rx_level_above;
  assign TXB = tx_level_below;
  assign RXF = rx_full;
  assign RXE = rx_empty;
  assign TXF = tx_full;
  assign TXE = tx_empty;
  assign TX_FIFO_LEVEL_WIRE = tx_level;
  assign RX_FIFO_LEVEL_WIRE = rx_level;
  assign STATUS_WIRE = { done, busy, rx_level_above, tx_level_below, rx_full, rx_empty, tx_full, tx_empty };
  assign RXDATA_WIRE = datao;
  assign enable = CTRL_REG[1];
  assign ss = CTRL_REG[0];
  assign tx_threshold = TX_FIFO_THRESHOLD_REG;
  assign tx_flush = TX_FIFO_FLUSH_REG;
  assign rx_threshold = RX_FIFO_THRESHOLD_REG;
  assign rx_flush = RX_FIFO_FLUSH_REG;
  assign rx_en = CTRL_REG[2];
  assign datai = PWDATA[7:0];
  assign clk_divider = PR_REG;
  assign CPHA = CFG_REG[1];
  assign CPOL = CFG_REG[0];
  assign rst_n = PRESETn;
  assign clk_gated_en = GCLK_REG;
  assign clk_g = clk;
  assign { PRDATA[31:10], PRDATA[8] } = { PRDATA[9], PRDATA[9], 1'h0, PRDATA[9], PRDATA[9], PRDATA[9], PRDATA[9], 1'h0, PRDATA[9], 1'h0, PRDATA[9], 1'h0, PRDATA[9], PRDATA[9], 1'h0, PRDATA[9], PRDATA[9], 1'h0, PRDATA[9], PRDATA[9], PRDATA[9], PRDATA[9], 1'h0 };
  assign PREADY = 1'h1;
endmodule
